    public const FESTIVALS = [
        'મેષ સંક્રાંતિ (વૈશાખી / પુથંડુ)' =>
        [
            'type' => 'solar_sankranti',
            'rashi' => 0,
            'description' => 'સૌર નવું વર્ષ',
            'regions' =>
            [
                0 => 'સંપૂર્ણ ભારત',
            ],
        ],
        'વૃષભ સંક્રાંતિ' =>
        [
            'type' => 'solar_sankranti',
            'rashi' => 1,
            'description' => 'સૂર્યનો વૃષભ રાશિમાં પ્રવેશ',
            'regions' =>
            [
                0 => 'સંપૂર્ણ ભારત',
            ],
        ],
        'મિથુન સંક્રાંતિ' =>
        [
            'type' => 'solar_sankranti',
            'rashi' => 2,
            'description' => 'સૂર્યનો મિથુન રાશિમાં પ્રવેશ',
            'regions' =>
            [
                0 => 'સંપૂર્ણ ભારત',
            ],
        ],
        'કર્ક સંક્રાંતિ' =>
        [
            'type' => 'solar_sankranti',
            'rashi' => 3,
            'description' => 'સૂર્યનો કર્ક રાશિમાં પ્રવેશ',
            'regions' =>
            [
                0 => 'સંપૂર્ણ ભારત',
            ],
        ],
        'સિંહ સંક્રાંતિ' =>
        [
            'type' => 'solar_sankranti',
            'rashi' => 4,
            'description' => 'સૂર્યનો સિંહ રાશિમાં પ્રવેશ',
            'regions' =>
            [
                0 => 'સંપૂર્ણ ભારત',
            ],
        ],
        'કન્યા સંક્રાંતિ (વિશ્વકર્મા પૂજા)' =>
        [
            'type' => 'solar_sankranti',
            'rashi' => 5,
            'description' => 'દિવ્ય વાસ્તુકાર વિશ્વકર્માની પૂજા',
            'regions' =>
            [
                0 => 'સંપૂર્ણ ભારત',
            ],
            'deity' => 'વિશ્વકર્મા',
        ],
        'તુલા સંક્રાંતિ' =>
        [
            'type' => 'solar_sankranti',
            'rashi' => 6,
            'description' => 'સૂર્યનો તુલા રાશિમાં પ્રવેશ',
            'regions' =>
            [
                0 => 'સંપૂર્ણ ભારત',
            ],
        ],
        'વૃશ્ચિક સંક્રાંતિ' =>
        [
            'type' => 'solar_sankranti',
            'rashi' => 7,
            'description' => 'સૂર્યનો વૃશ્ચિક રાશિમાં પ્રવેશ',
            'regions' =>
            [
                0 => 'સંપૂર્ણ ભારત',
            ],
        ],
        'ધનુ સંક્રાંતિ' =>
        [
            'type' => 'solar_sankranti',
            'rashi' => 8,
            'description' => 'સૂર્યનો ધનુ રાશિમાં પ્રવેશ',
            'regions' =>
            [
                0 => 'સંપૂર્ણ ભારત',
            ],
        ],
        'મકર સંક્રાંતિ (પોંગલ)' =>
        [
            'type' => 'solar_sankranti',
            'rashi' => 9,
            'description' => 'લણણીનો તહેવાર, સૂર્યનો મકર રાશિમાં પ્રવેશ',
            'regions' =>
            [
                0 => 'સંપૂર્ણ ભારત',
            ],
            'deity' => 'સૂર્ય',
        ],
        'કુંભ સંક્રાંતિ' =>
        [
            'type' => 'solar_sankranti',
            'rashi' => 10,
            'description' => 'સૂર્યનો કુંભ રાશિમાં પ્રવેશ',
            'regions' =>
            [
                0 => 'સંપૂર્ણ ભારત',
            ],
        ],
        'મીન સંક્રાંતિ' =>
        [
            'type' => 'solar_sankranti',
            'rashi' => 11,
            'description' => 'સૂર્યનો મીન રાશિમાં પ્રવેશ',
            'regions' =>
            [
                0 => 'સંપૂર્ણ ભારત',
            ],
        ],
        'વાસી ઉત્તરાયણ' =>
        [
            'type' => 'fixed_date',
            'month' => 1,
            'day' => 15,
            'description' => 'ગુજરાતમાં પતંગ મહોત્સવનો બીજો દિવસ',
            'regions' => ['ગુજરાત'],
        ],
        'લોહડી' =>
        [
            'type' => 'fixed_date',
            'month' => 1,
            'day' => 13,
            'description' => 'પંજાબી લણણીનો તહેવાર; શિયાળાના અંતના પ્રતીક રૂપે તાપણાનો ઉત્સવ',
            'deity' => 'અગ્નિ/સૂર્ય',
            'regions' => ['પંજાબ', 'હરિયાણા', 'દિલ્હી', 'ઉત્તર ભારત'],
        ],

        'ચેટી ચંડ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 2,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'સિંધી હિંદુ નવું વર્ષ; ઝૂલેલાલ (ઇષ્ટ-દેવતા) નો જન્મ',
            'deity' => 'ઝૂલેલાલ/વરુણ',
            'regions' => ['સિંધી', 'ગુજરાત', 'રાજસ્થાન'],
        ],
        'વિશુ' =>
        [
            'type' => 'solar_sankranti',
            'rashi' => 0,
            'description' => 'કેરળ હિંદુ નવું વર્ષ; મેડમ મહિનાનો પહેલો દિવસ; વિશુક્કાની સજાવટ',
            'deity' => 'કૃષ્ણ/વિષ્ણુ',
            'regions' => ['કેરળ', 'તમિલનાડુ', 'કર્ણાટક'],
        ],

        'શાસ્ત્રીજી મહારાજ જયંતિ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 5,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'BAPS ના સ્થાપક શાસ્ત્રીજી મહારાજની જયંતિ; વસંત પંચમીના દિવસે',
            'deity' => 'સ્વામિનારાયણ',
        ],

        'પ્રમુખ વર્ણી દિન' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 4,
            'month_amanta' => 'Jyeshtha',
            'month_purnimanta' => 'Jyeshtha',
            'description' => 'તે દિવસ જ્યારે પ્રમુખ સ્વામી મહારાજને BAPS ના વહીવટી પ્રમુખ નિયુક્ત કરવામાં આવ્યા હતા (1950)',
            'deity' => 'સ્વામિનારાયણ',
        ],

        'અષાઢી બીજ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 2,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'કચ્છી નવું વર્ષ; ચોમાસા અને ખરીફ પાકની ઋતુની શરૂઆત; પરંપરાગત હવામાનની આગાહી',
            'deity' => 'વરુણ/ઇન્દ્ર',
            'regions' => ['કચ્છ', 'ગુજરાત'],
        ],

        'રવેચી માતાનો મેળો' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 8,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'રવેચી માતાના મંદિરે (રાપર, કચ્છ) પ્રાચીન મેળો; રબારી અને આહીર સમુદાયના હજારો ભક્તો એકઠા થાય છે',
            'deity' => 'રવેચી માતા',
            'regions' => ['કચ્છ', 'ગુજરાત'],
        ],

        'તરણેતરનો મેળો' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 4,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'ત્રિનેત્રેશ્વર મહાદેવ મંદિરે સૌરાષ્ટ્રનો પ્રખ્યાત મેળો; ભાદરવા સુદ 4-6',
            'deity' => 'શિવ',
            'regions' => ['સૌરાષ્ટ્ર', 'ગુજરાત'],
        ],
        'તરણેતરનો મેળો દિવસ 2' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 5,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'તરણેતર મેળાનો બીજો દિવસ (ભાદરવા સુદ 5)',
            'deity' => 'શિવ',
            'regions' => ['સૌરાષ્ટ્ર', 'ગુજરાત'],
        ],
        'તરણેતરનો મેળો દિવસ 3' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 6,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'તરણેતર મેળાનો ત્રીજો દિવસ (ભાદરવા સુદ 6)',
            'deity' => 'શિવ',
            'regions' => ['સૌરાષ્ટ્ર', 'ગુજરાત'],
        ],

        'મોટા યક્ષનો મેળો (જખ બહોતેરા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 12,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'કાકડભીટ ખાતે કચ્છનો સૌથી મોટો મેળો; 72 યક્ષોનું સન્માન જેમણે સ્થાનિક લોકોની રક્ષા કરી હતી; ભાદરવા વદ 12-14',
            'deity' => '72 યક્ષ',
            'regions' => ['કચ્છ', 'ગુજરાત'],
        ],

        'દાદા મેકણનો મેળો (ધ્રાંગ મેળો)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 14,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Phalguna',
            'description' => 'ધ્રાંગ ગામમાં સંત મેકણ દાદાના સન્માનમાં મેળો, જેમણે કચ્છના રણમાં ભૂલા પડેલા પ્રવાસીઓને બચાવ્યા હતા',
            'deity' => 'મેકણ દાદા',
            'regions' => ['કચ્છ', 'ગુજરાત'],
        ],

        'રંગ પંચમી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 5,
            'month_amanta' => 'Phalguna',
            'month_purnimanta' => 'Phalguna',
            'description' => 'હોળી ઉત્સવનો પાંચમો દિવસ; રંગોના ખેલની નિરંતરતા; વિશેષ રૂપે મહારાષ્ટ્ર અને મધ્ય પ્રદેશમાં ઉજવાય છે',
            'deity' => 'કૃષ્ણ',
            'regions' => ['મહારાષ્ટ્ર', 'મધ્ય પ્રદેશ', 'ઉત્તર ભારત'],
        ],

        'ચૈત્ર (વસંત) નવરાત્રિ દિવસ 1 (શૈલપુત્રી પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 1,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'ચૈત્ર (વસંત) નવરાત્રિ - શૈલપુત્રી (પર્વતની પુત્રી) ની પૂજા',
            'deity' => 'દુર્ગા/શૈલપુત્રી',
            'karmakala_type' => 'sunrise',
        ],
        'ચૈત્ર (વસંત) નવરાત્રિ દિવસ 2 (બ્રહ્મચારિણી પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 2,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'ચૈત્ર (વસંત) નવરાત્રિ - બ્રહ્મચારિણી (તપસ્વિની) ની પૂજા',
            'deity' => 'દુર્ગા/બ્રહ્મચારિણી',
            'karmakala_type' => 'sunrise',
        ],
        'ચૈત્ર (વસંત) નવરાત્રિ દિવસ 3 (ચંદ્રઘંટા પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 3,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'ચૈત્ર (વસંત) નવરાત્રિ - ચંદ્રઘંટા (ચંદ્રમા રૂપી ઘંટ ધારણ કરનારી) ની પૂજા',
            'deity' => 'દુર્ગા/ચંદ્રઘંટા',
            'karmakala_type' => 'sunrise',
        ],
        'ચૈત્ર (વસંત) નવરાત્રિ દિવસ 4 (કૂષ્માંડા પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 4,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'ચૈત્ર (વસંત) નવરાત્રિ - કૂષ્માંડા (બ્રહ્માંડના ઈંડાની રચયિતા) ની પૂજા',
            'deity' => 'દુર્ગા/કૂષ્માંડા',
            'karmakala_type' => 'sunrise',
        ],
        'ચૈત્ર (વસંત) નવરાત્રિ દિવસ 5 (સ્કંદમાતા પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 5,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'ચૈત્ર (વસંત) નવરાત્રિ - સ્કંદમાતા (સ્કંદની માતા) ની પૂજા',
            'deity' => 'દુર્ગા/સ્કંદમાતા',
            'karmakala_type' => 'sunrise',
        ],
        'ચૈત્ર (વસંત) નવરાત્રિ દિવસ 6 (કાત્યાયની પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 6,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'ચૈત્ર (વસંત) નવરાત્રિ - કાત્યાયની (યોદ્ધા દેવી) ની પૂજા',
            'deity' => 'દુર્ગા/કાત્યાયની',
            'karmakala_type' => 'sunrise',
        ],
        'ચૈત્ર (વસંત) નવરાત્રિ દિવસ 7 (કાલરાત્રિ પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 7,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'ચૈત્ર (વસંત) નવરાત્રિ - કાલરાત્રિ (ભયંકર રાત) ની પૂજા / મહા સપ્તમી',
            'deity' => 'દુર્ગા/કાલરાત્રિ',
            'karmakala_type' => 'sunrise',
        ],
        'ચૈત્ર (વસંત) નવરાત્રિ દિવસ 8 (મહાગૌરી પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 8,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'ચૈત્ર (વસંત) નવરાત્રિ - મહાગૌરી (મહાન શ્વેત દેવી) ની પૂજા / મહા અષ્ટમી',
            'deity' => 'દુર્ગા/મહાગૌરી',
            'karmakala_type' => 'sunrise',
        ],
        'ચૈત્ર (વસંત) નવરાત્રિ દિવસ 9 (સિદ્ધિદાત્રી પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 9,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'ચૈત્ર (વસંત) નવરાત્રિ - સિદ્ધિદાત્રી (અલૌકિક શક્તિઓ આપનારી) ની પૂજા / મહા નવમી',
            'deity' => 'દુર્ગા/સિદ્ધિદાત્રી',
            'karmakala_type' => 'sunrise',
        ],
        'આસો શરદ નવરાત્રિ દિવસ 1 (શૈલપુત્રી પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 1,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Ashvina',
            'description' => 'આસો શરદ નવરાત્રિ - શૈલપુત્રી (પર્વતની પુત્રી) ની પૂજા',
            'deity' => 'દુર્ગા/શૈલપુત્રી',
            'karmakala_type' => 'sunrise',
        ],
        'આસો શરદ નવરાત્રિ દિવસ 2 (બ્રહ્મચારિણી પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 2,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Ashvina',
            'description' => 'આસો શરદ નવરાત્રિ - બ્રહ્મચારિણી (તપસ્વિની) ની પૂજા',
            'deity' => 'દુર્ગા/બ્રહ્મચારિણી',
            'karmakala_type' => 'sunrise',
        ],
        'આસો શરદ નવરાત્રિ દિવસ 3 (ચંદ્રઘંટા પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 3,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Ashvina',
            'description' => 'આસો શરદ નવરાત્રિ - ચંદ્રઘંટા (ચંદ્રમા રૂપી ઘંટ ધારણ કરનારી) ની પૂજા',
            'deity' => 'દુર્ગા/ચંદ્રઘંટા',
            'karmakala_type' => 'sunrise',
        ],
        'આસો શરદ નવરાત્રિ દિવસ 4 (કૂષ્માંડા પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 4,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Ashvina',
            'description' => 'આસો શરદ નવરાત્રિ - કૂષ્માંડા (બ્રહ્માંડના ઈંડાની રચયિતા) ની પૂજા',
            'deity' => 'દુર્ગા/કૂષ્માંડા',
            'karmakala_type' => 'sunrise',
        ],
        'આસો શરદ નવરાત્રિ દિવસ 5 (સ્કંદમાતા પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 5,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Ashvina',
            'description' => 'આસો શરદ નવરાત્રિ - સ્કંદમાતા (સ્કંદની માતા) ની પૂજા',
            'deity' => 'દુર્ગા/સ્કંદમાતા',
            'karmakala_type' => 'sunrise',
        ],
        'આસો શરદ નવરાત્રિ દિવસ 6 (કાત્યાયની પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 6,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Ashvina',
            'description' => 'આસો શરદ નવરાત્રિ - કાત્યાયની (યોદ્ધા દેવી) ની પૂજા',
            'deity' => 'દુર્ગા/કાત્યાયની',
            'karmakala_type' => 'sunrise',
        ],
        'આસો શરદ નવરાત્રિ દિવસ 7 (કાલરાત્રિ પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 7,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Ashvina',
            'description' => 'આસો શરદ નવરાત્રિ - કાલરાત્રિ (ભયંકર રાત) ની પૂજા / મહા સપ્તમી',
            'deity' => 'દુર્ગા/કાલરાત્રિ',
            'karmakala_type' => 'sunrise',
        ],
        'દુર્ગા અષ્ટમી (મહાગૌરી પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 8,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Ashvina',
            'description' => 'આસો શરદ નવરાત્રિ - મહાગૌરી (મહાન શ્વેત દેવી) ની પૂજા / મહા અષ્ટમી',
            'deity' => 'દુર્ગા/મહાગૌરી',
            'karmakala_type' => 'sunrise',
        ],
        'મહા નવમી (સિદ્ધિદાત્રી પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 9,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Ashvina',
            'description' => 'આસો શરદ નવરાત્રિ - સિદ્ધિદાત્રી (અલૌકિક શક્તિઓ આપનારી) ની પૂજા / મહા નવમી',
            'deity' => 'દુર્ગા/સિદ્ધિદાત્રી',
            'karmakala_type' => 'sunrise',
        ],
        'અષાઢ ગુપ્ત નવરાત્રિ દિવસ 1 (કાલી પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 1,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'અષાઢ ગુપ્ત નવરાત્રિ (10 મહાવિદ્યાઓ) - કાલી (સમયની સંહારક) ની પૂજા',
            'deity' => 'મહાવિદ્યા/કાલી',
            'karmakala_type' => 'sunrise',
        ],
        'અષાઢ ગુપ્ત નવરાત્રિ દિવસ 2 (તારા પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 2,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'અષાઢ ગુપ્ત નવરાત્રિ (10 મહાવિદ્યાઓ) - તારા (રક્ષક અને માર્ગદર્શક) ની પૂજા',
            'deity' => 'મહાવિદ્યા/તારા',
            'karmakala_type' => 'sunrise',
        ],
        'અષાઢ ગુપ્ત નવરાત્રિ દિવસ 3 (ત્રિપુર સુંદરી પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 3,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'અષાઢ ગુપ્ત નવરાત્રિ (10 મહાવિદ્યાઓ) - ત્રિપુર સુંદરી / ષોડશી (ત્રણેય લોકોની સુંદરી) ની પૂજા',
            'deity' => 'મહાવિદ્યા/ત્રિપુર સુંદરી',
            'karmakala_type' => 'sunrise',
        ],
        'અષાઢ ગુપ્ત નવરાત્રિ દિવસ 4 (ભુવનેશ્વરી પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 4,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'અષાઢ ગુપ્ત નવરાત્રિ (10 મહાવિદ્યાઓ) - ભુવનેશ્વરી (બ્રહ્માંડની દેવી) ની પૂજા',
            'deity' => 'મહાવિદ્યા/ભુવનેશ્વરી',
            'karmakala_type' => 'sunrise',
        ],
        'અષાઢ ગુપ્ત નવરાત્રિ દિવસ 5 (ભૈરવી પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 5,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'અષાઢ ગુપ્ત નવરાત્રિ (10 મહાવિદ્યાઓ) - ભૈરવી (વિનાશ અને પુનર્જન્મની ભયંકર દેવી) ની પૂજા',
            'deity' => 'મહાવિદ્યા/ભૈરવી',
            'karmakala_type' => 'sunrise',
        ],
        'અષાઢ ગુપ્ત નવરાત્રિ દિવસ 6 (છિન્નમસ્તા પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 6,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'અષાઢ ગુપ્ત નવરાત્રિ (10 મહાવિદ્યાઓ) - છિન્નમસ્તા (પોતાનું જ મસ્તક કાપનારી દેવી) ની પૂજા',
            'deity' => 'મહાવિદ્યા/છિન્નમસ્તા',
            'karmakala_type' => 'sunrise',
        ],
        'અષાઢ ગુપ્ત નવરાત્રિ દિવસ 7 (ધૂમાવતી પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 7,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'અષાઢ ગુપ્ત નવરાત્રિ (10 મહાવિદ્યાઓ) - ધૂમાવતી (વિધવા દેવી) ની પૂજા',
            'deity' => 'મહાવિદ્યા/ધૂમાવતી',
            'karmakala_type' => 'sunrise',
        ],
        'અષાઢ ગુપ્ત નવરાત્રિ દિવસ 8 (બગલામુખી પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 8,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'અષાઢ ગુપ્ત નવરાત્રિ (10 મહાવિદ્યાઓ) - બગલામુખી (શત્રુઓને સ્તંભિત કરનારી) ની પૂજા',
            'deity' => 'મહાવિદ્યા/બગલામુખી',
            'karmakala_type' => 'sunrise',
        ],
        'અષાઢ ગુપ્ત નવરાત્રિ દિવસ 9 (માતંગી પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 9,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'અષાઢ ગુપ્ત નવરાત્રિ (10 મહાવિદ્યાઓ) - માતંગી (તાંત્રિક સરસ્વતી / કળા અને સંગીત) ની પૂજા',
            'deity' => 'મહાવિદ્યા/માતંગી',
            'karmakala_type' => 'sunrise',
        ],
        'અષાઢ ગુપ્ત નવરાત્રિ દિવસ 10 (કમલા પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 10,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'અષાઢ ગુપ્ત નવરાત્રિ (10 મહાવિદ્યાઓ) - કમલા (તાંત્રિક લક્ષ્મી / સમૃદ્ધિ અને ફળદ્રુપતા) ની પૂજા',
            'deity' => 'કમલા',
            'karmakala_type' => 'sunrise',
        ],
        'મહા ગુપ્ત નવરાત્રિ દિવસ 1 (કાલી પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 1,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'મહા ગુપ્ત નવરાત્રિ (10 મહાવિદ્યાઓ) - કાલી (સમયની સંહારક) ની પૂજા',
            'deity' => 'મહાવિદ્યા/કાલી',
            'karmakala_type' => 'sunrise',
        ],
        'મહા ગુપ્ત નવરાત્રિ દિવસ 2 (તારા પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 2,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'મહા ગુપ્ત નવરાત્રિ (10 મહાવિદ્યાઓ) - તારા (રક્ષક અને માર્ગદર્શક) ની પૂજા',
            'deity' => 'મહાવિદ્યા/તારા',
            'karmakala_type' => 'sunrise',
        ],
        'મહા ગુપ્ત નવરાત્રિ દિવસ 3 (ત્રિપુર સુંદરી પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 3,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'મહા ગુપ્ત નવરાત્રિ (10 મહાવિદ્યાઓ) - ત્રિપુર સુંદરી / ષોડશી (ત્રણેય લોકોની સુંદરી) ની પૂજા',
            'deity' => 'મહાવિદ્યા/ત્રિપુર સુંદરી',
            'karmakala_type' => 'sunrise',
        ],
        'મહા ગુપ્ત નવરાત્રિ દિવસ 4 (ભુવનેશ્વરી પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 4,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'મહા ગુપ્ત નવરાત્રિ (10 મહાવિદ્યાઓ) - ભુવનેશ્વરી (બ્રહ્માંડની દેવી) ની પૂજા',
            'deity' => 'મહાવિદ્યા/ભુવનેશ્વરી',
            'karmakala_type' => 'sunrise',
        ],
        'મહા ગુપ્ત નવરાત્રિ દિવસ 5 (ભૈરવી પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 5,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'મહા ગુપ્ત નવરાત્રિ (10 મહાવિદ્યાઓ) - ભૈરવી (વિનાશ અને પુનર્જન્મની ભયંકર દેવી) ની પૂજા',
            'deity' => 'મહાવિદ્યા/ભૈરવી',
            'karmakala_type' => 'sunrise',
        ],
        'મહા ગુપ્ત નવરાત્રિ દિવસ 6 (છિન્નમસ્તા પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 6,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'મહા ગુપ્ત નવરાત્રિ (10 મહાવિદ્યાઓ) - છિન્નમસ્તા (પોતાનું જ મસ્તક કાપનારી દેવી) ની પૂજા',
            'deity' => 'મહાવિદ્યા/છિન્નમસ્તા',
            'karmakala_type' => 'sunrise',
        ],
        'મહા ગુપ્ત નવરાત્રિ દિવસ 7 (ધૂમાવતી પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 7,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'મહા ગુપ્ત નવરાત્રિ (10 મહાવિદ્યાઓ) - ધૂમાવતી (વિધવા દેવી) ની પૂજા',
            'deity' => 'મહાવિદ્યા/ધૂમાવતી',
            'karmakala_type' => 'sunrise',
        ],
        'મહા ગુપ્ત નવરાત્રિ દિવસ 8 (બગલામુખી પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 8,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'મહા ગુપ્ત નવરાત્રિ (10 મહાવિદ્યાઓ) - બગલામુખી (શત્રુઓને સ્તંભિત કરનારી) ની પૂજા',
            'deity' => 'મહાવિદ્યા/બગલામુખી',
            'karmakala_type' => 'sunrise',
        ],
        'મહા ગુપ્ત નવરાત્રિ દિવસ 9 (માતંગી પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 9,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'મહા ગુપ્ત નવરાત્રિ (10 મહાવિદ્યાઓ) - માતંગી (તાંત્રિક સરસ્વતી / કળા અને સંગીત) ની પૂજા',
            'deity' => 'મહાવિદ્યા/માતંગી',
            'karmakala_type' => 'sunrise',
        ],
        'મહા ગુપ્ત નવરાત્રિ દિવસ 10 (કમલા પૂજા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 10,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'મહા ગુપ્ત નવરાત્રિ (10 મહાવિદ્યાઓ) - કમલા (તાંત્રિક લક્ષ્મી / સમૃદ્ધિ અને ફળદ્રુપતા) ની પૂજા',
            'deity' => 'કમલા',
            'karmakala_type' => 'sunrise',
        ],
        'શીતળા અષ્ટમી (બસોડા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 8,
            'month_amanta' => 'Phalguna',
            'month_purnimanta' => 'Chaitra',
            'description' => 'રોગોથી બચવા માટે દેવી શીતળાની પૂજા',
            'deity' => 'શીતળા માતા',
        ],
        'પાપમોચની એકાદશી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 11,
            'month_amanta' => 'Phalguna',
            'month_purnimanta' => 'Chaitra',
            'description' => 'પાપમોચની એકાદશી માટે વ્રત (પાપોમાંથી મુક્તિ)',
            'deity' => 'વિષ્ણુ',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'ઉગાદી / ગુડી પડવો' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 1,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'ચંદ્ર નવું વર્ષ / ચૈત્ર મહિનાનો પહેલો દિવસ',
            'deity' => 'બ્રહ્મા',
            'karmakala_type' => 'sunrise',
        ],
        'ગણગૌર' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 3,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'ગૌરીની પૂજા',
            'deity' => 'પાર્વતી',
        ],
        'યમુના છઠ / ચૈતી છઠ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 6,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'દેવી યમુનાનું અવતરણ / ઉનાળુ છઠ',
            'deity' => 'સૂર્ય/યમુના',
        ],
        'રામ નવમી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 9,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'ભગવાન રામ (વિષ્ણુના સાતમા અવતાર) ની જન્મજયંતિ',
            'deity' => 'રામ',
            'fasting' => true,
            'karmakala_type' => 'madhyahna',
            'strict_karmakala' => true,
        ],
        'સ્વામિનારાયણ જયંતિ (હરિ-નોમ)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 9,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'ભગવાન સ્વામિનારાયણનો જન્મ; સભાઓ, સાંસ્કૃતિક કાર્યક્રમો અને ભજન કીર્તન સાથે ઉજવાય છે',
            'deity' => 'સ્વામિનારાયણ',
            'fasting' => true,
            'karmakala_type' => 'madhyahna',
            'strict_karmakala' => true,
        ],
        'કામદા એકાદશી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 11,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'કામદા એકાદશી માટે વ્રત (મનોકામનાઓ પૂર્ણ કરનારી)',
            'deity' => 'વિષ્ણુ',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'હનુમાન જયંતિ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'ભગવાન હનુમાનનો જન્મોત્સવ',
            'deity' => 'હનુમાન',
            'karmakala_type' => 'sunrise',
        ],
        'વરુથિની એકાદશી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 11,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Vaishakha',
            'description' => 'વરુથિની એકાદશી માટે વ્રત',
            'deity' => 'વિષ્ણુ',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'પરશુરામ જયંતિ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 3,
            'month_amanta' => 'Vaishakha',
            'month_purnimanta' => 'Vaishakha',
            'description' => 'ભગવાન પરશુરામનો જન્મ',
            'deity' => 'પરશુરામ',
        ],
        'અખા ત્રીજ (અક્ષય તૃતીયા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 3,
            'month_amanta' => 'Vaishakha',
            'month_purnimanta' => 'Vaishakha',
            'description' => 'નવી શરૂઆત માટે સૌથી શુભ દિવસ',
            'deity' => 'વિષ્ણુ/લક્ષ્મી',
            'karmakala_type' => 'sunrise',
        ],
        'આદિ શંકરાચાર્ય જયંતિ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 5,
            'month_amanta' => 'Vaishakha',
            'month_purnimanta' => 'Vaishakha',
            'description' => 'આદિ શંકરાચાર્યની જયંતિ',
            'deity' => 'શિવ/શંકરાચાર્ય',
        ],
        'ગંગા સપ્તમી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 7,
            'month_amanta' => 'Vaishakha',
            'month_purnimanta' => 'Vaishakha',
            'description' => 'ગંગા નદીનો પુનર્જન્મ',
            'deity' => 'ગંગા',
        ],
        'સીતા નવમી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 9,
            'month_amanta' => 'Vaishakha',
            'month_purnimanta' => 'Vaishakha',
            'description' => 'દેવી સીતાની જન્મજયંતિ',
            'deity' => 'સીતા',
        ],
        'મોહિની એકાદશી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 11,
            'month_amanta' => 'Vaishakha',
            'month_purnimanta' => 'Vaishakha',
            'description' => 'મોહિની એકાદશી માટે વ્રત',
            'deity' => 'વિષ્ણુ',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'નૃસિંહ જયંતિ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 14,
            'month_amanta' => 'Vaishakha',
            'month_purnimanta' => 'Vaishakha',
            'description' => 'ભગવાન નૃસિંહનો પ્રાગટ્ય દિવસ',
            'deity' => 'નૃસિંહ',
            'fasting' => true,
            'karmakala_type' => 'pradosha',
            'strict_karmakala' => true,
        ],
        'બુદ્ધ પૂર્ણિમા' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Vaishakha',
            'month_purnimanta' => 'Vaishakha',
            'description' => 'વૈશાખી પૂર્ણિમા — સુગત બુદ્ધ (વિષ્ણુનો 9મો અવતાર, બૌદ્ધ ધર્મના ગૌતમ બુદ્ધથી અલગ) અને કૂર્મ જયંતિ (ભગવાન વિષ્ણુના કાચબા અવતારનો જન્મ) નો હિંદુ તહેવાર. ભાગવત પુરાણ 1.3.24 અને અગ્નિ પુરાણમાં હિંદુ બુદ્ધ-અવતારનું વર્ણન કીકટ/ગયામાં રાક્ષસોને વૈદિક અનુષ્ઠાનોથી ભ્રમિત કરવા (ભાગવત દૃષ્ટિકોણ) અથવા કરુણા શીખવવા અને પશુબલિને સમાપ્ત કરવા (જયદેવનો ગીત ગોવિંદ દૃષ્ટિકોણ) પ્રગટ થવા તરીકે કરવામાં આવ્યું છે. પુરીના શંકરાચાર્ય સ્વામી નિશ્ચલાનંદ સરસ્વતી અને વિદ્વાનો આમને બે અલગ અલગ વ્યક્તિઓ તરીકે માને છે: પૌરાણિક સુગત બુદ્ધ (બ્રાહ્મણ વર્ણ, વેદોનું સમર્થન, પ્રાચીન સમયરેખા) વિરુદ્ધ ગૌતમ બુદ્ધ (ક્ષત્રિય શાક્ય વંશ, લુમ્બિની જન્મ ~563 ઈસા પૂર્વે, વેદોને નકાર્યા). આ દિવસ કૂર્મ જયંતિ સાથે પણ સુસંગત છે અને સત્યનારાયણ પૂજા માટે સૌથી શુભ દિવસ છે. પ્રાદેશિક ભિન્નતા: ઓડિશા અને બંગાળની પરંપરાઓમાં દશાવતારમાં 9મા અવતાર તરીકે બુદ્ધના સ્થાને બલરામને ગણવામાં આવે છે.',
            'deity' => 'સુગત બુદ્ધ/કૂર્મ/વિષ્ણુ',
            'karmakala_type' => 'sunrise',
        ],
        'નરસિંહ મહેતા જન્મ જયંતિ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Vaishakha',
            'month_purnimanta' => 'Vaishakha',
            'description' => 'આદિ કવિ નરસિંહ મહેતાની જન્મજયંતિ',
            'deity' => 'કૃષ્ણ/નરસિંહ મહેતા',
        ],
        'અપરા એકાદશી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 11,
            'month_amanta' => 'Vaishakha',
            'month_purnimanta' => 'Jyeshtha',
            'description' => 'અપરા એકાદશી માટે વ્રત',
            'deity' => 'વિષ્ણુ',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'યોગી મહારાજ જયંતિ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 12,
            'month_amanta' => 'Vaishakha',
            'month_purnimanta' => 'Jyeshtha',
            'description' => 'બ્રહ્મસ્વરૂપ યોગી મહારાજનો જન્મ',
            'deity' => 'સ્વામિનારાયણ',
        ],
        'શનિ જયંતિ / સાવિત્રી અમાસ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 15,
            'month_amanta' => 'Vaishakha',
            'month_purnimanta' => 'Jyeshtha',
            'description' => 'ભગવાન શનિનો જન્મ / સાવિત્રી વ્રત',
            'deity' => 'શનિ/સાવિત્રી',
        ],
        'જમાઈ ષષ્ઠી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 6,
            'month_amanta' => 'Jyeshtha',
            'month_purnimanta' => 'Jyeshtha',
            'description' => 'જમાઈને સમર્પિત બંગાળી તહેવાર',
            'deity' => 'ષષ્ઠી',
        ],
        'મહેશ નવમી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 9,
            'month_amanta' => 'Jyeshtha',
            'month_purnimanta' => 'Jyeshtha',
            'description' => 'માહેશ્વરી સમાજ દ્વારા ભગવાન શિવની પૂજા',
            'deity' => 'શિવ',
        ],
        'ગંગા દશેરા' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 10,
            'month_amanta' => 'Jyeshtha',
            'month_purnimanta' => 'Jyeshtha',
            'description' => 'પૃથ્વી પર માતા ગંગાનું અવતરણ',
            'deity' => 'ગંગા',
            'karmakala_type' => 'sunrise',
        ],
        'નિર્જળા એકાદશી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 11,
            'month_amanta' => 'Jyeshtha',
            'month_purnimanta' => 'Jyeshtha',
            'description' => 'સૌથી કઠિન એકાદશી વ્રત (પાણી વિના કરવામાં આવતું) / ગાયત્રી જયંતિ',
            'deity' => 'વિષ્ણુ/ગાયત્રી',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'વટ પૂર્ણિમા' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Jyeshtha',
            'month_purnimanta' => 'Jyeshtha',
            'description' => 'પૂર્ણિમાન્ત કેલેન્ડર મુજબ વટ સાવિત્રી વ્રત',
            'deity' => 'સાવિત્રી/બ્રહ્મા',
            'fasting' => true,
        ],
        'યોગિની એકાદશી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 11,
            'month_amanta' => 'Jyeshtha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'યોગિની એકાદશી માટે વ્રત',
            'deity' => 'વિષ્ણુ',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'જગન્નાથ રથયાત્રા' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 2,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'ભગવાન જગન્નાથનો રથ મહોત્સવ',
            'deity' => 'જગન્નાથ',
            'karmakala_type' => 'sunrise',
        ],
        'દેવપોઢી એકાદશી (Devshayani)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 11,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'ચાતુર્માસ પ્રારંભ, ભગવાન વિષ્ણુ યોગનિદ્રામાં જાય છે',
            'deity' => 'વિષ્ણુ',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'ગૌરી વ્રત (મોળાકાત) પ્રારંભ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 11,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'નાની કન્યાઓ દ્વારા 5 દિવસનું વ્રત (મીઠા વગરનું)',
            'deity' => 'ગૌરી/પાર્વતી',
        ],
        'જયા પાર્વતી વ્રત પ્રારંભ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 13,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'વૈવાહિક સુખ અને સારા પતિ માટે 5 દિવસનું વ્રત',
            'deity' => 'જયા/પાર્વતી',
        ],
        'ગુરુ પૂર્ણિમા' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'આધ્યાત્મિક ગુરુઓ અને મહર્ષિ વ્યાસનું સન્માન',
            'deity' => 'વ્યાસ',
            'karmakala_type' => 'sunrise',
        ],
        'કામિકા એકાદશી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 11,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Shravana',
            'description' => 'કામિકા એકાદશી માટે વ્રત',
            'deity' => 'વિષ્ણુ',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'હરિયાળી ત્રીજ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 3,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Shravana',
            'description' => 'વરસાદને આવકારતો ચોમાસાનો તહેવાર',
            'deity' => 'પાર્વતી/શિવ',
        ],
        'નાગ પંચમી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 5,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Shravana',
            'description' => 'સર્પ દેવતાઓની પૂજા',
            'deity' => 'નાગ',
        ],
        'કલ્કિ જયંતિ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 6,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Shravana',
            'description' => 'કલ્કિ અવતારનો જન્મ',
            'deity' => 'કલ્કિ',
        ],
        'તુલસીદાસ જયંતિ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 7,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Shravana',
            'description' => 'ગોસ્વામી તુલસીદાસની જયંતિ',
            'deity' => 'રામ/તુલસીદાસ',
        ],
        'શ્રાવણ પુત્રદા એકાદશી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 11,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Shravana',
            'description' => 'પુત્ર પ્રાપ્તિ માટેનું વ્રત',
            'deity' => 'વિષ્ણુ',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'રક્ષાબંધન / અવની અવિટ્ટમ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Shravana',
            'description' => 'ભાઈ-બહેનનો સંબંધ / હયગ્રીવ જન્મ / ઉપાકર્મ',
            'deity' => 'હયગ્રીવ',
            'karmakala_type' => 'aparahna',
            'strict_karmakala' => true,
        ],
        'પોળા / કુશોત્પાટિની અમાસ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 15,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'ખેડૂતો અને બળદો માટે આભાર માનતો તહેવાર',
            'deity' => 'શિવ',
        ],
        'અજા એકાદશી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 11,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'અજા એકાદશી માટે વ્રત',
            'deity' => 'વિષ્ણુ',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'ગોગા પાંચમ (નાગ પંચમી - ગુજરાત)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 5,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'ગોગા જી / ગોગા મહારાજ અને સર્પ દેવતાઓનું સન્માન કરતી ગુજરાતી નાગ પંચમી',
            'deity' => 'ગોગા જી / ગોગા બાપા',
            'regions' => ['ગુજરાત'],
        ],
        'શ્રાવણ સોમવાર (સોમવાર વ્રત)' =>
        [
            'type' => 'weekday_in_month',
            'weekday' => 1,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Shravana',
            'description' => 'ભગવાન શિવને સમર્પિત શ્રાવણ માસનો શુભ સોમવાર',
            'deity' => 'શિવ',
            'fasting' => true,
        ],
        'કજરી ત્રીજ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 3,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'કજરી ત્રીજ ઉત્સવ',
            'deity' => 'પાર્વતી/શિવ',
        ],
        'બોળ ચોથ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 4,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'ગાયો અને વાછરડાઓની પૂજા (બહુલા ચતુર્થી)',
            'deity' => 'કૃષ્ણ/ગાયો',
        ],
        'રાંધણ છઠ / બલરામ જયંતિ (હલ ષષ્ઠી)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 6,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'ગુજરાતી રાંધણ છઠ અને કૃષ્ણ ષષ્ઠીના દિવસે વ્યાપક હલ ષષ્ઠી / બલરામ જયંતિનું પર્વ',
            'deity' => 'બલરામ',
        ],
        'શીતળા સાતમ / શીતળા સપ્તમી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 7,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'શીતળા માતાનું પર્વ, જે ગુજરાતમાં શીતળા સાતમ તરીકે ઓળખાય છે, આરોગ્ય માટેની પ્રાર્થના અને ટાઢું ભોજન આરોગવાથી ઉજવાય છે',
            'deity' => 'શીતળા માતા',
            'fasting' => true,
        ],
        'કૃષ્ણ જન્માષ્ટમી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 8,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'ભગવાન કૃષ્ણનો જન્મોત્સવ',
            'deity' => 'કૃષ્ણ',
            'fasting' => true,
            'karmakala_type' => 'nishitha',
            'strict_karmakala' => true,
            'vriddhi_preference' => 'last',
        ],
        'હરતાલિકા ત્રીજ / કેવડા ત્રીજ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 3,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'હરતાલિકા ત્રીજ, જે ગુજરાતમાં કેવડા ત્રીજ તરીકે ઓળખાય છે, સ્ત્રીઓ દ્વારા પાર્વતી અને શિવના માનમાં ઉજવવામાં આવે છે',
            'deity' => 'પાર્વતી/શિવ',
        ],
        'વરાહ જયંતિ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 3,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'ભગવાન વરાહનો પ્રાગટ્ય દિવસ',
            'deity' => 'વિષ્ણુ/વરાહ',
        ],
        'ગણેશ ચતુર્થી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 4,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'ભગવાન ગણેશની જયંતિ',
            'deity' => 'ગણેશ',
            'karmakala_type' => 'madhyahna',
            'strict_karmakala' => true,
        ],
        'ઋષિ પંચમી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 5,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'સપ્તર્ષિઓની પૂજા',
            'deity' => 'સપ્તર્ષિ',
            'karmakala_type' => 'madhyahna',
        ],
        'રાધા અષ્ટમી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 8,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'રાધારાણીની જયંતિ',
            'deity' => 'રાધા',
            'karmakala_type' => 'madhyahna',
        ],
        'પાર્શ્વ એકાદશી / જળ ઝીલણી એકાદશી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 11,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'ભગવાન વિષ્ણુ પડખું ફરે છે / સ્વામિનારાયણ જળ ઝીલણી ઉત્સવ',
            'deity' => 'વિષ્ણુ/સ્વામિનારાયણ',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'મહંત સ્વામી મહારાજ જન્મ જયંતિ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 9,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'મહંત સ્વામી મહારાજનો ભૌતિક જન્મ દિવસ (13 સપ્ટેમ્બર 1933, ભાદરવા વદ 9)',
            'deity' => 'સ્વામિનારાયણ',
        ],
        'મહંત સ્વામી મહારાજ પાર્ષદી દીક્ષા દિન (સત્તાવાર જયંતિ)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 1,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'પાર્ષદી દીક્ષા દિન (2 ફેબ્રુઆરી 1957, મહા વદ 1) પર મહંત સ્વામી મહારાજ જયંતિનો સત્તાવાર BAPS ઉત્સવ',
            'deity' => 'સ્વામિનારાયણ',
        ],
        'વામન જયંતિ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 12,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'વામન અવતારનો જન્મ',
            'deity' => 'વામન',
        ],
        'અનંત ચતુર્દશી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 14,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'ભગવાન અનંતની પૂજા; ગણેશ વિસર્જન',
            'deity' => 'વિષ્ણુ/ગણેશ',
            'karmakala_type' => 'sunrise',
        ],
        'પિતૃ પક્ષ પ્રારંભ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'પૂર્વજોના પખવાડિયાની શરૂઆત',
            'deity' => 'પિતૃ',
        ],
        'ઇન્દિરા એકાદશી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 11,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Ashvina',
            'description' => 'ઇન્દિરા એકાદશી માટે વ્રત',
            'deity' => 'વિષ્ણુ',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'મહાલય અમાસ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 15,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Ashvina',
            'description' => 'પિતૃ પક્ષનો અંતિમ દિવસ (સર્વપિતૃ અમાસ)',
            'deity' => 'પિતૃ',
            'karmakala_type' => 'aparahna',
        ],
        'લલિતા પંચમી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 5,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Ashvina',
            'description' => 'નવરાત્રિ દરમિયાન દેવી લલિતા ત્રિપુરસુંદરીની પૂજા',
            'deity' => 'લલિતા',
        ],
        'દશેરા / વિજયાદશમી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 10,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Ashvina',
            'description' => 'રાવણ પર ભગવાન રામનો વિજય / શરદ નવરાત્રિનું સમાપન',
            'deity' => 'રામ/દુર્ગા',
            'karmakala_type' => 'aparahna',
            'strict_karmakala' => true,
        ],
        'પાપાંકુશા એકાદશી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 11,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Ashvina',
            'description' => 'પાપાંકુશા એકાદશી માટે વ્રત',
            'deity' => 'વિષ્ણુ',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'શરદ પૂર્ણિમા / માણેકઠારી પૂનમ / ગુણાતીતાનંદ સ્વામી જયંતિ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Ashvina',
            'description' => 'શરદ પૂર્ણિમા, જે ગુજરાતમાં માણેકઠારી પૂનમ તરીકે ઓળખાય છે, અને ગુણાતીતાનંદ સ્વામીની જન્મજયંતિ',
            'deity' => 'લક્ષ્મી/કૃષ્ણ/સ્વામિનારાયણ',
            'karmakala_type' => 'nishitha',
        ],
        'વાલ્મીકિ જયંતિ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Ashvina',
            'description' => 'મહર્ષિ વાલ્મીકિની જન્મજયંતિ',
            'deity' => 'વાલ્મીકિ',
        ],
        'રમા એકાદશી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 11,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Kartika',
            'description' => 'રમા એકાદશી માટે વ્રત',
            'deity' => 'વિષ્ણુ',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'કરવા ચોથ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 4,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Kartika',
            'description' => 'પરિણીત સ્ત્રીઓ પતિના લાંબા આયુષ્ય માટે વ્રત રાખે છે',
            'deity' => 'પાર્વતી/શિવ',
            'fasting' => true,
        ],
        'અહોઈ અષ્ટમી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 8,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Kartika',
            'description' => 'માતાઓ બાળકોની સુખાકારી માટે વ્રત રાખે છે',
            'deity' => 'અહોઈ માતા',
            'fasting' => true,
            'karmakala_type' => 'pradosha',
        ],
        'વાઘ બારસ (ગોવત્સ દ્વાદશી)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 12,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Kartika',
            'description' => 'ગાયો અને વાછરડાઓની પૂજા',
            'deity' => 'કૃષ્ણ/ગાયો',
            'karmakala_type' => 'pradosha',
        ],
        'ધનતેરસ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 13,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Kartika',
            'description' => 'લક્ષ્મી અને ધન્વંતરિની પૂજા',
            'deity' => 'લક્ષ્મી/ધન્વંતરિ',
            'karmakala_type' => 'pradosha',
            'strict_karmakala' => true,
        ],
        'કાળી ચૌદશ (નરક ચતુર્દશી)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 14,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Kartika',
            'description' => 'દેવી કાલીની પૂજા અને નરકાસુર પર વિજય',
            'deity' => 'કાલી/હનુમાન/કૃષ્ણ',
            'karmakala_type' => 'nishitha',
            'strict_karmakala' => true,
        ],
        'કાલી પૂજા / દિવાળી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 15,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Kartika',
            'description' => 'રોશનીનો તહેવાર / દેવી કાલીની પૂજા',
            'deity' => 'લક્ષ્મી/કાલી/ગણેશ',
            'karmakala_type' => 'pradosha',
            'strict_karmakala' => true,
            'vriddhi_preference' => 'first',
        ],
        'ગોવર્ધન પૂજા / બેસતું વર્ષ / અન્નકૂટ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 1,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Kartika',
            'description' => 'અન્નકૂટ (સ્વામિનારાયણ) / ગુજરાતી નવું વર્ષ',
            'deity' => 'કૃષ્ણ',
            'karmakala_type' => 'sunrise',
        ],
        'ભાઈ બીજ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 2,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Kartika',
            'description' => 'ભાઈ-બહેનના સંબંધનો ઉત્સવ',
            'deity' => 'યમ/યમુના',
            'karmakala_type' => 'aparahna',
        ],
        'લાભ પાંચમ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 5,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Kartika',
            'description' => 'ગુજરાતમાં વ્યવસાય માટે શુભ દિવસ',
            'deity' => 'લક્ષ્મી/ગણેશ',
        ],
        'સ્કંદ ષષ્ઠી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 6,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Kartika',
            'description' => 'ભગવાન મુરુગનને સમર્પિત છ દિવસીય ઉત્સવ, રાક્ષસ સૂરપદ્મન પર તેમની જીતની ઉજવણી',
            'deity' => 'મુરુગન/સ્કંદ',
            'fasting' => true,
            'regions' => ['તમિલનાડુ', 'કેરળ', 'કર્ણાટક', 'આંધ્ર પ્રદેશ', 'તેલંગાણા'],
        ],
        'છઠ પૂજા (સંધ્યા અર્ઘ્ય)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 6,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Kartika',
            'description' => 'છઠ પૂજાનો મુખ્ય દિવસ (4 માંથી ત્રીજો) - સૂર્યને સંધ્યા અર્ઘ્ય; પર્વ કાર્તિક શુક્લ 4-7 સુધી ચાલે છે',
            'deity' => 'સૂર્ય/છઠ્ઠી મૈયા',
            'fasting' => true,
            'regions' => ['બિહાર', 'ઝારખંડ', 'પૂર્વી યુપી', 'નેપાળ'],
            'karmakala_type' => 'aparahna',
        ],
        'જલારામ જયંતિ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 7,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Kartika',
            'description' => 'વીરપુરના સંત જલારામ બાપાની જયંતિ',
            'deity' => 'રામ/જલારામ બાપા',
        ],
        'ગોપાષ્ટમી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 8,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Kartika',
            'description' => 'ગાયોની પૂજા અને ઉત્સવ',
            'deity' => 'કામધેનુ/કૃષ્ણ',
        ],
        'જગદ્ધાત્રી પૂજા' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 9,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Kartika',
            'description' => 'બંગાળમાં દેવી જગદ્ધાત્રીની પૂજા',
            'deity' => 'જગદ્ધાત્રી',
        ],
        'પ્રમુખ સ્વામી મહારાજ જયંતિ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 8,
            'month_amanta' => 'Margashirsha',
            'month_purnimanta' => 'Margashirsha',
            'description' => 'પ્રમુખ સ્વામી મહારાજની જન્મજયંતિ (7 ડિસેમ્બર 1921, માગશર સુદ 8, વિક્રમ સંવત 1978)',
            'deity' => 'સ્વામિનારાયણ',
        ],
        'દેવઉઠી (પ્રબોધિની) એકાદશી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 11,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Kartika',
            'description' => 'પ્રબોધિની એકાદશી / ચાતુર્માસની પૂર્ણાહુતિ',
            'deity' => 'વિષ્ણુ/સ્વામિનારાયણ',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'તુલસી વિવાહ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 12,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Kartika',
            'description' => 'તુલસી અને ભગવાન વિષ્ણુનો ઔપચારિક વિવાહ',
            'deity' => 'તુલસી/વિષ્ણુ',
        ],
        'વૈકુંઠ ચતુર્દશી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 14,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Kartika',
            'description' => 'વિષ્ણુ અને શિવ બંનેના ભક્તો માટે પવિત્ર દિવસ',
            'deity' => 'વિષ્ણુ/શિવ',
            'karmakala_type' => 'nishitha',
        ],
        'દેવ દિવાળી (ત્રિપુરારી પૂર્ણિમા)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Kartika',
            'description' => 'ત્રિપુરાસુર પર શિવના વિજયની ઉજવણી કરતો વારાણસીનો તહેવાર; ઘાટોને દીવાઓથી શણગારવામાં આવે છે',
            'deity' => 'શિવ',
            'regions' => ['વારાણસી', 'ઉત્તર પ્રદેશ'],
            'karmakala_type' => 'pradosha',
        ],
        'કાર્તિગઈ દીપમ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Kartika',
            'description' => 'પ્રકાશનો તમિલ તહેવાર; તિરુવન્નામલઈમાં મહા દીપમ પ્રગટાવવામાં આવે છે',
            'deity' => 'શિવ/કારતિકેય',
            'regions' => ['તમિલનાડુ', 'કેરળ', 'કર્ણાટક', 'આંધ્ર પ્રદેશ', 'તેલંગાણા'],
            'karmakala_type' => 'pradosha',
        ],
        'ઉત્પન્ના એકાદશી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 11,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Margashirsha',
            'description' => 'ઉત્પન્ના એકાદશી માટે વ્રત',
            'deity' => 'વિષ્ણુ',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'વચનામૃત જયંતિ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 4,
            'month_amanta' => 'Margashirsha',
            'month_purnimanta' => 'Margashirsha',
            'description' => 'વચનામૃતનું સ્મરણોત્સવ',
            'deity' => 'સ્વામિનારાયણ',
        ],
        'કાલભૈરવ જયંતિ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 8,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Margashirsha',
            'description' => 'ભગવાન કાલભૈરવ (શિવ) નો જન્મ',
            'deity' => 'કાલભૈરવ',
        ],
        'વિવાહ પંચમી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 5,
            'month_amanta' => 'Margashirsha',
            'month_purnimanta' => 'Margashirsha',
            'description' => 'રામ અને સીતાની વિવાહ વર્ષગાંઠ',
            'deity' => 'રામ/સીતા',
        ],
        'ગીતા જયંતિ / મોક્ષદા એકાદશી / વૈકુંઠ એકાદશી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 11,
            'month_amanta' => 'Margashirsha',
            'month_purnimanta' => 'Margashirsha',
            'description' => 'ભગવદ્ ગીતાનો ઉત્સવ / મોક્ષનું દ્વાર',
            'deity' => 'કૃષ્ણ/વિષ્ણુ',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'દત્તાત્રેય જયંતિ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Margashirsha',
            'month_purnimanta' => 'Margashirsha',
            'description' => 'ભગવાન દત્તાત્રેયનો જન્મ (અન્નપૂર્ણા જયંતિ)',
            'deity' => 'દત્તાત્રેય/અન્નપૂર્ણા',
            'karmakala_type' => 'pradosha',
        ],
        'સફલા એકાદશી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 11,
            'month_amanta' => 'Margashirsha',
            'month_purnimanta' => 'Pausha',
            'description' => 'સફલા એકાદશી માટે વ્રત',
            'deity' => 'વિષ્ણુ',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'પોષ પુત્રદા એકાદશી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 11,
            'month_amanta' => 'Pausha',
            'month_purnimanta' => 'Pausha',
            'description' => 'પોષ પુત્રદા એકાદશી માટે વ્રત',
            'deity' => 'વિષ્ણુ',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'શાકંભરી પૂર્ણિમા' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Pausha',
            'month_purnimanta' => 'Pausha',
            'description' => 'શાકંભરી નવરાત્રિની પૂર્ણાહુતિ; દેવી શાકંભરીની પૂજા જેમણે શાકભાજી અને ફળોથી વિશ્વનું પોષણ કર્યું',
            'deity' => 'શાકંભરી/દેવી',
            'regions' => ['રાજસ્થાન', 'ઉત્તર પ્રદેશ', 'મધ્ય પ્રદેશ', 'બિહાર'],
        ],
        'થાઈ પૂસમ' =>
        [
            'nakshatra_only' => true,
            'nakshatra' => 'Pushya',
            'requires_purnima' => true,
            'allowed_months_amanta' => ['Pausha', 'Magha'],
            'description' => 'ભગવાન મુરુગનને સમર્પિત તમિલ તહેવાર; તે ત્યારે ઉજવાય છે જ્યારે તમિલ મહિના થાઈ (જાન્યુઆરી-ફેબ્રુઆરી) માં પુષ્ય નક્ષત્ર પૂર્ણિમા સાથે આવે છે',
            'deity' => 'મુરુગન',
            'regions' => ['તમિલનાડુ', 'કેરળ', 'કર્ણાટક', 'આંધ્ર પ્રદેશ', 'તેલંગાણા', 'શ્રીલંકા', 'મલેશિયા', 'સિંગાપોર'],
        ],
        'ઓણમ (તિરુવોણમ)' =>
        [
            'nakshatra_only' => true,
            'nakshatra' => 'Shravana',
            'allowed_months_amanta' => ['Shravana', 'Bhadrapada'],
            'description' => 'કેરળનો લણણીનો તહેવાર; મલયાલમ મહિના ચિંગમ (ઓગસ્ટ-સપ્ટેમ્બર) માં તિરુવોણમ નક્ષત્ર (શ્રવણ); રાજા મહાબલીની વાર્ષિક મુલાકાતનું પ્રતીક છે',
            'deity' => 'વિષ્ણુ/મહાબલી',
            'regions' => ['કેરળ', 'તમિલનાડુ', 'કર્ણાટક'],
            'karmakala_type' => 'madhyahna',
        ],
        'ગુણાતીતાનંદ સ્વામી દીક્ષા દિન' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Pausha',
            'month_purnimanta' => 'Pausha',
            'description' => 'ગુણાતીતાનંદ સ્વામીનો દીક્ષા દિવસ',
            'deity' => 'સ્વામિનારાયણ',
        ],
        'ષટતિલા એકાદશી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 11,
            'month_amanta' => 'Pausha',
            'month_purnimanta' => 'Magha',
            'description' => 'ષટતિલા એકાદશી માટે વ્રત',
            'deity' => 'વિષ્ણુ',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'મૌની અમાસ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 15,
            'month_amanta' => 'Pausha',
            'month_purnimanta' => 'Magha',
            'description' => 'કઠોર મૌન વ્રત અને પવિત્ર સ્નાનનો દિવસ',
            'deity' => 'વિષ્ણુ',
            'fasting' => true,
        ],
        'વસંત પંચમી / શિક્ષાપત્રી જયંતિ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 5,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'દેવી સરસ્વતીની પૂજા / શિક્ષાપત્રી જયંતિ',
            'deity' => 'સરસ્વતી/સ્વામિનારાયણ',
            'karmakala_type' => 'sunrise',
        ],
        'રથ સપ્તમી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 7,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'સૂર્ય જયંતિ',
            'deity' => 'સૂર્ય',
        ],
        'ભીષ્મ અષ્ટમી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 8,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'ભીષ્મ પિતામહના પ્રસ્થાનની વર્ષગાંઠ',
            'deity' => 'ભીષ્મ',
        ],
        'જયા એકાદશી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 11,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'જયા એકાદશી માટે વ્રત',
            'deity' => 'વિષ્ણુ',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'માઘી પૂર્ણિમા / માસી મગમ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'કુંભ મેળામાં સ્નાનનો દિવસ / તમિલ પવિત્ર સ્નાન દિવસ',
            'deity' => 'ગંગા/શિવ',
        ],
        'પુષ્પદોલોત્સવ (ધુળેટી)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 1,
            'month_amanta' => 'Phalguna',
            'month_purnimanta' => 'Phalguna',
            'description' => 'રંગોનો તહેવાર (ધુળેટી/પુષ્પદોલોત્સવ)',
            'deity' => 'કૃષ્ણ/સ્વામિનારાયણ',
            'karmakala_type' => 'sunrise',
        ],
        'વિજયા એકાદશી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 11,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Phalguna',
            'description' => 'વિજયા એકાદશી માટે વ્રત',
            'deity' => 'વિષ્ણુ',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'મહા શિવરાત્રિ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 14,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Phalguna',
            'description' => 'ભગવાન શિવની મહાન રાત્રિ',
            'deity' => 'શિવ',
            'fasting' => true,
            'karmakala_type' => 'nishitha',
            'strict_karmakala' => true,
            'vriddhi_preference' => 'last',
        ],
        'ફુલેરા દૂજ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 2,
            'month_amanta' => 'Phalguna',
            'month_purnimanta' => 'Phalguna',
            'description' => 'ફૂલોનો તહેવાર',
            'deity' => 'કૃષ્ણ',
        ],
        'આમલકી એકાદશી' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 11,
            'month_amanta' => 'Phalguna',
            'month_purnimanta' => 'Phalguna',
            'description' => 'આમલકી એકાદશી માટે વ્રત',
            'deity' => 'વિષ્ણુ',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'હોલિકા દહન' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Phalguna',
            'month_purnimanta' => 'Phalguna',
            'description' => 'તાપણાનો ઉત્સવ, બુરાઈ પર સારપની જીત',
            'deity' => 'વિષ્ણુ/હિરણ્યકશિપુ',
            'karmakala_type' => 'pradosha',
            'strict_karmakala' => true,
            'vriddhi_preference' => 'first',
        ],
        'ભગતજી મહારાજ જયંતિ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Phalguna',
            'month_purnimanta' => 'Phalguna',
            'description' => 'ભગતજી મહારાજનો જન્મ (સ્વામિનારાયણ સંપ્રદાય)',
            'deity' => 'સ્વામિનારાયણ',
        ],
        'હોળી' =>
        [
            'type' => 'day_after',
            'parent_festival' => 'હોલિકા દહન',
            'days_after' => 1,
            'description' => 'રંગોનો તહેવાર',
            'deity' => 'કૃષ્ણ',
        ],
        'વરલક્ષ્મી વ્રતમ' =>
        [
            'type' => 'weekday_tithi',
            'paksha' => 'Shukla',
            'tithi' =>
            [
                0 => 12,
                1 => 13,
                2 => 14,
                3 => 15,
            ],
            'weekday' => 5,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Shravana',
            'description' => 'સમૃદ્ધિ માટે દેવી લક્ષ્મીની પૂજા',
            'deity' => 'લક્ષ્મી',
            'fasting' => true,
        ],
        'પદ્મિની એકાદશી' => [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 11,
            'description' => 'વિશેષ એકાદશી જે માત્ર અધિક માસ દરમિયાન આવે છે',
            'deity' => 'વિષ્ણુ',
            'fasting' => true,
            'adhika_only' => true,
        ],
        'પરમા એકાદશી' => [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 11,
            'description' => 'વિશેષ એકાદશી જે માત્ર અધિક માસના કૃષ્ણ પક્ષમાં આવે છે',
            'deity' => 'વિષ્ણુ',
            'fasting' => true,
            'adhika_only' => true,
        ],
    ];