    public const FESTIVALS = [
        'मेष संक्रांति (बैसाखी / पुथंडु)' =>
        [
            'type' => 'solar_sankranti',
            'rashi' => 0,
            'description' => 'सौर नव वर्ष',
            'regions' =>
            [
                0 => 'संपूर्ण भारत',
            ],
        ],
        'वृषभ संक्रांति' =>
        [
            'type' => 'solar_sankranti',
            'rashi' => 1,
            'description' => 'सूर्य का वृषभ राशि में प्रवेश',
            'regions' =>
            [
                0 => 'संपूर्ण भारत',
            ],
        ],
        'मिथुन संक्रांति' =>
        [
            'type' => 'solar_sankranti',
            'rashi' => 2,
            'description' => 'सूर्य का मिथुन राशि में प्रवेश',
            'regions' =>
            [
                0 => 'संपूर्ण भारत',
            ],
        ],
        'कर्क संक्रांति' =>
        [
            'type' => 'solar_sankranti',
            'rashi' => 3,
            'description' => 'सूर्य का कर्क राशि में प्रवेश',
            'regions' =>
            [
                0 => 'संपूर्ण भारत',
            ],
        ],
        'सिंह संक्रांति' =>
        [
            'type' => 'solar_sankranti',
            'rashi' => 4,
            'description' => 'सूर्य का सिंह राशि में प्रवेश',
            'regions' =>
            [
                0 => 'संपूर्ण भारत',
            ],
        ],
        'कन्या संक्रांति (विश्वकर्मा पूजा)' =>
        [
            'type' => 'solar_sankranti',
            'rashi' => 5,
            'description' => 'दिव्य वास्तुकार विश्वकर्मा की पूजा',
            'regions' =>
            [
                0 => 'संपूर्ण भारत',
            ],
            'deity' => 'विश्वकर्मा',
        ],
        'तुला संक्रांति' =>
        [
            'type' => 'solar_sankranti',
            'rashi' => 6,
            'description' => 'सूर्य का तुला राशि में प्रवेश',
            'regions' =>
            [
                0 => 'संपूर्ण भारत',
            ],
        ],
        'वृश्चिक संक्रांति' =>
        [
            'type' => 'solar_sankranti',
            'rashi' => 7,
            'description' => 'सूर्य का वृश्चिक राशि में प्रवेश',
            'regions' =>
            [
                0 => 'संपूर्ण भारत',
            ],
        ],
        'धनु संक्रांति' =>
        [
            'type' => 'solar_sankranti',
            'rashi' => 8,
            'description' => 'सूर्य का धनु राशि में प्रवेश',
            'regions' =>
            [
                0 => 'संपूर्ण भारत',
            ],
        ],
        'मकर संक्रांति (पोंगल)' =>
        [
            'type' => 'solar_sankranti',
            'rashi' => 9,
            'description' => 'फसल उत्सव, सूर्य का मकर राशि में प्रवेश',
            'regions' =>
            [
                0 => 'संपूर्ण भारत',
            ],
            'deity' => 'सूर्य',
        ],
        'कुंभ संक्रांति' =>
        [
            'type' => 'solar_sankranti',
            'rashi' => 10,
            'description' => 'सूर्य का कुंभ राशि में प्रवेश',
            'regions' =>
            [
                0 => 'संपूर्ण भारत',
            ],
        ],
        'मीन संक्रांति' =>
        [
            'type' => 'solar_sankranti',
            'rashi' => 11,
            'description' => 'सूर्य का मीन राशि में प्रवेश',
            'regions' =>
            [
                0 => 'संपूर्ण भारत',
            ],
        ],
        'वासी उत्तरायण' =>
        [
            'type' => 'fixed_date',
            'month' => 1,
            'day' => 15,
            'description' => 'गुजरात में पतंग उत्सव का दूसरा दिन',
            'regions' => ['गुजरात'],
        ],
        'लोहड़ी' =>
        [
            'type' => 'fixed_date',
            'month' => 1,
            'day' => 13,
            'description' => 'पंजाबी फसल उत्सव; शीतकालीन संक्रांति के अंत का प्रतीक अलाव उत्सव',
            'deity' => 'अग्नि/सूर्य',
            'regions' => ['पंजाब', 'हरियाणा', 'दिल्ली', 'उत्तर भारत'],
        ],

        'चेटी चंड' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 2,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'सिंधी हिंदू नव वर्ष; झूलेलाल (इष्ट-देवता) का जन्म',
            'deity' => 'झूलेलाल/वरुण',
            'regions' => ['सिंधी', 'गुजरात', 'राजस्थान'],
        ],
        'विशु' =>
        [
            'type' => 'solar_sankranti',
            'rashi' => 0,
            'description' => 'केरल हिंदू नव वर्ष; मेड़म महीने का पहला दिन; विशुक्कानी सजावट',
            'deity' => 'कृष्ण/विष्णु',
            'regions' => ['केरल', 'तमिलनाडु', 'कर्नाटक'],
        ],

        'शास्त्रीजी महाराज जयंती' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 5,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'BAPS के संस्थापक शास्त्रीजी महाराज की जयंती; वसंत पंचमी के दिन',
            'deity' => 'स्वामीनारायण',
        ],

        'प्रमुख वर्णी दिन' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 4,
            'month_amanta' => 'Jyeshtha',
            'month_purnimanta' => 'Jyeshtha',
            'description' => 'वह दिन जब प्रमुख स्वामी महाराज को BAPS का प्रशासनिक अध्यक्ष नियुक्त किया गया था (1950)',
            'deity' => 'स्वामीनारायण',
        ],

        'अषाढ़ी बीज' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 2,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'कच्छी नव वर्ष; मानसून और खरीफ फसल के मौसम की शुरुआत; पारंपरिक मौसम भविष्यवाणी',
            'deity' => 'वरुण/इंद्र',
            'regions' => ['कच्छ', 'गुजरात'],
        ],

        'रवेची माता मेला' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 8,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'रवेची माता मंदिर (रापर, कच्छ) में प्राचीन मेला; रबारी और अहीर समुदाय के हजारों भक्त इकट्ठा होते हैं',
            'deity' => 'रवेची माता',
            'regions' => ['कच्छ', 'गुजरात'],
        ],

        'तरणेतर मेला' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 4,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'त्रिनेत्रेश्वर महादेव मंदिर में सौराष्ट्र का प्रसिद्ध मैचमेकिंग मेला; भादरवा सुद 4-6',
            'deity' => 'शिव',
            'regions' => ['सौराष्ट्र', 'गुजरात'],
        ],
        'तरणेतर मेला दिन 2' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 5,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'तरणेतर मेले का दूसरा दिन (भादरवा सुद 5)',
            'deity' => 'शिव',
            'regions' => ['सौराष्ट्र', 'गुजरात'],
        ],
        'तरणेतर मेला दिन 3' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 6,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'तरणेतर मेले का तीसरा दिन (भादरवा सुद 6)',
            'deity' => 'शिव',
            'regions' => ['सौराष्ट्र', 'गुजरात'],
        ],

        'मोटा यक्ष मेला (जख बहोतेरा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 12,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'ककड़भिट में कच्छ का सबसे बड़ा मेला; 72 यक्षों का सम्मान जिन्होंने स्थानीय लोगों की रक्षा की; भादरवा वद 12-14',
            'deity' => '72 यक्ष',
            'regions' => ['कच्छ', 'गुजरात'],
        ],

        'दादा मेकण मेला (ध्रांग मेला)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 14,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Phalguna',
            'description' => 'ध्रांग गाँव में संत मेकण दादा के सम्मान में मेला, जिन्होंने कच्छ के रण में भटके हुए यात्रियों को बचाया था',
            'deity' => 'मेकण दादा',
            'regions' => ['कच्छ', 'गुजरात'],
        ],

        'रंग पंचमी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 5,
            'month_amanta' => 'Phalguna',
            'month_purnimanta' => 'Phalguna',
            'description' => 'होली उत्सव का पांचवां दिन; रंगों के खेल की निरंतरता; विशेषकर महाराष्ट्र और मध्य प्रदेश में मनाया जाता है',
            'deity' => 'कृष्ण',
            'regions' => ['महाराष्ट्र', 'मध्य प्रदेश', 'उत्तर भारत'],
        ],

        'चैत्र (वसंत) नवरात्रि दिन 1 (शैलपुत्री पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 1,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'चैत्र (वसंत) नवरात्रि - शैलपुत्री (पर्वत की पुत्री) की पूजा',
            'deity' => 'दुर्गा/शैलपुत्री',
            'karmakala_type' => 'sunrise',
        ],
        'चैत्र (वसंत) नवरात्रि दिन 2 (ब्रह्मचारिणी पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 2,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'चैत्र (वसंत) नवरात्रि - ब्रह्मचारिणी (तपस्विनी) की पूजा',
            'deity' => 'दुर्गा/ब्रह्मचारिणी',
            'karmakala_type' => 'sunrise',
        ],
        'चैत्र (वसंत) नवरात्रि दिन 3 (चंद्रघंटा पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 3,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'चैत्र (वसंत) नवरात्रि - चंद्रघंटा (चंद्रमा रूपी घंटा धारण करने वाली) की पूजा',
            'deity' => 'दुर्गा/चंद्रघंटा',
            'karmakala_type' => 'sunrise',
        ],
        'चैत्र (वसंत) नवरात्रि दिन 4 (कूष्मांडा पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 4,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'चैत्र (वसंत) नवरात्रि - कूष्मांडा (ब्रह्मांडीय अंडे की रचयिता) की पूजा',
            'deity' => 'दुर्गा/कूष्मांडा',
            'karmakala_type' => 'sunrise',
        ],
        'चैत्र (वसंत) नवरात्रि दिन 5 (स्कंदमाता पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 5,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'चैत्र (वसंत) नवरात्रि - स्कंदमाता (स्कंद की माता) की पूजा',
            'deity' => 'दुर्गा/स्कंदमाता',
            'karmakala_type' => 'sunrise',
        ],
        'चैत्र (वसंत) नवरात्रि दिन 6 (कात्यायनी पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 6,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'चैत्र (वसंत) नवरात्रि - कात्यायनी (योद्धा देवी) की पूजा',
            'deity' => 'दुर्गा/कात्यायनी',
            'karmakala_type' => 'sunrise',
        ],
        'चैत्र (वसंत) नवरात्रि दिन 7 (कालरात्रि पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 7,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'चैत्र (वसंत) नवरात्रि - कालरात्रि (भयंकर रात) की पूजा / महा सप्तमी',
            'deity' => 'दुर्गा/कालरात्रि',
            'karmakala_type' => 'sunrise',
        ],
        'चैत्र (वसंत) नवरात्रि दिन 8 (महागौरी पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 8,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'चैत्र (वसंत) नवरात्रि - महागौरी (महान श्वेत देवी) की पूजा / महा अष्टमी',
            'deity' => 'दुर्गा/महागौरी',
            'karmakala_type' => 'sunrise',
        ],
        'चैत्र (वसंत) नवरात्रि दिन 9 (सिद्धिदात्री पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 9,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'चैत्र (वसंत) नवरात्रि - सिद्धिदात्री (अलौकिक शक्तियों की दाता) की पूजा / महा नवमी',
            'deity' => 'दुर्गा/सिद्धिदात्री',
            'karmakala_type' => 'sunrise',
        ],
        'अश्विन शरद नवरात्रि दिन 1 (शैलपुत्री पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 1,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Ashvina',
            'description' => 'अश्विन शरद नवरात्रि - शैलपुत्री (पर्वत की पुत्री) की पूजा',
            'deity' => 'दुर्गा/शैलपुत्री',
            'karmakala_type' => 'sunrise',
        ],
        'अश्विन शरद नवरात्रि दिन 2 (ब्रह्मचारिणी पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 2,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Ashvina',
            'description' => 'अश्विन शरद नवरात्रि - ब्रह्मचारिणी (तपस्विनी) की पूजा',
            'deity' => 'दुर्गा/ब्रह्मचारिणी',
            'karmakala_type' => 'sunrise',
        ],
        'अश्विन शरद नवरात्रि दिन 3 (चंद्रघंटा पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 3,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Ashvina',
            'description' => 'अश्विन शरद नवरात्रि - चंद्रघंटा (चंद्रमा रूपी घंटा धारण करने वाली) की पूजा',
            'deity' => 'दुर्गा/चंद्रघंटा',
            'karmakala_type' => 'sunrise',
        ],
        'अश्विन शरद नवरात्रि दिन 4 (कूष्मांडा पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 4,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Ashvina',
            'description' => 'अश्विन शरद नवरात्रि - कूष्मांडा (ब्रह्मांडीय अंडे की रचयिता) की पूजा',
            'deity' => 'दुर्गा/कूष्मांडा',
            'karmakala_type' => 'sunrise',
        ],
        'अश्विन शरद नवरात्रि दिन 5 (स्कंदमाता पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 5,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Ashvina',
            'description' => 'अश्विन शरद नवरात्रि - स्कंदमाता (स्कंद की माता) की पूजा',
            'deity' => 'दुर्गा/स्कंदमाता',
            'karmakala_type' => 'sunrise',
        ],
        'अश्विन शरद नवरात्रि दिन 6 (कात्यायनी पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 6,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Ashvina',
            'description' => 'अश्विन शरद नवरात्रि - कात्यायनी (योद्धा देवी) की पूजा',
            'deity' => 'दुर्गा/कात्यायनी',
            'karmakala_type' => 'sunrise',
        ],
        'अश्विन शरद नवरात्रि दिन 7 (कालरात्रि पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 7,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Ashvina',
            'description' => 'अश्विन शरद नवरात्रि - कालरात्रि (भयंकर रात) की पूजा / महा सप्तमी',
            'deity' => 'दुर्गा/कालरात्रि',
            'karmakala_type' => 'sunrise',
        ],
        'दुर्गा अष्टमी (महागौरी पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 8,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Ashvina',
            'description' => 'अश्विन शरद नवरात्रि - महागौरी (महान श्वेत देवी) की पूजा / महा अष्टमी',
            'deity' => 'दुर्गा/महागौरी',
            'karmakala_type' => 'sunrise',
        ],
        'महा नवमी (सिद्धिदात्री पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 9,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Ashvina',
            'description' => 'अश्विन शरद नवरात्रि - सिद्धिदात्री (अलौकिक शक्तियों की दाता) की पूजा / महा नवमी',
            'deity' => 'दुर्गा/सिद्धिदात्री',
            'karmakala_type' => 'sunrise',
        ],
        'आषाढ़ गुप्त नवरात्रि दिन 1 (काली पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 1,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - काली (समय की संहारक) की पूजा',
            'deity' => 'महाविद्या/काली',
            'karmakala_type' => 'sunrise',
        ],
        'आषाढ़ गुप्त नवरात्रि दिन 2 (तारा पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 2,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - तारा (रक्षक और मार्गदर्शक) की पूजा',
            'deity' => 'महाविद्या/तारा',
            'karmakala_type' => 'sunrise',
        ],
        'आषाढ़ गुप्त नवरात्रि दिन 3 (त्रिपुर सुंदरी पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 3,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - त्रिपुर सुंदरी / षोडशी (तीनों लोकों की सुंदरी) की पूजा',
            'deity' => 'महाविद्या/त्रिपुर सुंदरी',
            'karmakala_type' => 'sunrise',
        ],
        'आषाढ़ गुप्त नवरात्रि दिन 4 (भुवनेश्वरी पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 4,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - भुवनेश्वरी (ब्रह्मांड की देवी) की पूजा',
            'deity' => 'महाविद्या/भुवनेश्वरी',
            'karmakala_type' => 'sunrise',
        ],
        'आषाढ़ गुप्त नवरात्रि दिन 5 (भैरवी पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 5,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - भैरवी (विनाश और पुनर्जन्म की भयंकर देवी) की पूजा',
            'deity' => 'महाविद्या/भैरवी',
            'karmakala_type' => 'sunrise',
        ],
        'आषाढ़ गुप्त नवरात्रि दिन 6 (छिन्नमस्ता पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 6,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - छिन्नमस्ता (स्वयं का सिर काटने वाली देवी) की पूजा',
            'deity' => 'महाविद्या/छिन्नमस्ता',
            'karmakala_type' => 'sunrise',
        ],
        'आषाढ़ गुप्त नवरात्रि दिन 7 (धूमावती पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 7,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - धूमावती (विधवा देवी) की पूजा',
            'deity' => 'महाविद्या/धूमावती',
            'karmakala_type' => 'sunrise',
        ],
        'आषाढ़ गुप्त नवरात्रि दिन 8 (बगलामुखी पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 8,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - बगलामुखी (शत्रुओं को पंगु करने वाली) की पूजा',
            'deity' => 'महाविद्या/बगलामुखी',
            'karmakala_type' => 'sunrise',
        ],
        'आषाढ़ गुप्त नवरात्रि दिन 9 (मातंगी पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 9,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - मातंगी (तांत्रिक सरस्वती / कला और संगीत) की पूजा',
            'deity' => 'महाविद्या/मातंगी',
            'karmakala_type' => 'sunrise',
        ],
        'आषाढ़ गुप्त नवरात्रि दिन 10 (कमला पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 10,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - कमला (तांत्रिक लक्ष्मी / समृद्धि और उर्वरता) की पूजा',
            'deity' => 'कमला',
            'karmakala_type' => 'sunrise',
        ],
        'माघ गुप्त नवरात्रि दिन 1 (काली पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 1,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - काली (समय की संहारक) की पूजा',
            'deity' => 'महाविद्या/काली',
            'karmakala_type' => 'sunrise',
        ],
        'माघ गुप्त नवरात्रि दिन 2 (तारा पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 2,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - तारा (रक्षक और मार्गदर्शक) की पूजा',
            'deity' => 'महाविद्या/तारा',
            'karmakala_type' => 'sunrise',
        ],
        'माघ गुप्त नवरात्रि दिन 3 (त्रिपुर सुंदरी पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 3,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - त्रिपुर सुंदरी / षोडशी (तीनों लोकों की सुंदरी) की पूजा',
            'deity' => 'महाविद्या/त्रिपुर सुंदरी',
            'karmakala_type' => 'sunrise',
        ],
        'माघ गुप्त नवरात्रि दिन 4 (भुवनेश्वरी पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 4,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - भुवनेश्वरी (ब्रह्मांड की देवी) की पूजा',
            'deity' => 'महाविद्या/भुवनेश्वरी',
            'karmakala_type' => 'sunrise',
        ],
        'माघ गुप्त नवरात्रि दिन 5 (भैरवी पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 5,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - भैरवी (विनाश और पुनर्जन्म की भयंकर देवी) की पूजा',
            'deity' => 'महाविद्या/भैरवी',
            'karmakala_type' => 'sunrise',
        ],
        'माघ गुप्त नवरात्रि दिन 6 (छिन्नमस्ता पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 6,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - छिन्नमस्ता (स्वयं का सिर काटने वाली देवी) की पूजा',
            'deity' => 'महाविद्या/छिन्नमस्ता',
            'karmakala_type' => 'sunrise',
        ],
        'माघ गुप्त नवरात्रि दिन 7 (धूमावती पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 7,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - धूमावती (विधवा देवी) की पूजा',
            'deity' => 'महाविद्या/धूमावती',
            'karmakala_type' => 'sunrise',
        ],
        'माघ गुप्त नवरात्रि दिन 8 (बगलामुखी पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 8,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - बगलामुखी (शत्रुओं को पंगु करने वाली) की पूजा',
            'deity' => 'महाविद्या/बगलामुखी',
            'karmakala_type' => 'sunrise',
        ],
        'माघ गुप्त नवरात्रि दिन 9 (मातंगी पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 9,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - मातंगी (तांत्रिक सरस्वती / कला और संगीत) की पूजा',
            'deity' => 'महाविद्या/मातंगी',
            'karmakala_type' => 'sunrise',
        ],
        'माघ गुप्त नवरात्रि दिन 10 (कमला पूजा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 10,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - कमला (तांत्रिक लक्ष्मी / समृद्धि और उर्वरता) की पूजा',
            'deity' => 'कमला',
            'karmakala_type' => 'sunrise',
        ],
        'शीतला अष्टमी (बसोड़ा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 8,
            'month_amanta' => 'Phalguna',
            'month_purnimanta' => 'Chaitra',
            'description' => 'बीमारियों से बचाव के लिए देवी शीतला की पूजा',
            'deity' => 'शीतला माता',
        ],
        'पापमोचनी एकादशी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 11,
            'month_amanta' => 'Phalguna',
            'month_purnimanta' => 'Chaitra',
            'description' => 'पापमोचनी एकादशी के लिए व्रत (पापों से मुक्ति)',
            'deity' => 'विष्णु',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'उगादी / गुड़ी पड़वा' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 1,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'चंद्र नव वर्ष / चैत्र का पहला दिन',
            'deity' => 'ब्रह्मा',
            'karmakala_type' => 'sunrise',
        ],
        'गणगौर' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 3,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'गौरी की पूजा',
            'deity' => 'पार्वती',
        ],
        'यमुना छठ / चैती छठ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 6,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'देवी यमुना का अवतरण / ग्रीष्मकालीन छठ',
            'deity' => 'सूर्य/यमुना',
        ],
        'राम नवमी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 9,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'भगवान राम (विष्णु के सातवें अवतार) की जयंती',
            'deity' => 'राम',
            'fasting' => true,
            'karmakala_type' => 'madhyahna',
            'strict_karmakala' => true,
        ],
        'स्वामीनारायण जयंती (हरि-नोम)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 9,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'भगवान स्वामीनारायण का जन्म; सभाओं, सांस्कृतिक कार्यक्रमों और भजन गायन के साथ मनाया जाता है',
            'deity' => 'स्वामीनारायण',
            'fasting' => true,
            'karmakala_type' => 'madhyahna',
            'strict_karmakala' => true,
        ],
        'कामदा एकादशी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 11,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'कामदा एकादशी के लिए व्रत (इच्छाओं की पूर्ति करने वाली)',
            'deity' => 'विष्णु',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'हनुमान जयंती' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Chaitra',
            'description' => 'भगवान हनुमान का जन्मोत्सव',
            'deity' => 'हनुमान',
            'karmakala_type' => 'sunrise',
        ],
        'वरुथिनी एकादशी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 11,
            'month_amanta' => 'Chaitra',
            'month_purnimanta' => 'Vaishakha',
            'description' => 'वरुथिनी एकादशी के लिए व्रत',
            'deity' => 'विष्णु',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'परशुराम जयंती' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 3,
            'month_amanta' => 'Vaishakha',
            'month_purnimanta' => 'Vaishakha',
            'description' => 'भगवान परशुराम का जन्म',
            'deity' => 'परशुराम',
        ],
        'अक्षय तृतीया' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 3,
            'month_amanta' => 'Vaishakha',
            'month_purnimanta' => 'Vaishakha',
            'description' => 'नई शुरुआत के लिए सबसे शुभ दिन',
            'deity' => 'विष्णु/लक्ष्मी',
            'karmakala_type' => 'sunrise',
        ],
        'आदि शंकराचार्य जयंती' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 5,
            'month_amanta' => 'Vaishakha',
            'month_purnimanta' => 'Vaishakha',
            'description' => 'आदि शंकराचार्य की जयंती',
            'deity' => 'शिव/शंकराचार्य',
        ],
        'गंगा सप्तमी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 7,
            'month_amanta' => 'Vaishakha',
            'month_purnimanta' => 'Vaishakha',
            'description' => 'गंगा नदी का पुनर्जन्म',
            'deity' => 'गंगा',
        ],
        'सीता नवमी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 9,
            'month_amanta' => 'Vaishakha',
            'month_purnimanta' => 'Vaishakha',
            'description' => 'देवी सीता की जयंती',
            'deity' => 'सीता',
        ],
        'मोहिनी एकादशी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 11,
            'month_amanta' => 'Vaishakha',
            'month_purnimanta' => 'Vaishakha',
            'description' => 'मोहिनी एकादशी के लिए व्रत',
            'deity' => 'विष्णु',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'नरसिंह जयंती' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 14,
            'month_amanta' => 'Vaishakha',
            'month_purnimanta' => 'Vaishakha',
            'description' => 'भगवान नरसिंह का प्राकट्य दिवस',
            'deity' => 'नरसिंह',
            'fasting' => true,
            'karmakala_type' => 'pradosha',
            'strict_karmakala' => true,
        ],
        'बुद्ध पूर्णिमा' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Vaishakha',
            'month_purnimanta' => 'Vaishakha',
            'description' => 'वैशाख पूर्णिमा — सुगत बुद्ध (विष्णु के 9वें अवतार, बौद्ध धर्म के गौतम बुद्ध से अलग) और कूर्म जयंती (भगवान विष्णु के कछुए अवतार का जन्म) का हिंदू पर्व। भागवत पुराण 1.3.24 और अग्नि पुराण में हिंदू बुद्ध-अवतार का वर्णन कीकट/गया में राक्षसों को वैदिक अनुष्ठानों से भ्रमित करने (भागवत दृष्टिकोण) या करुणा सिखाने और पशु बलि को समाप्त करने (जयदेव का गीत गोविंद दृष्टिकोण) के लिए प्रकट होने के रूप में किया गया है। पुरी के शंकराचार्य स्वामी निश्चलानंद सरस्वती और विद्वान इन्हें दो अलग-अलग व्यक्तियों के रूप में मान्यता देते हैं: पौराणिक सुगत बुद्ध (ब्राह्मण वर्ण, वेदों का समर्थन, प्राचीन समयरेखा) बनाम गौतम बुद्ध (क्षत्रिय शाक्य वंश, लुंबिनी जन्म ~563 ईसा पूर्व, वेदों को अस्वीकार किया)। यह दिन कूर्म जयंती के साथ भी मेल खाता है और सत्यनारायण पूजा के लिए सबसे शुभ दिन है। क्षेत्रीय भिन्नता: ओडिशा और बंगाल की परंपराओं में दशावतार में 9वें अवतार के रूप में बुद्ध की जगह बलराम को रखा गया है।',
            'deity' => 'सुगत बुद्ध/कूर्म/विष्णु',
            'karmakala_type' => 'sunrise',
        ],
        'नरसिंह मेहता जन्म जयंती' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Vaishakha',
            'month_purnimanta' => 'Vaishakha',
            'description' => 'आदि कवि नरसिंह मेहता की जयंती',
            'deity' => 'कृष्ण/नरसिंह मेहता',
        ],
        'अपरा एकादशी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 11,
            'month_amanta' => 'Vaishakha',
            'month_purnimanta' => 'Jyeshtha',
            'description' => 'अपरा एकादशी के लिए व्रत',
            'deity' => 'विष्णु',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'योगी महाराज जयंती' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 12,
            'month_amanta' => 'Vaishakha',
            'month_purnimanta' => 'Jyeshtha',
            'description' => 'ब्रह्मस्वरूप योगी महाराज का जन्म',
            'deity' => 'स्वामीनारायण',
        ],
        'शनि जयंती / सावित्री अमावस्या' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 15,
            'month_amanta' => 'Vaishakha',
            'month_purnimanta' => 'Jyeshtha',
            'description' => 'भगवान शनि का जन्म / सावित्री व्रत',
            'deity' => 'शनि/सावित्री',
        ],
        'जामाइ षष्ठी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 6,
            'month_amanta' => 'Jyeshtha',
            'month_purnimanta' => 'Jyeshtha',
            'description' => 'दामाद को समर्पित बंगाली त्योहार',
            'deity' => 'षष्ठी',
        ],
        'महेश नवमी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 9,
            'month_amanta' => 'Jyeshtha',
            'month_purnimanta' => 'Jyeshtha',
            'description' => 'माहेश्वरी समाज द्वारा भगवान शिव की पूजा',
            'deity' => 'शिव',
        ],
        'गंगा दशहरा' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 10,
            'month_amanta' => 'Jyeshtha',
            'month_purnimanta' => 'Jyeshtha',
            'description' => 'पृथ्वी पर माता गंगा का अवतरण',
            'deity' => 'गंगा',
            'karmakala_type' => 'sunrise',
        ],
        'निर्जला एकादशी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 11,
            'month_amanta' => 'Jyeshtha',
            'month_purnimanta' => 'Jyeshtha',
            'description' => 'सबसे कठिन एकादशी व्रत (बिना जल के किया जाने वाला) / गायत्री जयंती',
            'deity' => 'विष्णु/गायत्री',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'वट पूर्णिमा' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Jyeshtha',
            'month_purnimanta' => 'Jyeshtha',
            'description' => 'पूर्णिमान्त कैलेंडर के अनुसार वट सावित्री व्रत',
            'deity' => 'सावित्री/ब्रह्मा',
            'fasting' => true,
        ],
        'योगिनी एकादशी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 11,
            'month_amanta' => 'Jyeshtha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'योगिनी एकादशी के लिए व्रत',
            'deity' => 'विष्णु',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'जगन्नाथ रथ यात्रा' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 2,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'भगवान जगन्नाथ का रथ उत्सव',
            'deity' => 'जगन्नाथ',
            'karmakala_type' => 'sunrise',
        ],
        'देवशयनी एकादशी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 11,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'चातुर्मास आरंभ, भगवान विष्णु योगनिद्रा में जाते हैं',
            'deity' => 'विष्णु',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'गौरी व्रत (मोलाकत) प्रारंभ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 11,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'छोटी कन्याओं द्वारा 5 दिवसीय व्रत (बिना नमक का)',
            'deity' => 'गौरी/पार्वती',
        ],
        'जया पार्वती व्रत प्रारंभ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 13,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'वैवाहिक सुख और अच्छे पति के लिए 5 दिवसीय व्रत',
            'deity' => 'जया/पार्वती',
        ],
        'गुरु पूर्णिमा' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Ashadha',
            'description' => 'आध्यात्मिक गुरुओं और महर्षि व्यास का सम्मान',
            'deity' => 'व्यास',
            'karmakala_type' => 'sunrise',
        ],
        'कामिका एकादशी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 11,
            'month_amanta' => 'Ashadha',
            'month_purnimanta' => 'Shravana',
            'description' => 'कामिका एकादशी के लिए व्रत',
            'deity' => 'विष्णु',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'हरियाली तीज' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 3,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Shravana',
            'description' => 'बारिश का स्वागत करने वाला मानसून त्योहार',
            'deity' => 'पार्वती/शिव',
        ],
        'नाग पंचमी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 5,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Shravana',
            'description' => 'सर्प देवताओं की पूजा',
            'deity' => 'नाग',
        ],
        'कल्कि जयंती' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 6,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Shravana',
            'description' => 'कल्कि अवतार का जन्म',
            'deity' => 'कल्कि',
        ],
        'तुलसीदास जयंती' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 7,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Shravana',
            'description' => 'गोस्वामी तुलसीदास की जयंती',
            'deity' => 'राम/तुलसीदास',
        ],
        'श्रावण पुत्रदा एकादशी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 11,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Shravana',
            'description' => 'पुत्र प्राप्ति के लिए व्रत',
            'deity' => 'विष्णु',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'रक्षा बंधन / अवनी अवित्तम' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Shravana',
            'description' => 'भाई-बहन का बंधन / हयग्रीव जन्म / उपाकर्म',
            'deity' => 'हयग्रीव',
            'karmakala_type' => 'aparahna',
            'strict_karmakala' => true,
        ],
        'पोला / कुशोत्पाटिनी अमावस्या' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 15,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'किसानों और बैलों के लिए धन्यवाद उत्सव',
            'deity' => 'शिव',
        ],
        'अजा एकादशी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 11,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'अजा एकादशी के लिए व्रत',
            'deity' => 'विष्णु',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'गोगा पंचम / गोगा पंचमी (नाग पंचमी - गुजरात)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 5,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'गोगा जी / गोगा महाराज और सर्प देवताओं का सम्मान करने वाली गुजराती नाग पंचमी',
            'deity' => 'गोगा जी / गोगा बापा',
            'regions' => ['गुजरात'],
        ],
        'श्रावण सोमवार (सोमवार व्रत)' =>
        [
            'type' => 'weekday_in_month',
            'weekday' => 1,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Shravana',
            'description' => 'भगवान शिव को समर्पित श्रावण मास का शुभ सोमवार',
            'deity' => 'शिव',
            'fasting' => true,
        ],
        'कजरी तीज' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 3,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'कजरी तीज उत्सव',
            'deity' => 'पार्वती/शिव',
        ],
        'बोल चौथ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 4,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'गायों और बछड़ों की पूजा (बहुला चतुर्थी)',
            'deity' => 'कृष्ण/गाएं',
        ],
        'रांधण छठ / बलराम जयंती (हल षष्ठी)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 6,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'गुजराती रांधण छठ और कृष्ण षष्ठी पर व्यापक हल षष्ठी / बलराम जयंती का पर्व',
            'deity' => 'बलराम',
        ],
        'शीतला सातम / शीतला सप्तमी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 7,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'शीतला माता का पर्व, जिसे गुजरात में शीतला सातम के रूप में जाना जाता है, स्वास्थ्य के लिए प्रार्थना और ठंडे भोजन के प्रसाद द्वारा मनाया जाता है',
            'deity' => 'शीतला माता',
            'fasting' => true,
        ],
        'कृष्ण जन्माष्टमी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 8,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'भगवान कृष्ण का जन्मोत्सव',
            'deity' => 'कृष्ण',
            'fasting' => true,
            'karmakala_type' => 'nishitha',
            'strict_karmakala' => true,
            'vriddhi_preference' => 'last',
        ],
        'हरतालिका तीज / केवड़ा त्रीज' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 3,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'हरतालिका तीज, जिसे गुजरात में केवड़ा त्रीज के नाम से जाना जाता है, महिलाओं द्वारा पार्वती और शिव के सम्मान में मनाया जाता है',
            'deity' => 'पार्वती/शिव',
        ],
        'वराह जयंती' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 3,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'भगवान वराह का प्राकट्य दिवस',
            'deity' => 'विष्णु/वराह',
        ],
        'गणेश चतुर्थी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 4,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'भगवान गणेश की जयंती',
            'deity' => 'गणेश',
            'karmakala_type' => 'madhyahna',
            'strict_karmakala' => true,
        ],
        'ऋषि पंचमी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 5,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'सप्तर्षियों की पूजा',
            'deity' => 'सप्तर्षि',
            'karmakala_type' => 'madhyahna',
        ],
        'राधा अष्टमी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 8,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'राधारानी की जयंती',
            'deity' => 'राधा',
            'karmakala_type' => 'madhyahna',
        ],
        'पार्श्व एकादशी / जल झिलानी एकादशी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 11,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'भगवान विष्णु करवट बदलते हैं / स्वामीनारायण जल झिलानी उत्सव',
            'deity' => 'विष्णु/स्वामीनारायण',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'महंत स्वामी महाराज जन्म जयंती' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 9,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'महंत स्वामी महाराज का भौतिक जन्म दिवस (13 सितंबर 1933, भादरवा वद 9)',
            'deity' => 'स्वामीनारायण',
        ],
        'महंत स्वामी महाराज पार्षदी दीक्षा दिन (आधिकारिक जयंती)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 1,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'पार्षदी दीक्षा दिन (2 फरवरी 1957, महा वद 1) पर महंत स्वामी महाराज जयंती का आधिकारिक BAPS उत्सव',
            'deity' => 'स्वामीनारायण',
        ],
        'वामन जयंती' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 12,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'वामन अवतार का जन्म',
            'deity' => 'वामन',
        ],
        'अनंत चतुर्दशी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 14,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'भगवान अनंत की पूजा; गणेश विसर्जन',
            'deity' => 'विष्णु/गणेश',
            'karmakala_type' => 'sunrise',
        ],
        'पितृ पक्ष प्रारंभ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Bhadrapada',
            'description' => 'पूर्वजों के पखवाड़े की शुरुआत',
            'deity' => 'पितृ',
        ],
        'इन्दिरा एकादशी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 11,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Ashvina',
            'description' => 'इन्दिरा एकादशी के लिए व्रत',
            'deity' => 'विष्णु',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'महालय अमावस्या' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 15,
            'month_amanta' => 'Bhadrapada',
            'month_purnimanta' => 'Ashvina',
            'description' => 'पितृ पक्ष का अंतिम दिन (सर्वपित्री अमावस्या)',
            'deity' => 'पितृ',
            'karmakala_type' => 'aparahna',
        ],
        'ललिता पंचमी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 5,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Ashvina',
            'description' => 'नवरात्रि के दौरान देवी ललिता त्रिपुरसुंदरी की पूजा',
            'deity' => 'ललिता',
        ],
        'दशहरा / विजयदशमी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 10,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Ashvina',
            'description' => 'रावण पर भगवान राम की जीत / शरद नवरात्रि का समापन',
            'deity' => 'राम/दुर्गा',
            'karmakala_type' => 'aparahna',
            'strict_karmakala' => true,
        ],
        'पापांकुशा एकादशी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 11,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Ashvina',
            'description' => 'पापांकुशा एकादशी के लिए व्रत',
            'deity' => 'विष्णु',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'शरद पूर्णिमा / माणेकठारी पूनम / गुणातीतानंद स्वामी जयंती' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Ashvina',
            'description' => 'शरद पूर्णिमा, जिसे गुजरात में माणेकठारी पूनम के रूप में जाना जाता है, और गुणातीतानंद स्वामी की जयंती',
            'deity' => 'लक्ष्मी/कृष्ण/स्वामीनारायण',
            'karmakala_type' => 'nishitha',
        ],
        'वाल्मीकि जयंती' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Ashvina',
            'description' => 'महर्षि वाल्मीकि की जयंती',
            'deity' => 'वाल्मीकि',
        ],
        'रमा एकादशी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 11,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Kartika',
            'description' => 'रमा एकादशी के लिए व्रत',
            'deity' => 'विष्णु',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'करवा चौथ' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 4,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Kartika',
            'description' => 'विवाहित महिलाएं पति की लंबी उम्र के लिए व्रत रखती हैं',
            'deity' => 'पार्वती/शिव',
            'fasting' => true,
        ],
        'अहोई अष्टमी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 8,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Kartika',
            'description' => 'माताएं बच्चों की भलाई के लिए व्रत रखती हैं',
            'deity' => 'अहोई माता',
            'fasting' => true,
            'karmakala_type' => 'pradosha',
        ],
        'वाघ बारस (गोवत्स द्वादशी)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 12,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Kartika',
            'description' => 'गायों और बछड़ों की पूजा',
            'deity' => 'कृष्ण/गाएं',
            'karmakala_type' => 'pradosha',
        ],
        'धनतेरस' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 13,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Kartika',
            'description' => 'लक्ष्मी और धन्वंतरि की पूजा',
            'deity' => 'लक्ष्मी/धन्वंतरि',
            'karmakala_type' => 'pradosha',
            'strict_karmakala' => true,
        ],
        'काली चौदस (नरक चतुर्दशी)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 14,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Kartika',
            'description' => 'देवी काली की पूजा और नरकासुर पर विजय',
            'deity' => 'काली/हनुमान/कृष्ण',
            'karmakala_type' => 'nishitha',
            'strict_karmakala' => true,
        ],
        'काली पूजा / दिवाली' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 15,
            'month_amanta' => 'Ashvina',
            'month_purnimanta' => 'Kartika',
            'description' => 'रोशनी का त्योहार / देवी काली की पूजा',
            'deity' => 'लक्ष्मी/काली/गणेश',
            'karmakala_type' => 'pradosha',
            'strict_karmakala' => true,
            'vriddhi_preference' => 'first',
        ],
        'गोवर्धन पूजा / बेस्तु वरस / अन्नकूट' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 1,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Kartika',
            'description' => 'अन्नकूट (स्वामीनारायण) / गुजराती नव वर्ष',
            'deity' => 'कृष्ण',
            'karmakala_type' => 'sunrise',
        ],
        'भाई दूज' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 2,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Kartika',
            'description' => 'भाई-बहन के रिश्ते का उत्सव',
            'deity' => 'यम/यमुना',
            'karmakala_type' => 'aparahna',
        ],
        'लाभ पंचम' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 5,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Kartika',
            'description' => 'गुजरात में व्यवसायों के लिए शुभ दिन',
            'deity' => 'लक्ष्मी/गणेश',
        ],
        'स्कंद षष्ठी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 6,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Kartika',
            'description' => 'भगवान मुरुगन को समर्पित छह दिवसीय उत्सव, राक्षस सूरपद्मन पर उनकी जीत का जश्न',
            'deity' => 'मुरुगन/स्कंद',
            'fasting' => true,
            'regions' => ['तमिलनाडु', 'केरल', 'कर्नाटक', 'आंध्र प्रदेश', 'तेलंगाना'],
        ],
        'छठ पूजा (संध्या अर्घ्य)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 6,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Kartika',
            'description' => 'छठ पूजा का प्रमुख दिन (4 में से तीसरा) - सूर्य को संध्या अर्घ्य; पर्व कार्तिक शुक्ल 4-7 तक चलता है',
            'deity' => 'सूर्य/छठी मईया',
            'fasting' => true,
            'regions' => ['बिहार', 'झारखंड', 'पूर्वी यूपी', 'नेपाल'],
            'karmakala_type' => 'aparahna',
        ],
        'जलाराम जयंती' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 7,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Kartika',
            'description' => 'वीरपुर के संत जलाराम बापा की जयंती',
            'deity' => 'राम/जलाराम बापा',
        ],
        'गोपाष्टमी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 8,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Kartika',
            'description' => 'गायों की पूजा और उत्सव',
            'deity' => 'कामधेनु/कृष्ण',
        ],
        'जगद्धात्री पूजा' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 9,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Kartika',
            'description' => 'बंगाल में देवी जगद्धात्री की पूजा',
            'deity' => 'जगद्धात्री',
        ],
        'प्रमुख स्वामी महाराज जयंती' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 8,
            'month_amanta' => 'Margashirsha',
            'month_purnimanta' => 'Margashirsha',
            'description' => 'प्रमुख स्वामी महाराज की जयंती (7 दिसंबर 1921, मगशर सुद 8, विक्रम संवत 1978)',
            'deity' => 'स्वामीनारायण',
        ],
        'देवोत्थान (प्रबोधिनी) एकादशी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 11,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Kartika',
            'description' => 'प्रबोधिनी एकादशी / चातुर्मास का समापन',
            'deity' => 'विष्णु/स्वामीनारायण',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'तुलसी विवाह' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 12,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Kartika',
            'description' => 'तुलसी और शालिग्राम (विष्णु) का औपचारिक विवाह',
            'deity' => 'तुलसी/विष्णु',
        ],
        'वैकुंठ चतुर्दशी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 14,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Kartika',
            'description' => 'विष्णु और शिव दोनों के भक्तों के लिए पवित्र दिन',
            'deity' => 'विष्णु/शिव',
            'karmakala_type' => 'nishitha',
        ],
        'देव दिवाली (त्रिपुरारी पूर्णिमा)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Kartika',
            'description' => 'त्रिपुरासुर पर शिव की जीत का जश्न मनाने वाला वाराणसी का त्योहार; घाटों को दीयों से रोशन किया जाता है',
            'deity' => 'शिव',
            'regions' => ['वाराणसी', 'उत्तर प्रदेश'],
            'karmakala_type' => 'pradosha',
        ],
        'कार्तिगई दीपम' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Kartika',
            'description' => 'रोशनी का तमिल त्योहार; तिरुवन्नामलाई में महा दीपम जलाया जाता है',
            'deity' => 'शिव/कार्तिकेय',
            'regions' => ['तमिलनाडु', 'केरल', 'कर्नाटक', 'आंध्र प्रदेश', 'तेलंगाना'],
            'karmakala_type' => 'pradosha',
        ],
        'उत्पन्ना एकादशी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 11,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Margashirsha',
            'description' => 'उत्पन्ना एकादशी के लिए व्रत',
            'deity' => 'विष्णु',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'वचनामृत जयंती' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 4,
            'month_amanta' => 'Margashirsha',
            'month_purnimanta' => 'Margashirsha',
            'description' => 'वचनामृत का स्मरणोत्सव',
            'deity' => 'स्वामीनारायण',
        ],
        'कालभैरव जयंती' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 8,
            'month_amanta' => 'Kartika',
            'month_purnimanta' => 'Margashirsha',
            'description' => 'भगवान कालभैरव (शिव) का जन्म',
            'deity' => 'कालभैरव',
        ],
        'विवाह पंचमी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 5,
            'month_amanta' => 'Margashirsha',
            'month_purnimanta' => 'Margashirsha',
            'description' => 'राम और सीता की विवाह वर्षगांठ',
            'deity' => 'राम/सीता',
        ],
        'गीता जयंती / मोक्षदा एकादशी / वैकुंठ एकादशी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 11,
            'month_amanta' => 'Margashirsha',
            'month_purnimanta' => 'Margashirsha',
            'description' => 'भगवद गीता का उत्सव / मोक्ष का द्वार',
            'deity' => 'कृष्ण/विष्णु',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'दत्तात्रेय जयंती' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Margashirsha',
            'month_purnimanta' => 'Margashirsha',
            'description' => 'भगवान दत्तात्रेय का जन्म (अन्नपूर्णा जयंती)',
            'deity' => 'दत्तात्रेय/अन्नपूर्णा',
            'karmakala_type' => 'pradosha',
        ],
        'सफला एकादशी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 11,
            'month_amanta' => 'Margashirsha',
            'month_purnimanta' => 'Pausha',
            'description' => 'सफला एकादशी के लिए व्रत',
            'deity' => 'विष्णु',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'पौष पुत्रदा एकादशी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 11,
            'month_amanta' => 'Pausha',
            'month_purnimanta' => 'Pausha',
            'description' => 'पौष पुत्रदा एकादशी के लिए व्रत',
            'deity' => 'विष्णु',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'शाकंभरी पूर्णिमा' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Pausha',
            'month_purnimanta' => 'Pausha',
            'description' => 'शाकंभरी नवरात्रि का समापन; देवी शाकंभरी की पूजा जिन्होंने सब्जियों और फलों से दुनिया का पोषण किया',
            'deity' => 'शाकंभरी/देवी',
            'regions' => ['राजस्थान', 'उत्तर प्रदेश', 'मध्य प्रदेश', 'बिहार'],
        ],
        'थाई पूसम' =>
        [
            'nakshatra_only' => true,
            'nakshatra' => 'Pushya',
            'requires_purnima' => true,
            'allowed_months_amanta' => ['Pausha', 'Magha'],
            'description' => 'भगवान मुरुगन को समर्पित तमिल त्योहार; यह तब मनाया जाता है जब तमिल महीने थाई (जनवरी-फरवरी) में पुष्य नक्षत्र पूर्णिमा के साथ मेल खाता है',
            'deity' => 'मुरुगन',
            'regions' => ['तमिलनाडु', 'केरल', 'कर्नाटक', 'आंध्र प्रदेश', 'तेलंगाना', 'श्रीलंका', 'मलेशिया', 'सिंगापुर'],
        ],
        'ओणम (तिरुवोणम)' =>
        [
            'nakshatra_only' => true,
            'nakshatra' => 'Shravana',
            'allowed_months_amanta' => ['Shravana', 'Bhadrapada'],
            'description' => 'केरल का फसल उत्सव; मलयालम महीने चिंगम (अगस्त-सितंबर) में तिरुवोणम नक्षत्र (श्रवण); राजा महाबली की वार्षिक यात्रा का प्रतीक है',
            'deity' => 'विष्णु/महाबली',
            'regions' => ['केरल', 'तमिलनाडु', 'कर्नाटक'],
            'karmakala_type' => 'madhyahna',
        ],
        'गुणातीतानंद स्वामी दीक्षा दिन' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Pausha',
            'month_purnimanta' => 'Pausha',
            'description' => 'गुणातीतानंद स्वामी का दीक्षा दिवस',
            'deity' => 'स्वामीनारायण',
        ],
        'षटतिला एकादशी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 11,
            'month_amanta' => 'Pausha',
            'month_purnimanta' => 'Magha',
            'description' => 'षटतिला एकादशी के लिए व्रत',
            'deity' => 'विष्णु',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'मौनी अमावस्या' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 15,
            'month_amanta' => 'Pausha',
            'month_purnimanta' => 'Magha',
            'description' => 'कठोर मौन व्रत और पवित्र स्नान का दिन',
            'deity' => 'विष्णु',
            'fasting' => true,
        ],
        'वसंत पंचमी / शिक्षापत्री जयंती' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 5,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'देवी सरस्वती की पूजा / शिक्षापत्री जयंती',
            'deity' => 'सरस्वती/स्वामीनारायण',
            'karmakala_type' => 'sunrise',
        ],
        'रथ सप्तमी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 7,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'सूर्य जयंती',
            'deity' => 'सूर्य',
        ],
        'भीष्म अष्टमी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 8,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'भीष्म पितामह के प्रस्थान की वर्षगांठ',
            'deity' => 'भीष्म',
        ],
        'जया एकादशी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 11,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'जया एकादशी के लिए व्रत',
            'deity' => 'विष्णु',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'माघी पूर्णिमा / मासी मगम' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Magha',
            'description' => 'कुंभ मेला स्नान का दिन / तमिल पवित्र स्नान दिवस',
            'deity' => 'गंगा/शिव',
        ],
        'पुष्पदोलोत्सव (धुलेटी)' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 1,
            'month_amanta' => 'Phalguna',
            'month_purnimanta' => 'Phalguna',
            'description' => 'रंगों का त्योहार (धुलेटी/पुष्पदोलोत्सव)',
            'deity' => 'कृष्ण/स्वामीनारायण',
            'karmakala_type' => 'sunrise',
        ],
        'विजया एकादशी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 11,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Phalguna',
            'description' => 'विजया एकादशी के लिए व्रत',
            'deity' => 'विष्णु',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'महा शिवरात्रि' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 14,
            'month_amanta' => 'Magha',
            'month_purnimanta' => 'Phalguna',
            'description' => 'भगवान शिव की महान रात्रि',
            'deity' => 'शिव',
            'fasting' => true,
            'karmakala_type' => 'nishitha',
            'strict_karmakala' => true,
            'vriddhi_preference' => 'last',
        ],
        'फुलेरा दूज' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 2,
            'month_amanta' => 'Phalguna',
            'month_purnimanta' => 'Phalguna',
            'description' => 'फूलों का त्योहार',
            'deity' => 'कृष्ण',
        ],
        'आमलकी एकादशी' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 11,
            'month_amanta' => 'Phalguna',
            'month_purnimanta' => 'Phalguna',
            'description' => 'आमलकी एकादशी के लिए व्रत',
            'deity' => 'विष्णु',
            'fasting' => true,
            'karmakala_type' => 'sunrise',
        ],
        'होलिका दहन' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Phalguna',
            'month_purnimanta' => 'Phalguna',
            'description' => 'अलाव समारोह, बुराई पर अच्छाई की जीत',
            'deity' => 'विष्णु/हिरण्यकशिपु',
            'karmakala_type' => 'pradosha',
            'strict_karmakala' => true,
            'vriddhi_preference' => 'first',
        ],
        'भगतजी महाराज जयंती' =>
        [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 15,
            'month_amanta' => 'Phalguna',
            'month_purnimanta' => 'Phalguna',
            'description' => 'भगतजी महाराज का जन्म (स्वामीनारायण संप्रदाय)',
            'deity' => 'स्वामीनारायण',
        ],
        'होली' =>
        [
            'type' => 'day_after',
            'parent_festival' => 'होलिका दहन',
            'days_after' => 1,
            'description' => 'रंगों का त्योहार',
            'deity' => 'कृष्ण',
        ],
        'वरलक्ष्मी व्रतम' =>
        [
            'type' => 'weekday_tithi',
            'paksha' => 'Shukla',
            'tithi' =>
            [
                0 => 12,
                1 => 13,
                2 => 14,
                3 => 15,
            ],
            'weekday' => 5,
            'month_amanta' => 'Shravana',
            'month_purnimanta' => 'Shravana',
            'description' => 'समृद्धि के लिए देवी लक्ष्मी की पूजा',
            'deity' => 'लक्ष्मी',
            'fasting' => true,
        ],
        'पद्मिनी एकादशी' => [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Shukla',
            'tithi' => 11,
            'description' => 'विशेष एकादशी जो केवल अधिक मास के दौरान आती है',
            'deity' => 'विष्णु',
            'fasting' => true,
            'adhika_only' => true,
        ],
        'परमा एकादशी' => [
            'type' => 'tithi',
            'resolver' => 'classical',
            'paksha' => 'Krishna',
            'tithi' => 11,
            'description' => 'विशेष एकादशी जो केवल अधिक मास के कृष्ण पक्ष में आती है',
            'deity' => 'विष्णु',
            'fasting' => true,
            'adhika_only' => true,
        ],
    ];