<?php

declare(strict_types=1);

namespace JayeshMepani\PanchangCore\Core;

/**
 * Localization Service.
 */
class Localization
{
    private static array $translations = [
        'Nakshatra' => [
            'en' => ['Ashwini','Bharani','Krittika','Rohini','Mrigashira','Ardra','Punarvasu','Pushya','Ashlesha','Magha','Purva Phalguni','Uttara Phalguni','Hasta','Chitra','Swati','Vishakha','Anuradha','Jyeshtha','Mula','Purva Ashadha','Uttara Ashadha','Shravana','Dhanishta','Shatabhisha','Purva Bhadrapada','Uttara Bhadrapada','Revati'],
            'hi' => ['अश्विनी','भरणी','कृत्तिका','रोहिणी','मृगशिरा','आर्द्रा','पुनर्वसु','पुष्य','आश्लेषा','मघा','पूर्व फाल्गुनी','उत्तर फाल्गुनी','हस्त','चित્રા','स्वाती','विशाखा','अनुराधा','ज्येष्ठा','मूला','पूर्वाषाढ़ा','उत्तराषाढ़ा','श्रवण','धनिष्ठा','शतभिषा','पूर्व भाद्रपदा','उत्तर भाद्रपदा','रेवती'],
            'gu' => ['અશ્વિની','ભરણી','કૃત્તિકા','રોહિણી','મૃગશિરા','આર્દ્રા','પુનર્વસુ','પુષ્ય','આશ્લેષા','મઘા','પૂર્વ ફાલ્ગુની','ઉત્તર ફાલ્ગુની','હસ્ત','ચિત્રા','સ્વાતિ','વિશાખા','અનુરાધા','જ્યેષ્ઠા','મૂળ','પૂર્વાષાઢા','ઉત્તરાષાઢા','શ્રવણ','ધનિષ્ઠા','શતભિષા','પૂર્વ ભાદ્રપદા','ઉત્તર ભાદ્રપદા','રેવતી'],
        ],
        'Vara' => [
            'en' => ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
            'hi' => ['रविवार', 'सोमवार', 'मंगलवार', 'बुधवार', 'गुरुवार', 'शुक्रवार', 'शनिवार'],
            'gu' => ['રવિવાર', 'સોમવાર', 'મંગળવાર', 'બુધવાર', 'ગુરૂવાર', 'શુક્રવાર', 'શનિવાર'],
        ],
        'Tithi' => [
            'en' => [
                1 => 'Pratipada', 2 => 'Dwitiya', 3 => 'Tritiya', 4 => 'Chaturthi', 5 => 'Panchami',
                6 => 'Shashthi', 7 => 'Saptami', 8 => 'Ashtami', 9 => 'Navami', 10 => 'Dashami',
                11 => 'Ekadashi', 12 => 'Dwadashi', 13 => 'Trayodashi', 14 => 'Chaturdashi', 15 => 'Purnima',
                16 => 'Sud Pratipada', 17 => 'Sud Dwitiya', 18 => 'Sud Tritiya', 19 => 'Sud Chaturthi', 20 => 'Sud Panchami',
                21 => 'Sud Shashthi', 22 => 'Sud Saptami', 23 => 'Sud Ashtami', 24 => 'Sud Navami', 25 => 'Sud Dashami',
                26 => 'Sud Ekadashi', 27 => 'Sud Dwadashi', 28 => 'Sud Trayodashi', 29 => 'Sud Chaturdashi', 30 => 'Amavasya',
            ],
            'hi' => [
                1 => 'प्रतिपदा', 2 => 'द्वितीया', 3 => 'तृतीया', 4 => 'चतुर्थी', 5 => 'पंचमी',
                6 => 'षष्ठी', 7 => 'सप्तमी', 8 => 'अष्टमी', 9 => 'नवमी', 10 => 'दशमी',
                11 => 'एकादशी', 12 => 'द्वादशी', 13 => 'त्रयोदशी', 14 => 'चतुर्दशी', 15 => 'पूर्णिमा',
                16 => 'शुक्ल प्रतिपदा', 17 => 'शुक्ल द्वितीया', 18 => 'शुक्ल तृतीया', 19 => 'शुक्ल चतुर्थी', 20 => 'शुक्ल पंचमी',
                21 => 'शुक्ल षष्ठी', 22 => 'शुक्ल सप्तमी', 23 => 'शुक्ल अष्टमी', 24 => 'शुक्ल नवमी', 25 => 'शुक्ल दशमी',
                26 => 'शुक्ल एकादशी', 27 => 'शुक्ल द्वादशी', 28 => 'शुक्ल त्रयोदशी', 29 => 'शुक्ल चतुर्दशी', 30 => 'अमावस्या',
            ],
            'gu' => [
                1 => 'પ્રતિપદા', 2 => 'દ્વિતિયા', 3 => 'તૃતિયા', 4 => 'ચતુર્થી', 5 => 'પંચમી',
                6 => 'ષષ્ઠી', 7 => 'સપ્તમી', 8 => 'અષ્ટમી', 9 => 'નવમી', 10 => 'દશમી',
                11 => 'એકાદશી', 12 => 'દ્વાદશી', 13 => 'ત્રયોદશી', 14 => 'ચતુર્દશી', 15 => 'પૂર્ણિમા',
                16 => 'સુદ પ્રતિપદા', 17 => 'સુદ દ્વિતિયા', 18 => 'સુદ તૃતિયા', 19 => 'સુદ ચતુર્થી', 20 => 'સુદ પંચમી',
                21 => 'સુદ ષષ્ઠી', 22 => 'સુદ સપ્તમી', 23 => 'સુદ અષ્ટમી', 24 => 'સુદ નવમી', 25 => 'સુદ દશમી',
                26 => 'સુદ એકાદશી', 27 => 'સુદ દ્વાદશી', 28 => 'સુદ ત્રયોદશી', 29 => 'સુદ ચતુર્દશી', 30 => 'અમાવસ્યા',
            ],
        ],
        'Rasi' => [
            'en' => ['Mesha', 'Vrishabha', 'Mithuna', 'Karka', 'Simha', 'Kanya', 'Tula', 'Vrischika', 'Dhanu', 'Makara', 'Kumbha', 'Meena'],
            'hi' => ['मेष', 'वृषभ', 'मिथुन', 'कर्क', 'सिंह', 'कन्या', 'तुला', 'वृश्चिक', 'धनु', 'मकर', 'कुंभ', 'मीन'],
            'gu' => ['મેષ', 'વૃષભ', 'મિથુન', 'કર્ક', 'સિંહ', 'કન્યા', 'તુલા', 'વૃશ્ચિક', 'ધનુ', 'મકર', 'કુંભ', 'મીન'],
        ],
        'Yoga' => [
            'en' => ['Vishkumbha', 'Priti', 'Ayushman', 'Saubhagya', 'Shobhana', 'Atiganda', 'Sukarma', 'Dhriti', 'Shula', 'Ganda', 'Vriddhi', 'Dhruva', 'Vyaghata', 'Harshana', 'Vajra', 'Siddhi', 'Vyatipata', 'Variyana', 'Parigha', 'Shiva', 'Siddha', 'Sadhya', 'Shubha', 'Shukla', 'Brahma', 'Indra', 'Vaidhriti'],
            'hi' => ['विष्कुम्भ', 'प्रीति', 'आयुष्मान', 'सौभाग्य', 'शोभन', 'अतिगण्ड', 'सुकर्मा', 'धृति', 'शूल', 'गण्ड', 'वृद्धि', 'ध्रुव', 'व्याघात', 'हर्षण', 'वज्र', 'सिद्धि', 'व्यतिपात', 'वरीयान', 'परिघ', 'शिव', 'सिद्ध', 'साध्य', 'शुभ', 'शुक्ल', 'ब्रह्म', 'इन्द्र', 'वैधृति'],
            'gu' => ['વિષ્કુંભ', 'પ્રીતિ', 'આયુષ્માન', 'સૌભાગ્ય', 'શોભન', 'અતિગંડ', 'સુકર્મા', 'ધૃતિ', 'શૂલ', 'ગંડ', 'વૃદ્ધિ', 'ધ્રુવ', 'વ્યાઘાત', 'હર્ષણ', 'વજ્ર', 'સિદ્ધિ', 'વ્યતિપાત', 'વરીયાન', 'પરીઘ', 'શિવ', 'સિદ્ધ', 'સાધ્ય', 'શુભ', 'શુક્લ', 'બ્રહ્મ', 'ઇન્દ્ર', 'વૈધૃતિ'],
        ],
        'Karana' => [
            'en' => ['Bava', 'Balava', 'Kaulava', 'Taitila', 'Gara', 'Vanija', 'Vishti', 'Shakuni', 'Chatushpada', 'Naga', 'Kintughna'],
            'hi' => ['बव', 'बालव', 'कौलव', 'तैतिल', 'गर', 'वणिज', 'विष्टि', 'शकुनि', 'चतुष्पद', 'नाग', 'किस्तुघ्न'],
            'gu' => ['બવ', 'બાલવ', 'કૌલવ', 'તૈતિલ', 'ગર', 'વણિજ', 'વિષ્ટિ', 'શકુનિ', 'ચતુષ્પદ', 'નાગ', 'કિંસ્તુઘ્ન'],
        ],
        'Choghadiya' => [
            'en' => ['Udveg', 'Chal', 'Labh', 'Amrit', 'Kaal', 'Shubh', 'Rog'],
            'hi' => ['उद्वेग', 'चल', 'लाभ', 'अमृत', 'काल', 'शुभ', 'रोग'],
            'gu' => ['ઉદવેગ', 'ચલ', 'લાભ', 'અમૃત', 'કાલ', 'શુભ', 'રોગ'],
        ],
        'Muhurta' => [
            'en' => [
                0 => 'Rudra', 1 => 'Sarpa', 2 => 'Mitra', 3 => 'Pitri', 4 => 'Vasu', 5 => 'Vara', 6 => 'Vishvedeva', 7 => 'Vidhi', 8 => 'Brahma', 9 => 'Indra', 10 => 'Indragni', 11 => 'Daitya', 12 => 'Varuna', 13 => 'Aryaman', 14 => 'Bhaga',
                15 => 'Ishvara', 16 => 'Ajapada', 17 => 'Ahirbudhnya', 18 => 'Pushya', 19 => 'Nasatya', 20 => 'Yama', 21 => 'Vahni', 22 => 'Dhala', 23 => 'Shashi', 24 => 'Aditya', 25 => 'Guru', 26 => 'Acyuta', 27 => 'Arka', 28 => 'Tvashta', 29 => 'Vayu'
            ],
            'hi' => [
                0 => 'रुद्र', 1 => 'सर्प', 2 => 'मित्र', 3 => 'पितृ', 4 => 'वसु', 5 => 'वाराह', 6 => 'विश्वेदेवा', 7 => 'विधि', 8 => 'ब्रह्मा', 9 => 'इन्द्र', 10 => 'इन्द्राग्नि', 11 => 'दैत्य', 12 => 'वरुण', 13 => 'अर्यमा', 14 => 'भग',
                15 => 'ईश्वर', 16 => 'अजपाद', 17 => 'अहिर्बुध्न्य', 18 => 'पुष्य', 19 => 'नासत्य', 20 => 'यम', 21 => 'वह्नि', 22 => 'धला', 23 => 'शशि', 24 => 'आदित्य', 25 => 'गुरु', 26 => 'अच्युत', 27 => 'अर्क', 28 => 'त्वष्टा', 29 => 'वायु'
            ],
            'gu' => [
                0 => 'રુદ્ર', 1 => 'સર્પ', 2 => 'મિત્ર', 3 => 'પિતૃ', 4 => 'વસુ', 5 => 'વારાહ', 6 => 'વિશ્વેદેવા', 7 => 'વિધિ', 8 => 'બ્રહ્મા', 9 => 'ઇન્દ્ર', 10 => 'ઇન્દ્રાજ્ઞિ', 11 => 'દૈત્ય', 12 => 'વરુણ', 13 => 'અર્યમા', 14 => 'ભગ',
                15 => 'ઈશ્વર', 16 => 'અજપાદ', 17 => 'અહિર્બુધ્ન્ય', 18 => 'પુષ્ય', 19 => 'નાસત્ય', 20 => 'યમ', 21 => 'વહ્નિ', 22 => 'ધલા', 23 => 'શશિ', 24 => 'આદિત્ય', 25 => 'ગુરુ', 26 => 'અચ્યુત', 27 => 'અર્ક', 28 => 'ત્વષ્ટા', 29 => 'વાયુ'
            ],
        ],
        'Masa' => [
            'en' => ['Chaitra', 'Vaishakha', 'Jyeshtha', 'Ashadha', 'Shravana', 'Bhadrapada', 'Ashvina', 'Kartika', 'Margashirsha', 'Pausha', 'Magha', 'Phalguna'],
            'hi' => ['चैत्र', 'वैशाख', 'ज्येष्ठ', 'आषाढ़', 'श्रावण', 'भाद्रपद', 'अश्विन', 'कार्तिक', 'मार्गशीर्ष', 'पौष', 'माघ', 'फाल्गुन'],
            'gu' => ['ચૈત્ર', 'વૈશાખ', 'જેઠ', 'અષાઢ', 'શ્રાવણ', 'ભાદરવો', 'આસો', 'કારતક', 'માગશર', 'પોષ', 'મહા', 'ફાગણ'],
        ],
        'Paksha' => [
            'en' => ['Shukla Paksha (waxing)', 'Krishna Paksha (waning)'],
            'hi' => ['शुक्ल', 'कृष्ण'],
            'gu' => ['શુક્લ', 'કૃષ્ણ'],
        ],
        'Ritu' => [
            'en' => ['Vasanta', 'Grishma', 'Varsha', 'Sharad', 'Hemanta', 'Shishira'],
            'hi' => ['वसंत', 'ग्रीष्म', 'वर्षा', 'शरद', 'हेमंत', 'शिशिर'],
            'gu' => ['વસંત', 'ગ્રીષ્મ', 'વર્ષા', 'શરદ', 'હેમંત', 'શિશિર'],
        ],
        'Ayana' => [
            'en' => ['Uttarayana', 'Dakshinayana'],
            'hi' => ['उत्तरायण', 'दक्षिणायन'],
            'gu' => ['ઉત્તરાયણ', 'દક્ષિણાયન'],
        ],
        'Planet' => [
            'en' => ['Sun', 'Moon', 'Mars', 'Rahu', 'Jupiter', 'Saturn', 'Mercury', 'Ketu', 'Venus'],
            'hi' => ['सूर्य', 'चन्द्र', 'मंगल', 'राहु', 'गुरु', 'शनि', 'बुध', 'केतु', 'शुक्र'],
            'gu' => ['સૂર્ય', 'ચંદ્ર', 'મંગળ', 'રાહુ', 'ગુરૂ', 'શનિ', 'બુધ', 'કેતુ', 'શુક્ર'],
        ],
        'Samvatsara' => [
            'en' => ['Prabhava','Vibhava','Shukla','Pramoda','Prajapati','Angirasa','Srimukha','Bhava','Yuva','Dhata','Ishvara','Bahudhanya','Pramathi','Vikrama','Vrisha','Chitrabhanu','Svabhanu','Tarana','Parthiva','Vyaya','Sarvajit','Sarvadhari','Virodi','Vikriti','Khara','Nandana','Vijaya','Jaya','Manmatha','Durmukhi','Hevilambi','Vilambi','Vikari','Sharvari','Plava','Shubhakritu','Shobhakritu','Krodhi','Vishvavasu','Parabhava','Plavanga','Kilaka','Saumya','Sadharana','Virodhikritu','Paritapi','Pramadi','Ananda','Rakshasa','Nala','Pingala','Kalayukti','Siddharthi','Raudri','Durmati','Dundubhi','Rudhirodgari','Raktakshi','Krodhana','Akshaya'],
            'hi' => ['प्रभव','विभव','शुक्ल','प्रमोद','प्रजापति','अंगिरा','श्रीमुख','भाव','युवा','धाता','ईश्वर','बहुधान्य','प्रमाथी','विक्रम','वृष','चित्रभानु','स्वभानु','तारण','पार्थिव','व्यय','सर्वजित','सर्वधारी','विरोधी','विकृति','खर','नन्दन','विजय','जय','मन्मथ','दुर्मुख','हेविलम्बी','विलम्बी','विकारी','शर्वरी','प्लव','शुभकृत','शोभनकृत','क्रोधी','विश्वावसु','पराभव','प्लवंग','कीलक','सौम्य','साधारण','विरोधकृत','परितापी','प्रमादी','आनन्द','राक्षस','नल','पिंगल','कालयुक्त','सिद्धार्थी','रौद्र','दुर्मति','दुन्दुभी','रुधिरोद्गारी','रक्ताक्ष','क्रोधन','अक्षय'],
            'gu' => ['પ્રભવ','વિભવ','શુક્લ','પ્રમોદ','પ્રજાપતિ','અંગિરા','શ્રીમુખ','ભાવ','યુવા','ધાતા','ઈશ્વર','બહુધાન્ય','પ્રમાથી','વિક્રમ','વૃષ','ચિત્રભાનુ','સ્વભાનુ','તારણ','પાર્થિવ','વ્યય','સર્વજિત','સર્વધારી','વિરોધી','વિૃતિ','ખર','નંદન','વિજય','જય','મન્મથ','દુર્મુખ','હેવિલંબી','વિલંબી','વિકારી','શાર્વરી','પ્લવ','શુભકૃત','શોભનકૃત','ક્રોધી','વિશ્વાવસુ','પરાભવ','પ્લવંગ','કીલક','સૌમ્ય','સાધારણ','વિરોધકૃત','પરિતાપી','પ્રમાદી','આનંદ','રાક્ષસ','નલ','પિંગલ','કાલયુક્ત','સિદ્ધાર્થી','રૌદ્ર','દુર્મતિ','દુંદુભી','રુધિરોદ્ગારી','રક્તાક્ષ','ક્રોધન','અક્ષય'],
        ],
        'Vrata' => [
            'en' => [
                'Pratipada Vrata' => 'Pratipada Vrata',
                'Dwitiya Vrata' => 'Dwitiya Vrata',
                'Tritiya Vrata' => 'Tritiya Vrata',
                'Chaturthi Vrata' => 'Chaturthi Vrata',
                'Panchami Vrata' => 'Panchami Vrata',
                'Shashthi Vrata' => 'Shashthi Vrata',
                'Saptami Vrata' => 'Saptami Vrata',
                'Ashtami Vrata' => 'Ashtami Vrata',
                'Navami Vrata' => 'Navami Vrata',
                'Dashami Vrata' => 'Dashami Vrata',
                'Ekadashi Vrata' => 'Ekadashi Vrata',
                'Dwadashi Vrata' => 'Dwadashi Vrata',
                'Trayodashi Vrata' => 'Trayodashi Vrata',
                'Chaturdashi Vrata' => 'Chaturdashi Vrata',
                'Purnima / Amavasya Vrata' => 'Purnima / Amavasya Vrata',
            ],
            'hi' => [
                'Pratipada Vrata' => 'प्रतिपदा व्रत',
                'Dwitiya Vrata' => 'द्वितीया व्रत',
                'Tritiya Vrata' => 'तृतीया व्रत',
                'Chaturthi Vrata' => 'चतुर्थी व्रत',
                'Panchami Vrata' => 'पंचमी व्रत',
                'Shashthi Vrata' => 'षष्ठी व्रत',
                'Saptami Vrata' => 'सप्तमी व्रत',
                'Ashtami Vrata' => 'अष्टमी व्रत',
                'Navami Vrata' => 'नवमी व्रत',
                'Dashami Vrata' => 'दशमी व्रत',
                'Ekadashi Vrata' => 'एकादशी व्रत',
                'Dwadashi Vrata' => 'द्वादशी व्रत',
                'Trayodashi Vrata' => 'त्रयोदशी व्रत',
                'Chaturdashi Vrata' => 'चतुर्दशी व्रत',
                'Purnima / Amavasya Vrata' => 'पूर्णिमा / अमावस्या व्रत',
            ],
            'gu' => [
                'Pratipada Vrata' => 'પ્રતિપદા વ્રત',
                'Dwitiya Vrata' => 'દ્વિતિયા વ્રત',
                'Tritiya Vrata' => 'તૃતિયા વ્રત',
                'Chaturthi Vrata' => 'ચતુર્થી વ્રત',
                'Panchami Vrata' => 'પંચમી વ્રત',
                'Shashthi Vrata' => 'ષષ્ઠી વ્રત',
                'Saptami Vrata' => 'સપ્તમી વ્રત',
                'Ashtami Vrata' => 'અષ્ટમી વ્રત',
                'Navami Vrata' => 'નવમી વ્રત',
                'Dashami Vrata' => 'દશમી વ્રત',
                'Ekadashi Vrata' => 'એકાદશી વ્રત',
                'Dwadashi Vrata' => 'દ્વાદશી વ્રત',
                'Trayodશી વ્રત' => 'ત્રયોદશી વ્રત',
                'Chaturdashi Vrata' => 'ચતુર્દશી વ્રત',
                'Purnima / Amavasya Vrata' => 'પૂર્ણિમા / અમાવસ્યા વ્રત',
            ],
        ],
        'Eclipse' => [
            'en' => ['Total' => 'Total', 'Partial' => 'Partial', 'Annular' => 'Annular', 'Annular-Total' => 'Annular-Total', 'Penumbral' => 'Penumbral', 'Partial Penumbral' => 'Partial Penumbral'],
            'hi' => ['Total' => 'पूर्ण', 'Partial' => 'आंशिक', 'Annular' => 'वलयाकार', 'Annular-Total' => 'वलयाकार-पूर्ण', 'Penumbral' => 'उपछाया', 'Partial Penumbral' => 'आंशिक उपछाया'],
            'gu' => ['Total' => 'સંપૂર્ણ', 'Partial' => 'આંશિક', 'Annular' => 'વલયાકાર', 'Annular-Total' => 'વલયાકાર-સંપૂર્ણ', 'Penumbral' => 'ઉપછાયા', 'Partial Penumbral' => 'આંશિક ઉપછાયા'],
        ],
        'Festival' => [
            'en' => [
                'Hanuman Jayanti' => 'Hanuman Jayanti',
                'Rama Navami' => 'Rama Navami',
                'Ganesh Chaturthi' => 'Ganesh Chaturthi',
                'Diwali' => 'Diwali',
                'Holi' => 'Holi',
                'Maha Shivaratri' => 'Maha Shivaratri',
                'Janmashtami' => 'Janmashtami',
                'Navaratri' => 'Navaratri',
                'Dussehra' => 'Dussehra',
                'Raksha Bandhan' => 'Raksha Bandhan',
            ],
            'hi' => [
                'Hanuman Jayanti' => 'हनुमान जयंती',
                'Rama Navami' => 'राम नवमी',
                'Ganesh Chaturthi' => 'गणेश चतुर्थी',
                'Diwali' => 'दीपावली',
                'Holi' => 'होली',
                'Maha Shivaratri' => 'महा शिवरात्रि',
                'Janmashtami' => 'कृष्ण जन्माष्टमी',
                'Navaratri' => 'नवरात्रि',
                'Dussehra' => 'दशहरा',
                'Raksha Bandhan' => 'रक्षाबंधन',
            ],
            'gu' => [
                'Hanuman Jayanti' => 'હનૂમાન જયંતિ',
                'Rama Navami' => 'રામ નવમી',
                'Ganesh Chaturthi' => 'ગણેશ ચતુર્થી',
                'Diwali' => 'દિવાળી',
                'Holi' => 'હોળી',
                'Maha Shivaratri' => 'મહા શિવરાત્રી',
                'Janmashtami' => 'જન્માષ્ટમી',
                'Navaratri' => 'નવરાત્રી',
                'Dussehra' => 'દશેરા',
                'Raksha Bandhan' => 'રક્ષાબંધન',
            ],
        ],
        'Panchaka' => [
            'en' => [
                'Mrityu' => 'Mrityu', 'Death' => 'Death',
                'Agni' => 'Agni', 'Fire' => 'Fire',
                'Rahita' => 'Rahita',
                'Raja' => 'Raja', 'King' => 'King',
                'Chora' => 'Chora', 'Thief' => 'Thief',
                'Roga' => 'Roga', 'Disease' => 'Disease',
            ],
            'hi' => [
                'Mrityu' => 'मृत्यु', 'Death' => 'मृत्यु',
                'Agni' => 'अग्नि', 'Fire' => 'अग्नि',
                'Rahita' => 'रहित',
                'Raja' => 'राज', 'King' => 'राज',
                'Chora' => 'चोर', 'Thief' => 'चोर',
                'Roga' => 'रोग', 'Disease' => 'रोग',
            ],
            'gu' => [
                'Mrityu' => 'મૃત્યુ', 'Death' => 'મૃત્યુ',
                'Agni' => 'અગ્નિ', 'Fire' => 'અગ્નિ',
                'Rahita' => 'રહિત',
                'Raja' => 'રાજ', 'King' => 'રાજ',
                'Chora' => 'ચોર', 'Thief' => 'ચોર',
                'Roga' => 'રોગ', 'Disease' => 'રોગ',
            ],
        ],
        'Moorthy' => [
            'en' => [
                'Suvarna' => 'Suvarna', 'Gold' => 'Gold',
                'Rajata' => 'Rajata', 'Silver' => 'Silver',
                'Tamra' => 'Tamra', 'Copper' => 'Copper',
                'Lauha' => 'Lauha', 'Iron' => 'Iron',
            ],
            'hi' => [
                'Suvarna' => 'सुवर्ण', 'Gold' => 'सुवर्ण (सोना)',
                'Rajata' => 'रजत', 'Silver' => 'रजत (चांदी)',
                'Tamra' => 'ताम्र', 'Copper' => 'ताम्र (तांबा)',
                'Lauha' => 'लौह', 'Iron' => 'लौह (लोहा)',
            ],
            'gu' => [
                'Suvarna' => 'સુવર્ણ', 'Gold' => 'સુવર્ણ',
                'Rajata' => 'રજત', 'Silver' => 'રજત',
                'Tamra' => 'તામ્ર', 'Copper' => 'તામ્ર',
                'Lauha' => 'લોહ', 'Iron' => 'લોહ',
            ],
        ],
        'Gowri' => [
            'en' => [
                'Uthi' => 'Uthi', 'Amirdha' => 'Amirdha', 'Rogam' => 'Rogam', 'Laabam' => 'Laabam',
                'Dhanam' => 'Dhanam', 'Sugam' => 'Sugam', 'Soram' => 'Soram', 'Visham' => 'Visham'
            ],
            'hi' => [
                'Uthi' => 'उथि', 'Amirdha' => 'अमिरधा', 'Rogam' => 'रोगम', 'Laabam' => 'लाभम',
                'Dhanam' => 'धनम', 'Sugam' => 'सुगम', 'Soram' => 'सोरम', 'Visham' => 'विषम'
            ],
            'gu' => [
                'Uthi' => 'ઉથિ', 'Amirdha' => 'અમિરધા', 'Rogam' => 'રોગમ', 'Laabam' => 'લાભમ',
                'Dhanam' => 'ધનમ', 'Sugam' => 'સુગમ', 'Soram' => 'સોરમ', 'Visham' => 'વિષમ'
            ],
        ],
        'GowriQuality' => [
            'en' => ['best' => 'best', 'wealth' => 'wealth', 'good' => 'good', 'gain' => 'gain', 'evil' => 'evil', 'bad' => 'bad'],
            'hi' => ['best' => 'सर्वोत्तम', 'wealth' => 'धन', 'good' => 'अच्छा', 'gain' => 'लाभ', 'evil' => 'दुष्ट', 'bad' => 'बुरा'],
            'gu' => ['best' => 'સર્વોત્તમ', 'wealth' => 'ધન', 'good' => 'સારું', 'gain' => 'લાભ', 'evil' => 'દુષ્ટ', 'bad' => 'ખરાબ'],
        ],
        'MuhurtaDesc' => [
            'en' => [
                'Brahma Muhurta significance' => 'Most auspicious time for meditation, study, and spiritual practices. Sattvik period filled with purity, calmness, and clarity.',
                'Varjyam active' => 'Varjyam is active at the evaluation time.',
                'Varjyam not active' => 'Varjyam is not active at the evaluation time.',
                'Bhadra not active' => 'Bhadra (Vishti Karana) is not active at the evaluation time.',
                'Bhadra active blocked' => 'Bhadra is active in a blocked portion now.',
                'Bhadra puchha active' => 'Only Bhadra Puchha is active now; this portion is relatively safe.',
                'Named window not available' => 'window is not available for the evaluation time.',
                'Named window active' => 'Window is active at the evaluation time.',
                'Named window not active' => 'Window is not active at the evaluation time.',
            ],
            'hi' => [
                'Brahma Muhurta significance' => 'ध्यान, अध्ययन और आध्यात्मिक अभ्यास के लिए सबसे शुभ समय। शुद्धता, शांति और स्पष्टता से भरा सात्विक काल।',
                'Varjyam active' => 'वर्ज्यम मूल्यांकन समय पर सक्रिय है।',
                'Varjyam not active' => 'वर्ज्यम मूल्यांकन समय पर सक्रिय नहीं है।',
                'Bhadra not active' => 'भद्र (विष्टि करण) मूल्यांकन समय पर सक्रिय नहीं है।',
                'Bhadra active blocked' => 'भद्र अब अवरुद्ध भाग में सक्रिय है।',
                'Bhadra puchha active' => 'केवल भद्र पुच्छ अब सक्रिय है; यह भाग अपेक्षाकृत सुरक्षित है।',
                'Named window not available' => 'विंडो मूल्यांकन समय के लिए उपलब्ध नहीं है।',
                'Named window active' => 'विंडो मूल्यांकन समय पर सक्रिय है।',
                'Named window not active' => 'विंडो मूल्यांकन समय पर सक्रिय नहीं है।',
            ],
            'gu' => [
                'Brahma Muhurta significance' => 'ધ્યાન, અભ્યાસ અને આધ્યાત્મિક અભ્યાસ માટે સૌથી શુભ સમય. શુદ્ધતા, શાંતિ અને સ્પષ્ટતાથી ભરેલો સાત્વિક કાળ.',
                'Varjyam active' => 'વર્જ્યમ મૂલ્યાંકન સમયે સક્રિય છે.',
                'Varjyam not active' => 'વર્જ્યમ મૂલ્યાંકન સમયે સક્રિય નથી.',
                'Bhadra not active' => 'ભદ્ર (વિષ્ટિ કરણ) મૂલ્યાંકન સમયે સક્રિય નથી.',
                'Bhadra active blocked' => 'ભદ્ર હવે અવરુદ્ધ ભાગમાં સક્રિય છે.',
                'Bhadra puchha active' => 'માત્ર ભદ્ર પુચ્છ હવે સક્રિય છે; આ ભાગ સાપેક્ષ રીતે સુરક્ષિત છે.',
                'Named window not available' => 'વિન્ડો મૂલ્યાંકન સમય માટે ઉપલબ્ધ નથી.',
                'Named window active' => 'વિન્ડો મૂલ્યાંકન સમયે સક્રિય છે.',
                'Named window not active' => 'વિન્ડો મૂલ્યાંકન સમયે સક્રિય નથી.',
            ],
        ],
        'Fivefold' => [
            'en' => ['Pratah', 'Sangava', 'Madhyahna', 'Aparahna', 'Sayahna'],
            'hi' => ['प्रातः', 'संगव', 'मध्याह्न', 'अपराह्न', 'सायह्न'],
            'gu' => ['પ્રાતઃ', 'સંગવ', 'મધ્યાહ્ન', 'અપરાહ્ન', 'સાયહ્ન'],
        ],
        'Prahara' => [
            'en' => [
                'Pratah Prahara' => 'Pratah Prahara', 'Sangava Prahara' => 'Sangava Prahara', 'Madhyahna Prahara' => 'Madhyahna Prahara', 'Aparahna Prahara' => 'Aparahna Prahara',
                'Pradosha Prahara' => 'Pradosha Prahara', 'Nishitha Prahara' => 'Nishitha Prahara', 'Triyama Prahara' => 'Triyama Prahara', 'Usha Prahara' => 'Usha Prahara'
            ],
            'hi' => [
                'Pratah Prahara' => 'प्रातः प्रहर', 'Sangava Prahara' => 'संगव प्रहर', 'Madhyahna Prahara' => 'मध्याह्न प्रहर', 'Aparahna Prahara' => 'अपराह्न प्रहर',
                'Pradosha Prahara' => 'प्रदोष प्रहर', 'Nishitha Prahara' => 'निशिथ प्रहर', 'Triyama Prahara' => 'त्रियाम प्रहर', 'Usha Prahara' => 'उषा प्रहर'
            ],
            'gu' => [
                'Pratah Prahara' => 'પ્રાતઃ પ્રહર', 'Sangava Prahara' => 'સંગવ પ્રહર', 'Madhyahna Prahara' => 'મધ્યાહ્ન પ્રહર', 'Aparahna Prahara' => 'અપરાહ્ન પ્રહર',
                'Pradosha Prahara' => 'પ્રદોષ પ્રહર', 'Nishitha Prahara' => 'નિશિથ પ્રહર', 'Triyama Prahara' => 'ત્રિયામ પ્રહર', 'Usha Prahara' => 'ઉષા પ્રહર'
            ],
        ],
        'Common' => [
            'en' => [
                'Adhika' => 'Adhika', 'Kshaya' => 'Kshaya', 'Sankranti' => 'Sankranti', 'Purnima' => 'Purnima', 'Amavasya' => 'Amavasya',
                'Auspicious' => 'Auspicious', 'Inauspicious' => 'Inauspicious', 'Neutral' => 'Neutral', 'Very Auspicious' => 'Very Auspicious',
                'Challenging' => 'Challenging', 'Excellent' => 'Excellent', 'Good' => 'Good', 'Mixed' => 'Mixed',
                'None' => 'None', 'Low' => 'Low', 'Medium' => 'Medium', 'High' => 'High', 'Critical' => 'Critical',
                'Earth' => 'Earth', 'Heaven' => 'Heaven', 'Underworld' => 'Underworld',
                'Sunrise' => 'Sunrise', 'Sunset' => 'Sunset', 'Moonrise' => 'Moonrise', 'Moonset' => 'Moonset',
                'Deity' => 'Deity', 'Benefit' => 'Benefit', 'Description' => 'Description', 'Fasting' => 'Fasting', 'Regions' => 'Regions',
                'rejected' => 'rejected', 'accepted' => 'accepted', 'accepted_with_warnings' => 'accepted_with_warnings', 'rejected_but_can_try_remedies' => 'rejected_but_can_try_remedies',
            ],
            'hi' => [
                'Adhika' => 'अधिक', 'Kshaya' => 'क्षय', 'Sankranti' => 'संक्रांति', 'Purnima' => 'पूर्णिमा', 'Amavasya' => 'अमावस्या',
                'Auspicious' => 'शुभ', 'Inauspicious' => 'अशुभ', 'Neutral' => 'सामान्य', 'Very Auspicious' => 'अति शुभ',
                'Challenging' => 'चुनौतीपूर्ण', 'Excellent' => 'उत्तम', 'Good' => 'अच्छा', 'Mixed' => 'मिश्रित',
                'None' => 'कोई नहीं', 'Low' => 'कम', 'Medium' => 'मध्यम', 'High' => 'उच्च', 'Critical' => 'गंभीर',
                'Earth' => 'पृथ्वी', 'Heaven' => 'स्वर्ग', 'Underworld' => 'पाताल',
                'Sunrise' => 'सूर्योदय', 'Sunset' => 'सूर्यास्त', 'Moonrise' => 'चन्द्रोदय', 'Moonset' => 'चन्द्रास्त',
                'Deity' => 'देवता', 'Benefit' => 'फल', 'Description' => 'विवरण', 'Fasting' => 'व्रत/उपवास', 'Regions' => 'क्षेत्र',
                'rejected' => 'अस्वीकृत', 'accepted' => 'स्वीकृत', 'accepted_with_warnings' => 'चेतावनियों के साथ स्वीकृत', 'rejected_but_can_try_remedies' => 'अस्वीकृत लेकिन उपाय किए जा सकते हैं',
            ],
            'gu' => [
                'Adhika' => 'અધિક', 'Kshaya' => 'ક્ષય', 'Sankranti' => 'સંક્રાંતિ', 'Purnima' => 'પૂર્ણિમા', 'Amavasya' => 'અમાવસ્યા',
                'Auspicious' => 'શુભ', 'Inauspicious' => 'અશુભ', 'Neutral' => 'સામાન્ય', 'Very Auspicious' => 'અતિ શુભ',
                'Challenging' => 'પડકારરૂપ', 'Excellent' => 'ઉત્તમ', 'Good' => 'સારું', 'Mixed' => 'મિશ્રિત',
                'None' => 'કોઈ નહીં', 'Low' => 'ઓછું', 'Medium' => 'મધ્યમ', 'High' => 'ઉચ્ચ', 'Critical' => 'ગંભીર',
                'Earth' => 'પૃથ્વી', 'Heaven' => 'સ્વર્ગ', 'Underworld' => 'પાતાળ',
                'Sunrise' => 'સૂર્યોદય', 'Sunset' => 'સૂર્યાસ્ત', 'Moonrise' => 'ચંદ્રોદય', 'Moonset' => 'ચંદ્રાસ્ત',
                'Deity' => 'દેવતા', 'Benefit' => 'ફળ', 'Description' => 'વર્ણન', 'Fasting' => 'ઉપવાસ', 'Regions' => 'વિસ્તાર',
                'rejected' => 'અસ્વીકૃત', 'accepted' => 'સ્વીકૃત', 'accepted_with_warnings' => 'ચેતવણીઓ સાથે સ્વીકૃત', 'rejected_but_can_try_remedies' => 'અસ્વીકૃત પરંતુ ઉપાયો કરી શકાય છે',
            ],
        ],
        'FestivalDesc' => [
    'en' => [
        'Mesha Sankranti (Baisakhi / Puthandu)' => 'Solar New Year',
        'Vrishabha Sankranti' => 'Sun enters Vrishabha',
        'Mithuna Sankranti' => 'Sun enters Mithuna',
        'Karka Sankranti' => 'Sun enters Karka',
        'Simha Sankranti' => 'Sun enters Simha',
        'Kanya Sankranti (Vishwakarma Puja)' => 'Worship of divine architect Vishwakarma',
        'Tula Sankranti' => 'Sun enters Tula',
        'Vrischika Sankranti' => 'Sun enters Vrischika',
        'Dhanu Sankranti' => 'Sun enters Dhanu',
        'Makara Sankranti (Pongal)' => 'Harvest festival, Sun enters Makara',
        'Kumbha Sankranti' => 'Sun enters Kumbha',
        'Meena Sankranti' => 'Sun enters Meena',
        'Vasi Uttarayan' => 'Second day of the kite festival in Gujarat',
        'Lohri' => 'Punjabi harvest festival; bonfire celebration marking end of winter solstice',
        'Cheti Chand' => 'Sindhi Hindu New Year; birth of Jhulelal (Ishta-Devta)',
        'Vishu' => 'Kerala Hindu New Year; first day of Medam month; Vishukkani arrangement',
        'Shastriji Maharaj Jayanti' => 'Birth anniversary of Shastriji Maharaj, founder of BAPS; coincides with Vasant Panchami',
        'Pramukh Varni Din' => 'Day when Pramukh Swami Maharaj was appointed administrative president of BAPS (1950)',
        'Ashadhi Bij' => 'Kutchi New Year; marks beginning of monsoon and kharif crop season; traditional weather prediction',
        'Ravechi Mata Fair' => 'Ancient fair at Ravechi Mata Temple (Rapar, Kutch); thousands of Rabari and Ahir devotees gather',
        'Tarnetar Fair' => 'Famous match-making fair of Saurashtra at Trinetreshwar Mahadev temple; Bhadarva Sud 4-6',
        'Tarnetar Fair Day 2' => 'Second day of Tarnetar Fair (Bhadarva Sud 5)',
        'Tarnetar Fair Day 3' => 'Third day of Tarnetar Fair (Bhadarva Sud 6)',
        'Mota Yaksh Fair (Jakh Bahotera)' => 'Largest fair in Kutch at Kakadbhit; honors 72 Yakshas who protected locals; Bhadarva Vad 12-14',
        'Dada Mekan Fair (Dhrang Mela)' => 'Fair at Dhrang village honoring saint Mekan Dada who saved lost travelers in Rann of Kutch',
        'Rang Panchami' => 'Fifth day of Holi celebrations; continuation of color play; especially celebrated in Maharashtra and MP',
        'Chaitra (Vasant) Navaratri Day 1 (Shailaputri Puja)' => 'Chaitra (Vasant) Navaratri - Worship of Shailaputri (Daughter of the Mountain]',
        'Chaitra (Vasant) Navaratri Day 2 (Brahmacharini Puja)' => 'Chaitra (Vasant) Navaratri - Worship of Brahmacharini (The Ascetic]',
        'Chaitra (Vasant) Navaratri Day 3 (Chandraghanta Puja)' => 'Chaitra (Vasant) Navaratri - Worship of Chandraghanta (Bearer of the Moon-Bell]',
        'Chaitra (Vasant) Navaratri Day 4 (Kushmanda Puja)' => 'Chaitra (Vasant) Navaratri - Worship of Kushmanda (Creator of the Cosmic Egg]',
        'Chaitra (Vasant) Navaratri Day 5 (Skandamata Puja)' => 'Chaitra (Vasant) Navaratri - Worship of Skandamata (Mother of Skanda]',
        'Chaitra (Vasant) Navaratri Day 6 (Katyayani Puja)' => 'Chaitra (Vasant) Navaratri - Worship of Katyayani (The Warrior Goddess]',
        'Chaitra (Vasant) Navaratri Day 7 (Kalaratri Puja)' => 'Chaitra (Vasant) Navaratri - Worship of Kalaratri (The Fierce Night] / Maha Saptami',
        'Chaitra (Vasant) Navaratri Day 8 (Mahagauri Puja)' => 'Chaitra (Vasant) Navaratri - Worship of Mahagauri (The Great White One] / Maha Ashtami',
        'Chaitra (Vasant) Navaratri Day 9 (Siddhidatri Puja)' => 'Chaitra (Vasant) Navaratri - Worship of Siddhidatri (Giver of Supernatural Powers] / Maha Navami',
        'Ashvina Sharad Navaratri Day 1 (Shailaputri Puja)' => 'Ashvina Sharad Navaratri - Worship of Shailaputri (Daughter of the Mountain]',
        'Ashvina Sharad Navaratri Day 2 (Brahmacharini Puja)' => 'Ashvina Sharad Navaratri - Worship of Brahmacharini (The Ascetic]',
        'Ashvina Sharad Navaratri Day 3 (Chandraghanta Puja)' => 'Ashvina Sharad Navaratri - Worship of Chandraghanta (Bearer of the Moon-Bell]',
        'Ashvina Sharad Navaratri Day 4 (Kushmanda Puja)' => 'Ashvina Sharad Navaratri - Worship of Kushmanda (Creator of the Cosmic Egg]',
        'Ashvina Sharad Navaratri Day 5 (Skandamata Puja)' => 'Ashvina Sharad Navaratri - Worship of Skandamata (Mother of Skanda]',
        'Ashvina Sharad Navaratri Day 6 (Katyayani Puja)' => 'Ashvina Sharad Navaratri - Worship of Katyayani (The Warrior Goddess]',
        'Ashvina Sharad Navaratri Day 7 (Kalaratri Puja)' => 'Ashvina Sharad Navaratri - Worship of Kalaratri (The Fierce Night] / Maha Saptami',
        'Durga Ashtami (Mahagauri Puja)' => 'Ashvina Sharad Navaratri - Worship of Mahagauri (The Great White One] / Maha Ashtami',
        'Maha Navami (Siddhidatri Puja)' => 'Ashvina Sharad Navaratri - Worship of Siddhidatri (Giver of Supernatural Powers] / Maha Navami',
        'Ashadha Gupt Navaratri Day 1 (Kali Puja)' => 'Ashadha Gupt Navaratri (10 Mahavidyas] - Worship of Kali (Destroyer of Time]',
        'Ashadha Gupt Navaratri Day 2 (Tara Puja)' => 'Ashadha Gupt Navaratri (10 Mahavidyas] - Worship of Tara (Protector and Guide]',
        'Ashadha Gupt Navaratri Day 3 (Tripura Sundari Puja)' => 'Ashadha Gupt Navaratri (10 Mahavidyas] - Worship of Tripura Sundari / Shodashi (Beauty of Three Worlds]',
        'Ashadha Gupt Navaratri Day 4 (Bhuvaneshwari Puja)' => 'Ashadha Gupt Navaratri (10 Mahavidyas] - Worship of Bhuvaneshwari (Goddess of the Universe]',
        'Ashadha Gupt Navaratri Day 5 (Bhairavi Puja)' => 'Ashadha Gupt Navaratri (10 Mahavidyas] - Worship of Bhairavi (Fierce Goddess of Decay and Rebirth]',
        'Ashadha Gupt Navaratri Day 6 (Chhinnamasta Puja)' => 'Ashadha Gupt Navaratri (10 Mahavidyas] - Worship of Chhinnamasta (Self-Decapitated Goddess]',
        'Ashadha Gupt Navaratri Day 7 (Dhumavati Puja)' => 'Ashadha Gupt Navaratri (10 Mahavidyas] - Worship of Dhumavati (The Widow Goddess]',
        'Ashadha Gupt Navaratri Day 8 (Bagalamukhi Puja)' => 'Ashadha Gupt Navaratri (10 Mahavidyas] - Worship of Bagalamukhi (Paralyzer of Enemies]',
        'Ashadha Gupt Navaratri Day 9 (Matangi Puja)' => 'Ashadha Gupt Navaratri (10 Mahavidyas] - Worship of Matangi (Tantric Saraswati / Arts and Music]',
        'Ashadha Gupt Navaratri Day 10 (Kamala Puja)' => 'Ashadha Gupt Navaratri (10 Mahavidyas] - Worship of Kamala (Tantric Lakshmi / Prosperity and Fertility]',
        'Magha Gupt Navaratri Day 1 (Kali Puja)' => 'Magha Gupt Navaratri (10 Mahavidyas] - Worship of Kali (Destroyer of Time]',
        'Magha Gupt Navaratri Day 2 (Tara Puja)' => 'Magha Gupt Navaratri (10 Mahavidyas] - Worship of Tara (Protector and Guide]',
        'Magha Gupt Navaratri Day 3 (Tripura Sundari Puja)' => 'Magha Gupt Navaratri (10 Mahavidyas] - Worship of Tripura Sundari / Shodashi (Beauty of Three Worlds]',
        'Magha Gupt Navaratri Day 4 (Bhuvaneshwari Puja)' => 'Magha Gupt Navaratri (10 Mahavidyas] - Worship of Bhuvaneshwari (Goddess of the Universe]',
        'Magha Gupt Navaratri Day 5 (Bhairavi Puja)' => 'Magha Gupt Navaratri (10 Mahavidyas] - Worship of Bhairavi (Fierce Goddess of Decay and Rebirth]',
        'Magha Gupt Navaratri Day 6 (Chhinnamasta Puja)' => 'Magha Gupt Navaratri (10 Mahavidyas] - Worship of Chhinnamasta (Self-Decapitated Goddess]',
        'Magha Gupt Navaratri Day 7 (Dhumavati Puja)' => 'Magha Gupt Navaratri (10 Mahavidyas] - Worship of Dhumavati (The Widow Goddess]',
        'Magha Gupt Navaratri Day 8 (Bagalamukhi Puja)' => 'Magha Gupt Navaratri (10 Mahavidyas] - Worship of Bagalamukhi (Paralyzer of Enemies]',
        'Magha Gupt Navaratri Day 9 (Matangi Puja)' => 'Magha Gupt Navaratri (10 Mahavidyas] - Worship of Matangi (Tantric Saraswati / Arts and Music]',
        'Magha Gupt Navaratri Day 10 (Kamala Puja)' => 'Magha Gupt Navaratri (10 Mahavidyas] - Worship of Kamala (Tantric Lakshmi / Prosperity and Fertility]',
        'Sheetala Ashtami (Basoda)' => 'Worship of Goddess Sheetala for protection from diseases',
        'Papmochani Ekadashi' => 'Fasting for Papmochani Ekadashi (Liberation from Sins)',
        'Ugadi / Gudi Padwa' => 'Lunar New Year / First day of Chaitra',
        'Gangaur' => 'Worship of Gauri',
        'Yamuna Chhath / Chaiti Chhath' => 'Descent of Goddess Yamuna / Summer Chhath',
        'Rama Navami' => 'Birth anniversary of Lord Rama, seventh avatar of Vishnu',
        'Swaminarayan Jayanti (Hari-Nom)' => 'Birth of Bhagwan Swaminarayan; celebrated with assemblies, cultural programs, and devotional singing',
        'Kamada Ekadashi' => 'Fasting for Kamada Ekadashi (Fulfiller of Desires)',
        'Hanuman Jayanti' => 'Birth celebration of Lord Hanuman',
        'Varuthini Ekadashi' => 'Fasting for Varuthini Ekadashi',
        'Parashurama Jayanti' => 'Birth of Lord Parashurama',
        'Akshaya Tritiya' => 'Most auspicious for new beginnings',
        'Adi Shankaracharya Jayanti' => 'Birth anniversary of Adi Shankaracharya',
        'Ganga Saptami' => 'Rebirth of River Ganga',
        'Sita Navami' => 'Birth anniversary of Goddess Sita',
        'Mohini Ekadashi' => 'Fasting for Mohini Ekadashi',
        'Narasimha Jayanti' => 'Appearance day of Lord Narasimha',
        'Buddha Purnima' => 'Vaishakha Purnima — Hindu observance of Sugata Buddha (9th avatar of Vishnu, distinct from Gautama Buddha of Buddhism) and Kurma Jayanti (birth of Lord Vishnu)',
        'Narsinh Mehta Janma Jayanti' => 'Birth anniversary of Adi Kavi Narsinh Mehta',
        'Apara Ekadashi' => 'Fasting for Apara Ekadashi',
        'Yogi Maharaj Jayanti' => 'Birth of Brahmaswarup Yogi Maharaj',
        'Shani Jayanti / Savitri Amavasya' => 'Birth of Lord Shani / Savitri Vrat',
        'Jamai Shashti' => 'Bengali festival dedicated to son-in-laws',
        'Mahesh Navami' => 'Worship of Lord Shiva by Maheshwari community',
        'Ganga Dussehra' => 'Descent of Mother Ganga to Earth',
        'Nirjala Ekadashi' => 'Toughest Ekadashi vrat (observed without water] / Gayatri Jayanti',
        'Vat Purnima' => 'Vat Savitri observed by Purnimanta calendar',
        'Yogini Ekadashi' => 'Fasting for Yogini Ekadashi',
        'Jagannath Rath Yatra' => 'Chariot festival of Lord Jagannath',
        'Devshayani Ekadashi' => 'Chaturmas begins, Lord Vishnu sleeps',
        'Gauri Vrat (Molakat) Begins' => '5-day fast by young girls (without salt)',
        'Jaya Parvati Vrat Begins' => '5-day fast for marital bliss and good husband',
        'Guru Purnima' => 'Honoring spiritual teachers and Vyasa',
        'Kamika Ekadashi' => 'Fasting for Kamika Ekadashi',
        'Hariyali Teej' => 'Monsoon festival welcoming the rain',
        'Nag Panchami' => 'Worship of serpent deities',
        'Kalki Jayanti' => 'Birth of Kalki Avatar',
        'Tulsidas Jayanti' => 'Birth anniversary of Goswami Tulsidas',
        'Shravana Putrada Ekadashi' => 'Fasting to be blessed with a son',
        'Raksha Bandhan / Avani Avittam' => 'Brother-sister bond / Hayagriva birth / Upakarma',
        'Pola / Kushotpatini Amavasya' => 'Thanksgiving festival for farmers and bulls',
        'Aja Ekadashi' => 'Fasting for Aja Ekadashi',
        'Goga Pancham / Goga Panchami (Nag Panchami - Gujarat)' => 'Gujarati Nag Panchami honoring Goga Ji / Goga Maharaj and serpent deities',
        'Shravana Somvar (Monday Fasting)' => 'Auspicious Monday of Shravana month dedicated to Lord Shiva',
        'Kajari Teej' => 'Kajari Teej festival',
        'Bol Choth' => 'Worship of cows and calves (Bahula Chaturthi)',
        'Randhan Chhath / Balarama Jayanti (Hala Shashthi)' => 'Gujarati Randhan Chhath and the wider Hala Shashthi / Balarama Jayanti observance on Krishna Shashthi',
        'Sheetala Satam / Sheetala Saptami' => 'Sheetala Mata observance, known in Gujarat as Sheetala Satam, marked by cold-food offerings and prayers for health',
        'Krishna Janmashtami' => 'Birth celebration of Lord Krishna',
        'Hartalika Teej / Kevada Trij' => 'Hartalika Teej, known in Gujarat as Kevada Trij, observed by women in honor of Parvati and Shiva',
        'Varaha Jayanti' => 'Appearance day of Lord Varaha (Boar Avatar)',
        'Ganesh Chaturthi' => 'Birth anniversary of Lord Ganesha',
        'Rishi Panchami' => 'Worship of the Saptarishis',
        'Radha Ashtami' => 'Birth anniversary of Radha Rani',
        'Parsva Ekadashi / Jal Jhilani Ekadashi' => 'Lord Vishnu changes sides / Swaminarayan Jal Jhilani Utsav',
        'Mahant Swami Maharaj Janma Jayanti' => 'Physical birth anniversary of Mahant Swami Maharaj (13 September 1933, Bhadarva Vad 9)',
        'Mahant Swami Maharaj Parshadi Diksha Din (Official Jayanti)' => 'Official BAPS celebration of Mahant Swami Maharaj Jayanti on Parshadi Diksha Din (2 February 1957, Maha Vad 1)',
        'Vamana Jayanti' => 'Birth of Vamana Avatar',
        'Anant Chaturdashi' => 'Worship of Lord Ananta; Ganesh Visarjan',
        'Pitru Paksha Begins' => 'Beginning of the fortnight of ancestors',
        'Indira Ekadashi' => 'Fasting for Indira Ekadashi',
        'Mahalaya Amavasya' => 'Final day of Pitru Paksha (Sarvapitri Amavasya)',
        'Lalita Panchami' => 'Worship of Goddess Lalita Tripurasundari during Navaratri',
        'Dussehra / Vijayadashami' => 'Victory of Lord Rama over Ravana / End of Sharad Navaratri',
        'Papankusha Ekadashi' => 'Fasting for Papankusha Ekadashi',
        'Sharad Purnima / Manekthari Punam / Gunatitanand Swami Jayanti' => 'Sharad Purnima, known in Gujarat as Manekthari Punam, and the birth anniversary of Gunatitanand Swami',
        'Valmiki Jayanti' => 'Birth anniversary of Sage Valmiki',
        'Rama Ekadashi' => 'Fasting for Rama Ekadashi',
        'Karva Chauth' => 'Married women fast for husband long life',
        'Ahoi Ashtami' => 'Mothers fast for wellbeing of children',
        'Vagh Baras (Govatsa Dwadashi)' => 'Worship of cows and calves',
        'Dhanteras' => 'Worship of Lakshmi and Dhanvantari',
        'Kali Chaudas (Naraka Chaturdashi)' => 'Worship of Goddess Kali and victory over Narakasura',
        'Kali Puja / Diwali' => 'Festival of lights / Worship of Goddess Kali',
        'Govardhan Puja / Bestu Varas / Annakut' => 'Annakut (Swaminarayan) / Gujarati New Year',
        'Bhai Dooj' => 'Brother-sister relationship celebration',
        'Labh Pancham' => 'Auspicious day for businesses in Gujarat',
        'Skanda Shashti' => 'Six-day festival dedicated to Lord Murugan, celebrating his victory over demon Surapadman',
        'Chhath Puja (Sandhya Arghya)' => 'Major day (3rd of 4) of Chhath Puja - evening arghya to Surya; festival runs Kartika Shukla 4-7',
        'Jalaram Jayanti' => 'Birth anniversary of Saint Jalaram Bapa of Virpur',
        'Gopashtami' => 'Worship and celebration of cows',
        'Jagaddhatri Puja' => 'Worship of Goddess Jagaddhatri in Bengal',
        'Pramukh Swami Maharaj Jayanti' => 'Birth anniversary of Pramukh Swami Maharaj (7 December 1921, Magshar Sud 8, VS 1978)',
        'Devutthana (Prabodhini) Ekadashi' => 'Prabodhini Ekadashi / End of Chaturmas',
        'Tulsi Vivah' => 'Ceremonial marriage of Tulsi to Vishnu',
        'Vaikuntha Chaturdashi' => 'Sacred day for both Vishnu and Shiva worshippers',
        'Dev Diwali (Tripurari Purnima)' => 'Festival of Varanasi celebrating Shiva',
        'Karthigai Deepam' => 'Tamil festival of lights; Maha Deepam lit at Tiruvannamalai',
        'Utpanna Ekadashi' => 'Fasting for Utpanna Ekadashi',
        'Vachanamrut Jayanti' => 'Commemoration of the Vachanamrut',
        'Kalabhairav Jayanti' => 'Birth of Lord Kalabhairav (Shiva)',
        'Vivah Panchami' => 'Wedding anniversary of Rama and Sita',
        'Geeta Jayanti / Mokshada Ekadashi / Vaikunta Ekadasi' => 'Celebration of Bhagavad Gita / Gateway to Heaven',
        'Dattatreya Jayanti' => 'Birth of Dattatreya (Annapurna Jayanti)',
        'Saphala Ekadashi' => 'Fasting for Saphala Ekadashi',
        'Pausha Putrada Ekadashi' => 'Fasting for Pausha Putrada Ekadashi',
        'Shakambhari Purnima' => 'Culmination of Shakambhari Navaratri; worship of Goddess Shakambhari who nourished the world with vegetables and fruits',
        'Thai Poosam' => 'Tamil festival dedicated to Lord Murugan; observed when Pushya nakshatra coincides with Purnima in Tamil month Thai (Jan-Feb)',
        'Onam (Thiruvonam)' => 'Kerala harvest festival; Thiruvonam nakshatra (Shravana) in Malayalam month Chingam (Aug-Sep); marks King Mahabali',
        'Gunatitanand Swami Diksha Day' => 'Diksha day of Gunatitanand Swami',
        'Shattila Ekadashi' => 'Fasting for Shattila Ekadashi',
        'Mauni Amavasya' => 'Day of rigorous silence and holy bath',
        'Vasant Panchami / Shikshapatri Jayanti' => 'Worship of Goddess Saraswati / Shikshapatri presentation',
        'Ratha Saptami' => 'Surya Jayanti',
        'Bhishma Ashtami' => 'Anniversary of Bhishma Pitamah departure',
        'Jaya Ekadashi' => 'Fasting for Jaya Ekadashi',
        'Maghi Purnima / Masi Magam' => 'Kumbh Mela bathing day / Tamil holy bathing day',
        'Pushpadolotsav (Dhuleti)' => 'Festival of colors (Dhuleti/Pushpadolotsav]',
        'Vijaya Ekadashi' => 'Fasting for Vijaya Ekadashi',
        'Maha Shivaratri' => 'Great night of Lord Shiva',
        'Phulera Dooj' => 'Festival of flowers',
        'Amalaki Ekadashi' => 'Fasting for Amalaki Ekadashi',
        'Holika Dahan' => 'Bonfire ceremony, victory of good over evil',
        'Bhagatji Maharaj Jayanti' => 'Birth of Bhagatji Maharaj (Swaminarayan Sect)',
        'Holi' => 'Festival of colors',
        'Varalakshmi Vratam' => 'Worship of Goddess Lakshmi for prosperity',
        'Padmini Ekadashi' => 'Special Ekadashi occurring ONLY during Adhik Maas',
        'Parama Ekadashi' => 'Special Ekadashi occurring ONLY during Adhik Maas Krishna Paksha',
    ],
    'hi' => [
        'मेष संक्रांति (बैसाखी / पुथंडु)' => 'सौर नव वर्ष',
        'वृषभ संक्रांति' => 'सूर्य का वृषभ राशि में प्रवेश',
        'मिथुन संक्रांति' => 'सूर्य का मिथुन राशि में प्रवेश',
        'कर्क संक्रांति' => 'सूर्य का कर्क राशि में प्रवेश',
        'सिंह संक्रांति' => 'सूर्य का सिंह राशि में प्रवेश',
        'कन्या संक्रांति (विश्वकर्मा पूजा)' => 'दिव्य वास्तुकार विश्वकर्मा की पूजा',
        'तुला संक्रांति' => 'सूर्य का तुला राशि में प्रवेश',
        'वृश्चिक संक्रांति' => 'सूर्य का वृश्चिक राशि में प्रवेश',
        'धनु संक्रांति' => 'सूर्य का धनु राशि में प्रवेश',
        'मकर संक्रांति (पोंगल)' => 'फसल उत्सव, सूर्य का मकर राशि में प्रवेश',
        'कुंभ संक्रांति' => 'सूर्य का कुंभ राशि में प्रवेश',
        'मीन संक्रांति' => 'सूर्य का मीन राशि में प्रवेश',
        'वासी उत्तरायण' => 'गुजरात में पतंग उत्सव का दूसरा दिन',
        'लोहड़ी' => 'पंजाबी फसल उत्सव; शीतकालीन संक्रांति के अंत का प्रतीक अलाव उत्सव',
        'चेटी चंड' => 'सिंधी हिंदू नव वर्ष; झूलेलाल (इष्ट-देवता) का जन्म',
        'विशु' => 'केरल हिंदू नव वर्ष; मेड़म महीने का पहला दिन; विशुक्कानी सजावट',
        'शास्त्रीजी महाराज जयंती' => 'BAPS के संस्थापक शास्त्रीजी महाराज की जयंती; वसंत पंचमी के दिन',
        'प्रमुख वर्णी दिन' => 'वह दिन जब प्रमुख स्वामी महाराज को BAPS का प्रशासनिक अध्यक्ष नियुक्त किया गया था (1950)',
        'अषाढ़ी बीज' => 'कच्छी नव वर्ष; मानसून और खरीफ फसल के मौसम की शुरुआत; पारंपरिक मौसम भविष्यवाणी',
        'रवेची माता मेला' => 'रवेची माता मंदिर (रापर, कच्छ) में प्राचीन मेला; रबारी और अहीर समुदाय के हजारों भक्त इकट्ठा होते हैं',
        'तरणेतर मेला' => 'त्रिनेत्रेश्वर महादेव मंदिर में सौराष्ट्र का प्रसिद्ध मैचमेकिंग मेला; भादरवा सुद 4-6',
        'तरणेतर मेला दिन 2' => 'तरणेतर मेले का दूसरा दिन (भादरवा सुद 5)',
        'तरणेतर मेला दिन 3' => 'तरणेतर मेले का तीसरा दिन (भादरवा सुद 6)',
        'मोटा यक्ष मेला (जख बहोतेरा)' => 'ककड़भिट में कच्छ का सबसे बड़ा मेला; 72 यक्षों का सम्मान जिन्होंने स्थानीय लोगों की रक्षा की; भादरवा वद 12-14',
        'दादा मेकण मेला (ध्रांग मेला)' => 'ध्रांग गाँव में संत मेकण दादा के सम्मान में मेला, जिन्होंने कच्छ के रण में भटके हुए यात्रियों को बचाया था',
        'रंग पंचमी' => 'होली उत्सव का पांचवां दिन; रंगों के खेल की निरंतरता; विशेषकर महाराष्ट्र और मध्य प्रदेश में मनाया जाता है',
        'चैत्र (वसंत) नवरात्रि दिन 1 (शैलपुत्री पूजा)' => 'चैत्र (वसंत) नवरात्रि - शैलपुत्री (पर्वत की पुत्री) की पूजा',
        'चैत्र (वसंत) नवरात्रि दिन 2 (ब्रह्मचारिणी पूजा)' => 'चैत्र (वसंत) नवरात्रि - ब्रह्मचारिणी (तपस्विनी) की पूजा',
        'चैत्र (वसंत) नवरात्रि दिन 3 (चंद्रघंटा पूजा)' => 'चैत्र (वसंत) नवरात्रि - चंद्रघंटा (चंद्रमा रूपी घंटा धारण करने वाली) की पूजा',
        'चैत्र (वसंत) नवरात्रि दिन 4 (कूष्मांडा पूजा)' => 'चैत्र (वसंत) नवरात्रि - कूष्मांडा (ब्रह्मांडीय अंडे की रचयिता) की पूजा',
        'चैत्र (वसंत) नवरात्रि दिन 5 (स्कंदमाता पूजा)' => 'चैत्र (वसंत) नवरात्रि - स्कंदमाता (स्कंद की माता) की पूजा',
        'चैत्र (वसंत) नवरात्रि दिन 6 (कात्यायनी पूजा)' => 'चैत्र (वसंत) नवरात्रि - कात्यायनी (योद्धा देवी) की पूजा',
        'चैत्र (वसंत) नवरात्रि दिन 7 (कालरात्रि पूजा)' => 'चैत्र (वसंत) नवरात्रि - कालरात्रि (भयंकर रात) की पूजा / महा सप्तमी',
        'चैत्र (वसंत) नवरात्रि दिन 8 (महागौरी पूजा)' => 'चैत्र (वसंत) नवरात्रि - महागौरी (महान श्वेत देवी) की पूजा / महा अष्टमी',
        'चैत्र (वसंत) नवरात्रि दिन 9 (सिद्धिदात्री पूजा)' => 'चैत्र (वसंत) नवरात्रि - सिद्धिदात्री (अलौकिक शक्तियों की दाता) की पूजा / महा नवमी',
        'अश्विन शरद नवरात्रि दिन 1 (शैलपुत्री पूजा)' => 'अश्विन शरद नवरात्रि - शैलपुत्री (पर्वत की पुत्री) की पूजा',
        'अश्विन शरद नवरात्रि दिन 2 (ब्रह्मचारिणी पूजा)' => 'अश्विन शरद नवरात्रि - ब्रह्मचारिणी (तपस्विनी) की पूजा',
        'अश्विन शरद नवरात्रि दिन 3 (चंद्रघंटा पूजा)' => 'अश्विन शरद नवरात्रि - चंद्रघंटा (चंद्रमा रूपी घंटा धारण करने वाली) की पूजा',
        'अश्विन शरद नवरात्रि दिन 4 (कूष्मांडा पूजा)' => 'अश्विन शरद नवरात्रि - कूष्मांडा (ब्रह्मांडीय अंडे की रचयिता) की पूजा',
        'अश्विन शरद नवरात्रि दिन 5 (स्कंदमाता पूजा)' => 'अश्विन शरद नवरात्रि - स्कंदमाता (स्कंद की माता) की पूजा',
        'अश्विन शरद नवरात्रि दिन 6 (कात्यायनी पूजा)' => 'अश्विन शरद नवरात्रि - कात्यायनी (योद्धा देवी) की पूजा',
        'अश्विन शरद नवरात्रि दिन 7 (कालरात्रि पूजा)' => 'अश्विन शरद नवरात्रि - कालरात्रि (भयंकर रात) की पूजा / महा सप्तमी',
        'दुर्गा अष्टमी (महागौरी पूजा)' => 'अश्विन शरद नवरात्रि - महागौरी (महान श्वेत देवी) की पूजा / महा अष्टमी',
        'महा नवमी (सिद्धिदात्री पूजा)' => 'अश्विन शरद नवरात्रि - सिद्धिदात्री (अलौकिक शक्तियों की दाता) की पूजा / महा नवमी',
        'आषाढ़ गुप्त नवरात्रि दिन 1 (काली पूजा)' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - काली (समय की संहारक) की पूजा',
        'आषाढ़ गुप्त नवरात्रि दिन 2 (तारा पूजा)' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - तारा (रक्षक और मार्गदर्शक) की पूजा',
        'आषाढ़ गुप्त नवरात्रि दिन 3 (त्रिपुर सुंदरी पूजा)' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - त्रिपुर सुंदरी / षोडशी (तीनों लोकों की सुंदरी) की पूजा',
        'आषाढ़ गुप्त नवरात्रि दिन 4 (भुवनेश्वरी पूजा)' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - भुवनेश्वरी (ब्रह्मांड की देवी) की पूजा',
        'आषाढ़ गुप्त नवरात्रि दिन 5 (भैरवी पूजा)' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - भैरवी (विनाश और पुनर्जन्म की भयंकर देवी) की पूजा',
        'आषाढ़ गुप्त नवरात्रि दिन 6 (छिन्नमस्ता पूजा)' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - छिन्नमस्ता (स्वयं का सिर काटने वाली देवी) की पूजा',
        'आषाढ़ गुप्त नवरात्रि दिन 7 (धूमावती पूजा)' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - धूमावती (विधवा देवी) की पूजा',
        'आषाढ़ गुप्त नवरात्रि दिन 8 (बगलामुखी पूजा)' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - बगलामुखी (शत्रुओं को पंगु करने वाली) की पूजा',
        'आषाढ़ गुप्त नवरात्रि दिन 9 (मातंगी पूजा)' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - मातंगी (तांत्रिक सरस्वती / कला और संगीत) की पूजा',
        'आषाढ़ गुप्त नवरात्रि दिन 10 (कमला पूजा)' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - कमला (तांत्रिक लक्ष्मी / समृद्धि और उर्वरता) की पूजा',
        'माघ गुप्त नवरात्रि दिन 1 (काली पूजा)' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - काली (समय की संहारक) की पूजा',
        'माघ गुप्त नवरात्रि दिन 2 (तारा पूजा)' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - तारा (रक्षक और मार्गदर्शक) की पूजा',
        'माघ गुप्त नवरात्रि दिन 3 (त्रिपुर सुंदरी पूजा)' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - त्रिपुर सुंदरी / षोडशी (तीनों लोकों की सुंदरी) की पूजा',
        'माघ गुप्त नवरात्रि दिन 4 (भुवनेश्वरी पूजा)' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - भुवनेश्वरी (ब्रह्मांड की देवी) की पूजा',
        'माघ गुप्त नवरात्रि दिन 5 (भैरवी पूजा)' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - भैरवी (विनाश और पुनर्जन्म की भयंकर देवी) की पूजा',
        'माघ गुप्त नवरात्रि दिन 6 (छिन्नमस्ता पूजा)' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - छिन्नमस्ता (स्वयं का सिर काटने वाली देवी) की पूजा',
        'माघ गुप्त नवरात्रि दिन 7 (धूमावती पूजा)' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - धूमावती (विधवा देवी) की पूजा',
        'माघ गुप्त नवरात्रि दिन 8 (बगलामुखी पूजा)' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - बगलामुखी (शत्रुओं को पंगु करने वाली) की पूजा',
        'माघ गुप्त नवरात्रि दिन 9 (मातंगी पूजा)' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - मातंगी (तांत्रिक सरस्वती / कला और संगीत) की पूजा',
        'माघ गुप्त नवरात्रि दिन 10 (कमला पूजा)' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - कमला (तांत्रिक लक्ष्मी / समृद्धि और उर्वरता) की पूजा',
        'शीतला अष्टमी (बसोड़ा)' => 'बीमारियों से बचाव के लिए देवी शीतला की पूजा',
        'पापमोचनी एकादशी' => 'पापमोचनी एकादशी के लिए व्रत (पापों से मुक्ति)',
        'उगादी / गुड़ी पड़वा' => 'चंद्र नव वर्ष / चैत्र का पहला दिन',
        'गणगौर' => 'गौरी की पूजा',
        'यमुना छठ / चैती छठ' => 'देवी यमुना का अवतरण / ग्रीष्मकालीन छठ',
        'राम नवमी' => 'भगवान राम (विष्णु के सातवें अवतार) की जयंती',
        'स्वामीनारायण जयंती (हरि-नोम)' => 'भगवान स्वामीनारायण का जन्म; सभाओं, सांस्कृतिक कार्यक्रमों और भजन गायन के साथ मनाया जाता है',
        'कामदा एकादशी' => 'कामदा एकादशी के लिए व्रत (इच्छाओं की पूर्ति करने वाली)',
        'हनुमान जयंती' => 'भगवान हनुमान का जन्मोत्सव',
        'वरुथिनी एकादशी' => 'वरुथिनी एकादशी के लिए व्रत',
        'परशुराम जयंती' => 'भगवान परशुराम का जन्म',
        'अक्षय तृतीया' => 'नई शुरुआत के लिए सबसे शुभ दिन',
        'आदि शंकराचार्य जयंती' => 'आदि शंकराचार्य की जयंती',
        'गंगा सप्तमी' => 'गंगा नदी का पुनर्जन्म',
        'सीता नवमी' => 'देवी सीता की जयंती',
        'मोहिनी एकादशी' => 'मोहिनी एकादशी के लिए व्रत',
        'नरसिंह जयंती' => 'भगवान नरसिंह का प्राकट्य दिवस',
        'बुद्ध पूर्णिमा' => 'वैशाख पूर्णिमा — सुगत बुद्ध (विष्णु के 9वें अवतार, बौद्ध धर्म के गौतम बुद्ध से अलग) और कूर्म जयंती (भगवान विष्णु के कछुए अवतार का जन्म) का हिंदू पर्व। भागवत पुराण 1.3.24 और अग्नि पुराण में हिंदू बुद्ध-अवतार का वर्णन कीकट/गया में राक्षसों को वैदिक अनुष्ठानों से भ्रमित करने (भागवत दृष्टिकोण) या करुणा सिखाने और पशु बलि को समाप्त करने (जयदेव का गीत गोविंद दृष्टिकोण) के लिए प्रकट होने के रूप में किया गया है। पुरी के शंकराचार्य स्वामी निश्चलानंद सरस्वती और विद्वान इन्हें दो अलग-अलग व्यक्तियों के रूप में मान्यता देते हैं: पौराणिक सुगत बुद्ध (ब्राह्मण वर्ण, वेदों का समर्थन, प्राचीन समयरेखा) बनाम गौतम बुद्ध (क्षत्रिय शाक्य वंश, लुंबिनी जन्म ~563 ईसा पूर्व, वेदों को अस्वीकार किया)। यह दिन कूर्म जयंती के साथ भी मेल खाता है और सत्यनारायण पूजा के लिए सबसे शुभ दिन है। क्षेत्रीय भिन्नता: ओडिशा और बंगाल की परंपराओं में दशावतार में 9वें अवतार के रूप में बुद्ध की जगह बलराम को रखा गया है।',
        'नरसिंह मेहता जन्म जयंती' => 'आदि कवि नरसिंह मेहता की जयंती',
        'अपरा एकादशी' => 'अपरा एकादशी के लिए व्रत',
        'योगी महाराज जयंती' => 'ब्रह्मस्वरूप योगी महाराज का जन्म',
        'शनि जयंती / सावित्री अमावस्या' => 'भगवान शनि का जन्म / सावित्री व्रत',
        'जामाइ षष्ठी' => 'दामाद को समर्पित बंगाली त्योहार',
        'महेश नवमी' => 'माहेश्वरी समाज द्वारा भगवान शिव की पूजा',
        'गंगा दशहरा' => 'पृथ्वी पर माता गंगा का अवतरण',
        'निर्जला एकादशी' => 'सबसे कठिन एकादशी व्रत (बिना जल के किया जाने वाला) / गायत्री जयंती',
        'वट पूर्णिमा' => 'पूर्णिमान्त कैलेंडर के अनुसार वट सावित्री व्रत',
        'योगिनी एकादशी' => 'योगिनी एकादशी के लिए व्रत',
        'जगन्नाथ रथ यात्रा' => 'भगवान जगन्नाथ का रथ उत्सव',
        'देवशयनी एकादशी' => 'चातुर्मास आरंभ, भगवान विष्णु योगनिद्रा में जाते हैं',
        'गौरी व्रत (मोलाकत) प्रारंभ' => 'छोटी कन्याओं द्वारा 5 दिवसीय व्रत (बिना नमक का)',
        'जया पार्वती व्रत प्रारंभ' => 'वैवाहिक सुख और अच्छे पति के लिए 5 दिवसीय व्रत',
        'गुरु पूर्णिमा' => 'आध्यात्मिक गुरुओं और महर्षि व्यास का सम्मान',
        'कामिका एकादशी' => 'कामिका एकादशी के लिए व्रत',
        'हरियाली तीज' => 'बारिश का स्वागत करने वाला मानसून त्योहार',
        'नाग पंचमी' => 'सर्प देवताओं की पूजा',
        'कल्कि जयंती' => 'कल्कि अवतार का जन्म',
        'तुलसीदास जयंती' => 'गोस्वामी तुलसीदास की जयंती',
        'श्रावण पुत्रदा एकादशी' => 'पुत्र प्राप्ति के लिए व्रत',
        'रक्षा बंधन / अवनी अवित्तम' => 'भाई-बहन का बंधन / हयग्रीव जन्म / उपाकर्म',
        'पोला / कुशोत्पाटिनी अमावस्या' => 'किसानों और बैलों के लिए धन्यवाद उत्सव',
        'अजा एकादशी' => 'अजा एकादशी के लिए व्रत',
        'गोगा पंचम / गोगा पंचमी (नाग पंचमी - गुजरात)' => 'गोगा जी / गोगा महाराज और सर्प देवताओं का सम्मान करने वाली गुजराती नाग पंचमी',
        'श्रावण सोमवार (सोमवार व्रत)' => 'भगवान शिव को समर्पित श्रावण मास का शुभ सोमवार',
        'कजरी तीज' => 'कजरी तीज उत्सव',
        'बोल चौथ' => 'गायों और बछड़ों की पूजा (बहुला चतुर्थी)',
        'रांधण छठ / बलराम जयंती (हल षष्ठी)' => 'गुजराती रांधण छठ और कृष्ण षष्ठी पर व्यापक हल षष्ठी / बलराम जयंती का पर्व',
        'शीतला सातम / शीतला सप्तमी' => 'शीतला माता का पर्व, जिसे गुजरात में शीतला सातम के रूप में जाना जाता है, स्वास्थ्य के लिए प्रार्थना और ठंडे भोजन के प्रसाद द्वारा मनाया जाता है',
        'कृष्ण जन्माष्टमी' => 'भगवान कृष्ण का जन्मोत्सव',
        'हरतालिका तीज / केवड़ा त्रीज' => 'हरतालिका तीज, जिसे गुजरात में केवड़ा त्रीज के नाम से जाना जाता है, महिलाओं द्वारा पार्वती और शिव के सम्मान में मनाया जाता है',
        'वराह जयंती' => 'भगवान वराह का प्राकट्य दिवस',
        'गणेश चतुर्थी' => 'भगवान गणेश की जयंती',
        'ऋषि पंचमी' => 'सप्तर्षियों की पूजा',
        'राधा अष्टमी' => 'राधारानी की जयंती',
        'पार्श्व एकादशी / जल झिलानी एकादशी' => 'भगवान विष्णु करवट बदलते हैं / स्वामीनारायण जल झिलानी उत्सव',
        'महंत स्वामी महाराज जन्म जयंती' => 'महंत स्वामी महाराज का भौतिक जन्म दिवस (13 सितंबर 1933, भादरवा वद 9)',
        'महंत स्वामी महाराज पार्षदी दीक्षा दिन (आधिकारिक जयंती)' => 'पार्षदी दीक्षा दिन (2 फरवरी 1957, महा वद 1) पर महंत स्वामी महाराज जयंती का आधिकारिक BAPS उत्सव',
        'वामन जयंती' => 'वामन अवतार का जन्म',
        'अनंत चतुर्दशी' => 'भगवान अनंत की पूजा; गणेश विसर्जन',
        'पितृ पक्ष प्रारंभ' => 'पूर्वजों के पखवाड़े की शुरुआत',
        'इन्दिरा एकादशी' => 'इन्दिरा एकादशी के लिए व्रत',
        'महालय अमावस्या' => 'पितृ पक्ष का अंतिम दिन (सर्वपित्री अमावस्या)',
        'ललिता पंचमी' => 'नवरात्रि के दौरान देवी ललिता त्रिपुरसुंदरी की पूजा',
        'दशहरा / विजयदशमी' => 'रावण पर भगवान राम की जीत / शरद नवरात्रि का समापन',
        'पापांकुशा एकादशी' => 'पापांकुशा एकादशी के लिए व्रत',
        'शरद पूर्णिमा / माणेकठारी पूनम / गुणातीतानंद स्वामी जयंती' => 'शरद पूर्णिमा, जिसे गुजरात में माणेकठारी पूनम के रूप में जाना जाता है, और गुणातीतानंद स्वामी की जयंती',
        'वाल्मीकि जयंती' => 'महर्षि वाल्मीकि की जयंती',
        'रमा एकादशी' => 'रमा एकादशी के लिए व्रत',
        'करवा चौथ' => 'विवाहित महिलाएं पति की लंबी उम्र के लिए व्रत रखती हैं',
        'अहोई अष्टमी' => 'माताएं बच्चों की भलाई के लिए व्रत रखती हैं',
        'वाघ बारस (गोवत्स द्वादशी)' => 'गायों और बछड़ों की पूजा',
        'धनतेरस' => 'लक्ष्मी और धन्वंतरि की पूजा',
        'काली चौदस (नरक चतुर्दशी)' => 'देवी काली की पूजा और नरकासुर पर विजय',
        'काली पूजा / दिवाली' => 'रोशनी का त्योहार / देवी काली की पूजा',
        'गोवर्धन पूजा / बेस्तु वरस / अन्नकूट' => 'अन्नकूट (स्वामीनारायण) / गुजराती नव वर्ष',
        'भाई दूज' => 'भाई-बहन के रिश्ते का उत्सव',
        'लाभ पंचम' => 'गुजरात में व्यवसायों के लिए शुभ दिन',
        'स्कंद षष्ठी' => 'भगवान मुरुगन को समर्पित छह दिवसीय उत्सव, राक्षस सूरपद्मन पर उनकी जीत का जश्न',
        'छठ पूजा (संध्या अर्घ्य)' => 'छठ पूजा का प्रमुख दिन (4 में से तीसरा) - सूर्य को संध्या अर्घ्य; पर्व कार्तिक शुक्ल 4-7 तक चलता है',
        'जलाराम जयंती' => 'वीरपुर के संत जलाराम बापा की जयंती',
        'गोपाष्टमी' => 'गायों की पूजा और उत्सव',
        'जगद्धात्री पूजा' => 'बंगाल में देवी जगद्धात्री की पूजा',
        'प्रमुख स्वामी महाराज जयंती' => 'प्रमुख स्वामी महाराज की जयंती (7 दिसंबर 1921, मगशर सुद 8, विक्रम संवत 1978)',
        'देवोत्थान (प्रबोधिनी) एकादशी' => 'प्रबोधिनी एकादशी / चातुर्मास का समापन',
        'तुलसी विवाह' => 'तुलसी और शालिग्राम (विष्णु) का औपचारिक विवाह',
        'वैकुंठ चतुर्दशी' => 'विष्णु और शिव दोनों के भक्तों के लिए पवित्र दिन',
        'देव दिवाली (त्रिपुरारी पूर्णिमा)' => 'त्रिपुरासुर पर शिव की जीत का जश्न मनाने वाला वाराणसी का त्योहार; घाटों को दीयों से रोशन किया जाता है',
        'कार्तिगई दीपम' => 'रोशनी का तमिल त्योहार; तिरुवन्नामलाई में महा दीपम जलाया जाता है',
        'उत्पन्ना एकादशी' => 'उत्पन्ना एकादशी के लिए व्रत',
        'वचनामृत जयंती' => 'वचनामृत का स्मरणोत्सव',
        'कालभैरव जयंती' => 'भगवान कालभैरव (शिव) का जन्म',
        'विवाह पंचमी' => 'राम और सीता की विवाह वर्षगांठ',
        'गीता जयंती / मोक्षदा एकादशी / वैकुंठ एकादशी' => 'भगवद गीता का उत्सव / मोक्ष का द्वार',
        'दत्तात्रेय जयंती' => 'भगवान दत्तात्रेय का जन्म (अन्नपूर्णा जयंती)',
        'सफला एकादशी' => 'सफला एकादशी के लिए व्रत',
        'पौष पुत्रदा एकादशी' => 'पौष पुत्रदा एकादशी के लिए व्रत',
        'शाकंभरी पूर्णिमा' => 'शाकंभरी नवरात्रि का समापन; देवी शाकंभरी की पूजा जिन्होंने सब्जियों और फलों से दुनिया का पोषण किया',
        'थाई पूसम' => 'भगवान मुरुगन को समर्पित तमिल त्योहार; यह तब मनाया जाता है जब तमिल महीने थाई (जनवरी-फरवरी) में पुष्य नक्षत्र पूर्णिमा के साथ मेल खाता है',
        'ओणम (तिरुवोणम)' => 'केरल का फसल उत्सव; मलयालम महीने चिंगम (अगस्त-सितंबर) में तिरुवोणम नक्षत्र (श्रवण); राजा महाबली की वार्षिक यात्रा का प्रतीक है',
        'गुणातीतानंद स्वामी दीक्षा दिन' => 'गुणातीतानंद स्वामी का दीक्षा दिवस',
        'षटतिला एकादशी' => 'षटतिला एकादशी के लिए व्रत',
        'मौनी अमावस्या' => 'कठोर मौन व्रत और पवित्र स्नान का दिन',
        'वसंत पंचमी / शिक्षापत्री जयंती' => 'देवी सरस्वती की पूजा / शिक्षापत्री जयंती',
        'रथ सप्तमी' => 'सूर्य जयंती',
        'भीष्म अष्टमी' => 'भीष्म पितामह के प्रस्थान की वर्षगांठ',
        'जया एकादशी' => 'जया एकादशी के लिए व्रत',
        'माघी पूर्णिमा / मासी मगम' => 'कुंभ मेला स्नान का दिन / तमिल पवित्र स्नान दिवस',
        'पुष्पदोलोत्सव (धुलेटी)' => 'रंगों का त्योहार (धुलेटी/पुष्पदोलोत्सव)',
        'विजया एकादशी' => 'विजया एकादशी के लिए व्रत',
        'महा शिवरात्रि' => 'भगवान शिव की महान रात्रि',
        'फुलेरा दूज' => 'फूलों का त्योहार',
        'आमलकी एकादशी' => 'आमलकी एकादशी के लिए व्रत',
        'होलिका दहन' => 'अलाव समारोह, बुराई पर अच्छाई की जीत',
        'भगतजी महाराज जयंती' => 'भगतजी महाराज का जन्म (स्वामीनारायण संप्रदाय)',
        'होली' => 'रंगों का त्योहार',
        'वरलक्ष्मी व्रतम' => 'समृद्धि के लिए देवी लक्ष्मी की पूजा',
        'पद्मिनी एकादशी' => 'विशेष एकादशी जो केवल अधिक मास के दौरान आती है',
        'परमा एकादशी' => 'विशेष एकादशी जो केवल अधिक मास के कृष्ण पक्ष में आती है',
    ],
    'gu' => [
        'मेष संक्रांति (बैसाखी / पुथंडु)' => 'सौर नव वर्ष',
        'वृषभ संक्रांति' => 'सूर्य का वृषभ राशि में प्रवेश',
        'मिथुन संक्रांति' => 'सूर्य का मिथुन राशि में प्रवेश',
        'कर्क संक्रांति' => 'सूर्य का कर्क राशि में प्रवेश',
        'सिंह संक्रांति' => 'सूर्य का सिंह राशि में प्रवेश',
        'कन्या संक्रांति (विश्वकर्मा पूजा)' => 'दिव्य वास्तुकार विश्वकर्मा की पूजा',
        'तुला संक्रांति' => 'सूर्य का तुला राशि में प्रवेश',
        'वृश्चिक संक्रांति' => 'सूर्य का वृश्चिक राशि में प्रवेश',
        'धनु संक्रांति' => 'सूर्य का धनु राशि में प्रवेश',
        'मकर संक्रांति (पोंगल)' => 'फसल उत्सव, सूर्य का मकर राशि में प्रवेश',
        'कुंभ संक्रांति' => 'सूर्य का कुंभ राशि में प्रवेश',
        'मीन संक्रांति' => 'सूर्य का मीन राशि में प्रवेश',
        'वासी उत्तरायण' => 'गुजरात में पतंग उत्सव का दूसरा दिन',
        'लोहड़ी' => 'पंजाबी फसल उत्सव; शीतकालीन संक्रांति के अंत का प्रतीक अलाव उत्सव',
        'चेटी चंड' => 'सिंधी हिंदू नव वर्ष; झूलेलाल (इष्ट-देवता) का जन्म',
        'विशु' => 'केरल हिंदू नव वर्ष; मेड़म महीने का पहला दिन; विशुक्कानी सजावट',
        'शास्त्रीजी महाराज जयंती' => 'BAPS के संस्थापक शास्त्रीजी महाराज की जयंती; वसंत पंचमी के दिन',
        'प्रमुख वर्णी दिन' => 'वह दिन जब प्रमुख स्वामी महाराज को BAPS का प्रशासनिक अध्यक्ष नियुक्त किया गया था (1950)',
        'अषाढ़ी बीज' => 'कच्छी नव वर्ष; मानसून और खरीफ फसल के मौसम की शुरुआत; पारंपरिक मौसम भविष्यवाणी',
        'रवेची माता मेला' => 'रवेची माता मंदिर (रापर, कच्छ) में प्राचीन मेला; रबारी और अहीर समुदाय के हजारों भक्त इकट्ठा होते हैं',
        'तरणेतर मेला' => 'त्रिनेत्रेश्वर महादेव मंदिर में सौराष्ट्र का प्रसिद्ध मैचमेकिंग मेला; भादरवा सुद 4-6',
        'तरणेतर मेला दिन 2' => 'तरणेतर मेले का दूसरा दिन (भादरवा सुद 5)',
        'तरणेतर मेला दिन 3' => 'तरणेतर मेले का तीसरा दिन (भादरवा सुद 6)',
        'मोटा यक्ष मेला (जख बहोतेरा)' => 'ककड़भिट में कच्छ का सबसे बड़ा मेला; 72 यक्षों का सम्मान जिन्होंने स्थानीय लोगों की रक्षा की; भादरवा वद 12-14',
        'दादा मेकण मेला (ध्रांग मेला)' => 'ध्रांग गाँव में संत मेकण दादा के सम्मान में मेला, जिन्होंने कच्छ के रण में भटके हुए यात्रियों को बचाया था',
        'रंग पंचमी' => 'होली उत्सव का पांचवां दिन; रंगों के खेल की निरंतरता; विशेषकर महाराष्ट्र और मध्य प्रदेश में मनाया जाता है',
        'चैत्र (वसंत) नवरात्रि दिन 1 (शैलपुत्री पूजा)' => 'चैत्र (वसंत) नवरात्रि - शैलपुत्री (पर्वत की पुत्री) की पूजा',
        'चैत्र (वसंत) नवरात्रि दिन 2 (ब्रह्मचारिणी पूजा)' => 'चैत्र (वसंत) नवरात्रि - ब्रह्मचारिणी (तपस्विनी) की पूजा',
        'चैत्र (वसंत) नवरात्रि दिन 3 (चंद्रघंटा पूजा)' => 'चैत्र (वसंत) नवरात्रि - चंद्रघंटा (चंद्रमा रूपी घंटा धारण करने वाली) की पूजा',
        'चैत्र (वसंत) नवरात्रि दिन 4 (कूष्मांडा पूजा)' => 'चैत्र (वसंत) नवरात्रि - कूष्मांडा (ब्रह्मांडीय अंडे की रचयिता) की पूजा',
        'चैत्र (वसंत) नवरात्रि दिन 5 (स्कंदमाता पूजा)' => 'चैत्र (वसंत) नवरात्रि - स्कंदमाता (स्कंद की माता) की पूजा',
        'चैत्र (वसंत) नवरात्रि दिन 6 (कात्यायनी पूजा)' => 'चैत्र (वसंत) नवरात्रि - कात्यायनी (योद्धा देवी) की पूजा',
        'चैत्र (वसंत) नवरात्रि दिन 7 (कालरात्रि पूजा)' => 'चैत्र (वसंत) नवरात्रि - कालरात्रि (भयंकर रात) की पूजा / महा सप्तमी',
        'चैत्र (वसंत) नवरात्रि दिन 8 (महागौरी पूजा)' => 'चैत्र (वसंत) नवरात्रि - महागौरी (महान श्वेत देवी) की पूजा / महा अष्टमी',
        'चैत्र (वसंत) नवरात्रि दिन 9 (सिद्धिदात्री पूजा)' => 'चैत्र (वसंत) नवरात्रि - सिद्धिदात्री (अलौकिक शक्तियों की दाता) की पूजा / महा नवमी',
        'अश्विन शरद नवरात्रि दिन 1 (शैलपुत्री पूजा)' => 'अश्विन शरद नवरात्रि - शैलपुत्री (पर्वत की पुत्री) की पूजा',
        'अश्विन शरद नवरात्रि दिन 2 (ब्रह्मचारिणी पूजा)' => 'अश्विन शरद नवरात्रि - ब्रह्मचारिणी (तपस्विनी) की पूजा',
        'अश्विन शरद नवरात्रि दिन 3 (चंद्रघंटा पूजा)' => 'अश्विन शरद नवरात्रि - चंद्रघंटा (चंद्रमा रूपी घंटा धारण करने वाली) की पूजा',
        'अश्विन शरद नवरात्रि दिन 4 (कूष्मांडा पूजा)' => 'अश्विन शरद नवरात्रि - कूष्मांडा (ब्रह्मांडीय अंडे की रचयिता) की पूजा',
        'अश्विन शरद नवरात्रि दिन 5 (स्कंदमाता पूजा)' => 'अश्विन शरद नवरात्रि - स्कंदमाता (स्कंद की माता) की पूजा',
        'अश्विन शरद नवरात्रि दिन 6 (कात्यायनी पूजा)' => 'अश्विन शरद नवरात्रि - कात्यायनी (योद्धा देवी) की पूजा',
        'अश्विन शरद नवरात्रि दिन 7 (कालरात्रि पूजा)' => 'अश्विन शरद नवरात्रि - कालरात्रि (भयंकर रात) की पूजा / महा सप्तमी',
        'दुर्गा अष्टमी (महागौरी पूजा)' => 'अश्विन शरद नवरात्रि - महागौरी (महान श्वेत देवी) की पूजा / महा अष्टमी',
        'महा नवमी (सिद्धिदात्री पूजा)' => 'अश्विन शरद नवरात्रि - सिद्धिदात्री (अलौकिक शक्तियों की दाता) की पूजा / महा नवमी',
        'आषाढ़ गुप्त नवरात्रि दिन 1 (काली पूजा)' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - काली (समय की संहारक) की पूजा',
        'आषाढ़ गुप्त नवरात्रि दिन 2 (तारा पूजा)' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - तारा (रक्षक और मार्गदर्शक) की पूजा',
        'आषाढ़ गुप्त नवरात्रि दिन 3 (त्रिपुर सुंदरी पूजा)' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - त्रिपुर सुंदरी / षोडशी (तीनों लोकों की सुंदरी) की पूजा',
        'आषाढ़ गुप्त नवरात्रि दिन 4 (भुवनेश्वरी पूजा)' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - भुवनेश्वरी (ब्रह्मांड की देवी) की पूजा',
        'आषाढ़ गुप्त नवरात्रि दिन 5 (भैरवी पूजा)' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - भैरवी (विनाश और पुनर्जन्म की भयंकर देवी) की पूजा',
        'आषाढ़ गुप्त नवरात्रि दिन 6 (छिन्नमस्ता पूजा)' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - छिन्नमस्ता (स्वयं का सिर काटने वाली देवी) की पूजा',
        'आषाढ़ गुप्त नवरात्रि दिन 7 (धूमावती पूजा)' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - धूमावती (विधवा देवी) की पूजा',
        'आषाढ़ गुप्त नवरात्रि दिन 8 (बगलामुखी पूजा)' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - बगलामुखी (शत्रुओं को पंगु करने वाली) की पूजा',
        'आषाढ़ गुप्त नवरात्रि दिन 9 (मातंगी पूजा)' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - मातंगी (तांत्रिक सरस्वती / कला और संगीत) की पूजा',
        'आषाढ़ गुप्त नवरात्रि दिन 10 (कमला पूजा)' => 'आषाढ़ गुप्त नवरात्रि (10 महाविद्याएं) - कमला (तांत्रिक लक्ष्मी / समृद्धि और उर्वरता) की पूजा',
        'माघ गुप्त नवरात्रि दिन 1 (काली पूजा)' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - काली (समय की संहारक) की पूजा',
        'माघ गुप्त नवरात्रि दिन 2 (तारा पूजा)' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - तारा (रक्षक और मार्गदर्शक) की पूजा',
        'माघ गुप्त नवरात्रि दिन 3 (त्रिपुर सुंदरी पूजा)' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - त्रिपुर सुंदरी / षोडशी (तीनों लोकों की सुंदरी) की पूजा',
        'माघ गुप्त नवरात्रि दिन 4 (भुवनेश्वरी पूजा)' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - भुवनेश्वरी (ब्रह्मांड की देवी) की पूजा',
        'माघ गुप्त नवरात्रि दिन 5 (भैरवी पूजा)' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - भैरवी (विनाश और पुनर्जन्म की भयंकर देवी) की पूजा',
        'माघ गुप्त नवरात्रि दिन 6 (छिन्नमस्ता पूजा)' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - छिन्नमस्ता (स्वयं का सिर काटने वाली देवी) की पूजा',
        'माघ गुप्त नवरात्रि दिन 7 (धूमावती पूजा)' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - धूमावती (विधवा देवी) की पूजा',
        'माघ गुप्त नवरात्रि दिन 8 (बगलामुखी पूजा)' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - बगलामुखी (शत्रुओं को पंगु करने वाली) की पूजा',
        'माघ गुप्त नवरात्रि दिन 9 (मातंगी पूजा)' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - मातंगी (तांत्रिक सरस्वती / कला और संगीत) की पूजा',
        'माघ गुप्त नवरात्रि दिन 10 (कमला पूजा)' => 'माघ गुप्त नवरात्रि (10 महाविद्याएं) - कमला (तांत्रिक लक्ष्मी / समृद्धि और उर्वरता) की पूजा',
        'शीतला अष्टमी (बसोड़ा)' => 'बीमारियों से बचाव के लिए देवी शीतला की पूजा',
        'पापमोचनी एकादशी' => 'पापमोचनी एकादशी के लिए व्रत (पापों से मुक्ति)',
        'उगादी / गुड़ी पड़वा' => 'चंद्र नव वर्ष / चैत्र का पहला दिन',
        'गणगौर' => 'गौरी की पूजा',
        'यमुना छठ / चैती छठ' => 'देवी यमुना का अवतरण / ग्रीष्मकालीन छठ',
        'राम नवमी' => 'भगवान राम (विष्णु के सातवें अवतार) की जयंती',
        'स्वामीनारायण जयंती (हरि-नोम)' => 'भगवान स्वामीनारायण का जन्म; सभाओं, सांस्कृतिक कार्यक्रमों और भजन गायन के साथ मनाया जाता है',
        'कामदा एकादशी' => 'कामदा एकादशी के लिए व्रत (इच्छाओं की पूर्ति करने वाली)',
        'हनुमान जयंती' => 'भगवान हनुमान का जन्मोत्सव',
        'वरुथिनी एकादशी' => 'वरुथिनी एकादशी के लिए व्रत',
        'परशुराम जयंती' => 'भगवान परशुराम का जन्म',
        'अक्षय तृतीया' => 'नई शुरुआत के लिए सबसे शुभ दिन',
        'आदि शंकराचार्य जयंती' => 'आदि शंकराचार्य की जयंती',
        'गंगा सप्तमी' => 'गंगा नदी का पुनर्जन्म',
        'सीता नवमी' => 'देवी सीता की जयंती',
        'मोहिनी एकादशी' => 'मोहिनी एकादशी के लिए व्रत',
        'नरसिंह जयंती' => 'भगवान नरसिंह का प्राकट्य दिवस',
        'बुद्ध पूर्णिमा' => 'वैशाख पूर्णिमा — सुगत बुद्ध (विष्णु के 9वें अवतार, बौद्ध धर्म के गौतम बुद्ध से अलग) और कूर्म जयंती (भगवान विष्णु के कछुए अवतार का जन्म) का हिंदू पर्व। भागवत पुराण 1.3.24 और अग्नि पुराण में हिंदू बुद्ध-अवतार का वर्णन कीकट/गया में राक्षसों को वैदिक अनुष्ठानों से भ्रमित करने (भागवत दृष्टिकोण) या करुणा सिखाने और पशु बलि को समाप्त करने (जयदेव का गीत गोविंद दृष्टिकोण) के लिए प्रकट होने के रूप में किया गया है। पुरी के शंकराचार्य स्वामी निश्चलानंद सरस्वती और विद्वान इन्हें दो अलग-अलग व्यक्तियों के रूप में मान्यता देते हैं: पौराणिक सुगत बुद्ध (ब्राह्मण वर्ण, वेदों का समर्थन, प्राचीन समयरेखा) बनाम गौतम बुद्ध (क्षत्रिय शाक्य वंश, लुंबिनी जन्म ~563 ईसा पूर्व, वेदों को अस्वीकार किया)। यह दिन कूर्म जयंती के साथ भी मेल खाता है और सत्यनारायण पूजा के लिए सबसे शुभ दिन है। क्षेत्रीय भिन्नता: ओडिशा और बंगाल की परंपराओं में दशावतार में 9वें अवतार के रूप में बुद्ध की जगह बलराम को रखा गया है।',
        'नरसिंह मेहता जन्म जयंती' => 'आदि कवि नरसिंह मेहता की जयंती',
        'अपरा एकादशी' => 'अपरा एकादशी के लिए व्रत',
        'योगी महाराज जयंती' => 'ब्रह्मस्वरूप योगी महाराज का जन्म',
        'शनि जयंती / सावित्री अमावस्या' => 'भगवान शनि का जन्म / सावित्री व्रत',
        'जामाइ षष्ठी' => 'दामाद को समर्पित बंगाली त्योहार',
        'महेश नवमी' => 'माहेश्वरी समाज द्वारा भगवान शिव की पूजा',
        'गंगा दशहरा' => 'पृथ्वी पर माता गंगा का अवतरण',
        'निर्जला एकादशी' => 'सबसे कठिन एकादशी व्रत (बिना जल के किया जाने वाला) / गायत्री जयंती',
        'वट पूर्णिमा' => 'पूर्णिमान्त कैलेंडर के अनुसार वट सावित्री व्रत',
        'योगिनी एकादशी' => 'योगिनी एकादशी के लिए व्रत',
        'जगन्नाथ रथ यात्रा' => 'भगवान जगन्नाथ का रथ उत्सव',
        'देवशयनी एकादशी' => 'चातुर्मास आरंभ, भगवान विष्णु योगनिद्रा में जाते हैं',
        'गौरी व्रत (मोलाकत) प्रारंभ' => 'छोटी कन्याओं द्वारा 5 दिवसीय व्रत (बिना नमक का)',
        'जया पार्वती व्रत प्रारंभ' => 'वैवाहिक सुख और अच्छे पति के लिए 5 दिवसीय व्रत',
        'गुरु पूर्णिमा' => 'आध्यात्मिक गुरुओं और महर्षि व्यास का सम्मान',
        'कामिका एकादशी' => 'कामिका एकादशी के लिए व्रत',
        'हरियाली तीज' => 'बारिश का स्वागत करने वाला मानसून त्योहार',
        'नाग पंचमी' => 'सर्प देवताओं की पूजा',
        'कल्कि जयंती' => 'कल्कि अवतार का जन्म',
        'तुलसीदास जयंती' => 'गोस्वामी तुलसीदास की जयंती',
        'श्रावण पुत्रदा एकादशी' => 'पुत्र प्राप्ति के लिए व्रत',
        'रक्षा बंधन / अवनी अवित्तम' => 'भाई-बहन का बंधन / हयग्रीव जन्म / उपाकर्म',
        'पोला / कुशोत्पाटिनी अमावस्या' => 'किसानों और बैलों के लिए धन्यवाद उत्सव',
        'अजा एकादशी' => 'अजा एकादशी के लिए व्रत',
        'गोगा पंचम / गोगा पंचमी (नाग पंचमी - गुजरात)' => 'गोगा जी / गोगा महाराज और सर्प देवताओं का सम्मान करने वाली गुजराती नाग पंचमी',
        'श्रावण सोमवार (सोमवार व्रत)' => 'भगवान शिव को समर्पित श्रावण मास का शुभ सोमवार',
        'कजरी तीज' => 'कजरी तीज उत्सव',
        'बोल चौथ' => 'गायों और बछड़ों की पूजा (बहुला चतुर्थी)',
        'रांधण छठ / बलराम जयंती (हल षष्ठी)' => 'गुजराती रांधण छठ और कृष्ण षष्ठी पर व्यापक हल षष्ठी / बलराम जयंती का पर्व',
        'शीतला सातम / शीतला सप्तमी' => 'शीतला माता का पर्व, जिसे गुजरात में शीतला सातम के रूप में जाना जाता है, स्वास्थ्य के लिए प्रार्थना और ठंडे भोजन के प्रसाद द्वारा मनाया जाता है',
        'कृष्ण जन्माष्टमी' => 'भगवान कृष्ण का जन्मोत्सव',
        'हरतालिका तीज / केवड़ा त्रीज' => 'हरतालिका तीज, जिसे गुजरात में केवड़ा त्रीज के नाम से जाना जाता है, महिलाओं द्वारा पार्वती और शिव के सम्मान में मनाया जाता है',
        'वराह जयंती' => 'भगवान वराह का प्राकट्य दिवस',
        'गणेश चतुर्थी' => 'भगवान गणेश की जयंती',
        'ऋषि पंचमी' => 'सप्तर्षियों की पूजा',
        'राधा अष्टमी' => 'राधारानी की जयंती',
        'पार्श्व एकादशी / जल झिलानी एकादशी' => 'भगवान विष्णु करवट बदलते हैं / स्वामीनारायण जल झिलानी उत्सव',
        'महंत स्वामी महाराज जन्म जयंती' => 'महंत स्वामी महाराज का भौतिक जन्म दिवस (13 सितंबर 1933, भादरवा वद 9)',
        'महंत स्वामी महाराज पार्षदी दीक्षा दिन (आधिकारिक जयंती)' => 'पार्षदी दीक्षा दिन (2 फरवरी 1957, महा वद 1) पर महंत स्वामी महाराज जयंती का आधिकारिक BAPS उत्सव',
        'वामन जयंती' => 'वामन अवतार का जन्म',
        'अनंत चतुर्दशी' => 'भगवान अनंत की पूजा; गणेश विसर्जन',
        'पितृ पक्ष प्रारंभ' => 'पूर्वजों के पखवाड़े की शुरुआत',
        'इन्दिरा एकादशी' => 'इन्दिरा एकादशी के लिए व्रत',
        'महालय अमावस्या' => 'पितृ पक्ष का अंतिम दिन (सर्वपित्री अमावस्या)',
        'ललिता पंचमी' => 'नवरात्रि के दौरान देवी ललिता त्रिपुरसुंदरी की पूजा',
        'दशहरा / विजयदशमी' => 'रावण पर भगवान राम की जीत / शरद नवरात्रि का समापन',
        'पापांकुशा एकादशी' => 'पापांकुशा एकादशी के लिए व्रत',
        'शरद पूर्णिमा / माणेकठारी पूनम / गुणातीतानंद स्वामी जयंती' => 'शरद पूर्णिमा, जिसे गुजरात में माणेकठारी पूनम के रूप में जाना जाता है, और गुणातीतानंद स्वामी की जयंती',
        'वाल्मीकि जयंती' => 'महर्षि वाल्मीकि की जयंती',
        'रमा एकादशी' => 'रमा एकादशी के लिए व्रत',
        'करवा चौथ' => 'विवाहित महिलाएं पति की लंबी उम्र के लिए व्रत रखती हैं',
        'अहोई अष्टमी' => 'माताएं बच्चों की भलाई के लिए व्रत रखती हैं',
        'वाघ बारस (गोवत्स द्वादशी)' => 'गायों और बछड़ों की पूजा',
        'धनतेरस' => 'लक्ष्मी और धन्वंतरि की पूजा',
        'काली चौदस (नरक चतुर्दशी)' => 'देवी काली की पूजा और नरकासुर पर विजय',
        'काली पूजा / दिवाली' => 'रोशनी का त्योहार / देवी काली की पूजा',
        'गोवर्धन पूजा / बेस्तु वरस / अन्नकूट' => 'अन्नकूट (स्वामीनारायण) / गुजराती नव वर्ष',
        'भाई दूज' => 'भाई-बहन के रिश्ते का उत्सव',
        'लाभ पंचम' => 'गुजरात में व्यवसायों के लिए शुभ दिन',
        'स्कंद षष्ठी' => 'भगवान मुरुगन को समर्पित छह दिवसीय उत्सव, राक्षस सूरपद्मन पर उनकी जीत का जश्न',
        'छठ पूजा (संध्या अर्घ्य)' => 'छठ पूजा का प्रमुख दिन (4 में से तीसरा) - सूर्य को संध्या अर्घ्य; पर्व कार्तिक शुक्ल 4-7 तक चलता है',
        'जलाराम जयंती' => 'वीरपुर के संत जलाराम बापा की जयंती',
        'गोपाष्टमी' => 'गायों की पूजा और उत्सव',
        'जगद्धात्री पूजा' => 'बंगाल में देवी जगद्धात्री की पूजा',
        'प्रमुख स्वामी महाराज जयंती' => 'प्रमुख स्वामी महाराज की जयंती (7 दिसंबर 1921, मगशर सुद 8, विक्रम संवत 1978)',
        'देवोत्थान (प्रबोधिनी) एकादशी' => 'प्रबोधिनी एकादशी / चातुर्मास का समापन',
        'तुलसी विवाह' => 'तुलसी और शालिग्राम (विष्णु) का औपचारिक विवाह',
        'वैकुंठ चतुर्दशी' => 'विष्णु और शिव दोनों के भक्तों के लिए पवित्र दिन',
        'देव दिवाली (त्रिपुरारी पूर्णिमा)' => 'त्रिपुरासुर पर शिव की जीत का जश्न मनाने वाला वाराणसी का त्योहार; घाटों को दीयों से रोशन किया जाता है',
        'कार्तिगई दीपम' => 'रोशनी का तमिल त्योहार; तिरुवन्नामलाई में महा दीपम जलाया जाता है',
        'उत्पन्ना एकादशी' => 'उत्पन्ना एकादशी के लिए व्रत',
        'वचनामृत जयंती' => 'वचनामृत का स्मरणोत्सव',
        'कालभैरव जयंती' => 'भगवान कालभैरव (शिव) का जन्म',
        'विवाह पंचमी' => 'राम और सीता की विवाह वर्षगांठ',
        'गीता जयंती / मोक्षदा एकादशी / वैकुंठ एकादशी' => 'भगवद गीता का उत्सव / मोक्ष का द्वार',
        'दत्तात्रेय जयंती' => 'भगवान दत्तात्रेय का जन्म (अन्नपूर्णा जयंती)',
        'सफला एकादशी' => 'सफला एकादशी के लिए व्रत',
        'पौष पुत्रदा एकादशी' => 'पौष पुत्रदा एकादशी के लिए व्रत',
        'शाकंभरी पूर्णिमा' => 'शाकंभरी नवरात्रि का समापन; देवी शाकंभरी की पूजा जिन्होंने सब्जियों और फलों से दुनिया का पोषण किया',
        'थाई पूसम' => 'भगवान मुरुगन को समर्पित तमिल त्योहार; यह तब मनाया जाता है जब तमिल महीने थाई (जनवरी-फरवरी) में पुष्य नक्षत्र पूर्णिमा के साथ मेल खाता है',
        'ओणम (तिरुवोणम)' => 'केरल का फसल उत्सव; मलयालम महीने चिंगम (अगस्त-सितंबर) में तिरुवोणम नक्षत्र (श्रवण); राजा महाबली की वार्षिक यात्रा का प्रतीक है',
        'गुणातीतानंद स्वामी दीक्षा दिन' => 'गुणातीतानंद स्वामी का दीक्षा दिवस',
        'षटतिला एकादशी' => 'षटतिला एकादशी के लिए व्रत',
        'मौनी अमावस्या' => 'कठोर मौन व्रत और पवित्र स्नान का दिन',
        'वसंत पंचमी / शिक्षापत्री जयंती' => 'देवी सरस्वती की पूजा / शिक्षापत्री जयंती',
        'रथ सप्तमी' => 'सूर्य जयंती',
        'भीष्म अष्टमी' => 'भीष्म पितामह के प्रस्थान की वर्षगांठ',
        'जया एकादशी' => 'जया एकादशी के लिए व्रत',
        'माघी पूर्णिमा / मासी मगम' => 'कुंभ मेला स्नान का दिन / तमिल पवित्र स्नान दिवस',
        'पुष्पदोलोत्सव (धुलेटी)' => 'रंगों का त्योहार (धुलेटी/पुष्पदोलोत्सव)',
        'विजया एकादशी' => 'विजया एकादशी के लिए व्रत',
        'महा शिवरात्रि' => 'भगवान शिव की महान रात्रि',
        'फुलेरा दूज' => 'फूलों का त्योहार',
        'आमलकी एकादशी' => 'आमलकी एकादशी के लिए व्रत',
        'होलिका दहन' => 'अलाव समारोह, बुराई पर अच्छाई की जीत',
        'भगतजी महाराज जयंती' => 'भगतजी महाराज का जन्म (स्वामीनारायण संप्रदाय)',
        'होली' => 'रंगों का त्योहार',
        'वरलक्ष्मी व्रतम' => 'समृद्धि के लिए देवी लक्ष्मी की पूजा',
        'पद्मिनी एकादशी' => 'विशेष एकादशी जो केवल अधिक मास के दौरान आती है',
        'परमा एकादशी' => 'विशेष एकादशी जो केवल अधिक मास के कृष्ण पक्ष में आती है',
    ],
],
        'Deity' => [
            'en' => [],
            'hi' => [],
            'gu' => [],
        ],
        'Region' => [
            'en' => ['Pan-India' => 'Pan-India'],
            'hi' => ['Pan-India' => 'संपूर्ण भारत'],
            'gu' => ['Pan-India' => 'સમગ્ર ભારત'],
        ],
        'MuhurtaPeriod' => [
            'en' => ['Day' => 'Day', 'Night' => 'Night'],
            'hi' => ['Day' => 'दिन', 'Night' => 'रात्रि'],
            'gu' => ['Day' => 'દિવસ', 'Night' => 'રાત્રિ'],
        ],
        'Source' => [
            'en' => [
                'Muhurta Chintamani / Brihat Samhita' => 'Muhurta Chintamani / Brihat Samhita',
                'Muhurta Chintamani' => 'Muhurta Chintamani',
                'Classical Muhurta texts' => 'Classical Muhurta texts',
                'Muhurta Chintamani / Gargiya Jyotisha' => 'Muhurta Chintamani / Gargiya Jyotisha',
                'Visha Ghati constants' => 'Visha Ghati constants',
                'Muhurta Chintamani / Muhurta Martanda' => 'Muhurta Chintamani / Muhurta Martanda',
                'Rule engine' => 'Rule engine',
                'Transit-only evaluation' => 'Transit-only evaluation',
                'Muhūrta Chintāmaṇi / Nārada Saṁhitā' => 'Muhūrta Chintāmaṇi / Nārada Saṁhitā',
                '15-part night Muhurta model' => '15-part night Muhurta model',
                '30 Muhurta day division' => '30 Muhurta day division',
                'Observed Panchang convention; tradition-dependent' => 'Observed Panchang convention; tradition-dependent',
                'Sandhyavandanam practice convention' => 'Sandhyavandanam practice convention',
                'Published Gowri/Pambu table convention' => 'Published Gowri/Pambu table convention',
                'Ashtanga Hridaya Sutrasthana 2:1, Charaka Samhita, Manu Smriti 4.92' => 'Ashtanga Hridaya Sutrasthana 2:1, Charaka Samhita, Manu Smriti 4.92',
                'Muhurta Martanda / Bhadra (Vishti Karana) window from Panchang day calculation' => 'Muhurta Martanda / Bhadra (Vishti Karana) window from Panchang day calculation',
                'Varjyam (Tyajyam) window from Panchang day calculation' => 'Varjyam (Tyajyam) window from Panchang day calculation',
                '8th of 15 (Abhijit)' => '8th of 15 (Abhijit)',
            ],
            'hi' => [
                'Muhurta Chintamani / Brihat Samhita' => 'मुहूर्त चिंतामणि / बृहत् संहिता',
                'Muhurta Chintamani' => 'मुहूर्त चिंतामणि',
                'Classical Muhurta texts' => 'शास्त्रीय मुहूर्त ग्रंथ',
                'Muhurta Chintamani / Gargiya Jyotisha' => 'मुहूर्त चिंतामणि / गर्गिय ज्योतिष',
                'Visha Ghati constants' => 'विष घटी स्थिरांक',
                'Muhurta Chintamani / Muhurta Martanda' => 'मुहूर्त चिंतामणि / मुहूर्त मार्टांड',
                'Rule engine' => 'नियम इंजन',
                'Transit-only evaluation' => 'केवल गोचर मूल्यांकन',
                'Muhūrta Chintāmaṇi / Nārada Saṁhitā' => 'मुहूर्त चिंतामणि / नारद संहिता',
                '15-part night Muhurta model' => '15-भाग रात्रि मुहूर्त मॉडल',
                '30 Muhurta day division' => '30 मुहूर्त दिन विभाजन',
                'Observed Panchang convention; tradition-dependent' => 'अनुभवी पंचांग परंपरा; परंपरा-निर्भर',
                'Sandhyavandanam practice convention' => 'संध्यावंदनम अभ्यास परंपरा',
                'Published Gowri/Pambu table convention' => 'प्रकाशित गौरी/पम्बू तालिका परंपरा',
                'Ashtanga Hridaya Sutrasthana 2:1, Charaka Samhita, Manu Smriti 4.92' => 'अष्टांग हृदय सूत्रस्थान 2:1, चरक संहिता, मनु स्मृति 4.92',
                'Muhurta Martanda / Bhadra (Vishti Karana) window from Panchang day calculation' => 'मुहूर्त मार्टांड / भद्र (विष्टि करण) पंचांग दिन गणना',
                'Varjyam (Tyajyam) window from Panchang day calculation' => 'वर्ज्यम (त्याज्यम) पंचांग दिन गणना',
                '8th of 15 (Abhijit)' => '15 में से 8वाँ (अभिजित)',
            ],
            'gu' => [
                'Muhurta Chintamani / Brihat Samhita' => 'મુહૂર્ત ચિંતામણિ / બૃહત સંહિતા',
                'Muhurta Chintamani' => 'મુહૂર્ત ચિંતામણિ',
                'Classical Muhurta texts' => 'શાસ્ત્રીય મુહૂર્ત ગ્રંથો',
                'Muhurta Chintamani / Gargiya Jyotisha' => 'મુહૂર્ત ચિંતામણિ / ગર્ગિય જ્યોતિષ',
                'Visha Ghati constants' => 'વિષ ઘટી સ્થિરાંક',
                'Muhurta Chintamani / Muhurta Martanda' => 'મુહૂર્ત ચિંતામણિ / મુહૂર્ત માર્તાંડ',
                'Rule engine' => 'નિયમ એન્જિન',
                'Transit-only evaluation' => 'માત્ર ગોચર મૂલ્યાંકન',
                'Muhūrta Chintāmaṇi / Nārada Saṁhitā' => 'મુહૂર્ત ચિંતામણિ / નારદ સંહિતા',
                '15-part night Muhurta model' => '15-ભાગ રાત્રિ મુહૂર્ત મોડલ',
                '30 Muhurta day division' => '30 મુહૂર્ત દિવસ વિભાજન',
                'Observed Panchang convention; tradition-dependent' => 'અનુભવી પંચાંગ પરંપરા; પરંપરા-નિર્ભર',
                'Sandhyavandanam practice convention' => 'સંધ્યાવંદનમ અભ્યાસ પરંપરા',
                'Published Gowri/Pambu table convention' => 'પ્રકાશિત ગૌરી/પંબૂ તાલીકા પરંપરા',
                'Ashtanga Hridaya Sutrasthana 2:1, Charaka Samhita, Manu Smriti 4.92' => 'અષ્ટાંગ હૃદય સૂત્રસ્થાન 2:1, ચરક સંહિતા, મનુ સ્મૃતિ 4.92',
                'Muhurta Martanda / Bhadra (Vishti Karana) window from Panchang day calculation' => 'મુહૂર્ત માર્તાંડ / ભદ્ર (વિષ્ટિ કરણ) પંચાંગ દિવસ ગણતરી',
                'Varjyam (Tyajyam) window from Panchang day calculation' => 'વર્જ્યમ (ત્યાજ્યમ) પંચાંગ દિવસ ગણતરી',
                '8th of 15 (Abhijit)' => '15 માંથી 8મું (અભિજિત)',
            ],
        ],
        'String' => [
            'en' => [
                'Day' => 'Day', 'Night' => 'Night', 'Rahu Kaal' => 'Rahu Kaal', 'Gulika' => 'Gulika', 'Yamaganda' => 'Yamaganda',
                'Abhijit' => 'Abhijit', 'Nishita' => 'Nishita', 'Vijaya' => 'Vijaya', 'Godhuli' => 'Godhuli',
                'Pratah Sandhya' => 'Pratah Sandhya', 'Madhyahna Sandhya' => 'Madhyahna Sandhya', 'Sayahna Sandhya' => 'Sayahna Sandhya',
                'Brahma Muhurta' => 'Brahma Muhurta', 'Dagdha Tithi' => 'Dagdha Tithi', 'Dagdha Yoga' => 'Dagdha Yoga',
                'Rikta Tithi' => 'Rikta Tithi', 'Varjyam' => 'Varjyam', 'Abhijit Muhurta' => 'Abhijit Muhurta',
                'Varjyam (Visha Ghati)' => 'Varjyam (Visha Ghati)',
                'Sun Sign' => 'Sun Sign', 'Moon Sign' => 'Moon Sign',
                'Muhurta is auspicious. Proceed with confidence.' => 'Muhurta is auspicious. Proceed with confidence.',
                'Muhurta is inauspicious. Finding alternative time recommended.' => 'Muhurta is inauspicious. Finding alternative time recommended.',
                'Muhurta has significant doshas. Remedies may help but alternative preferred.' => 'Muhurta has significant doshas. Remedies may help but alternative preferred.',
                'Muhurta is acceptable but has minor doshas. Consider remedies.' => 'Muhurta is acceptable but has minor doshas. Consider remedies.',
                'Abhijit Muhurta - High Dosha Cancellation Power' => 'Abhijit Muhurta - High Dosha Cancellation Power',
                'Abhijit power cancelled (Wednesday)' => 'Abhijit power cancelled (Wednesday)',
                'Not in Abhijit Muhurta' => 'Not in Abhijit Muhurta',
                'Krishna Paksha (waning)' => 'Krishna Paksha (waning)',
                'Shukla Paksha (waxing)' => 'Shukla Paksha (waxing)',
            ],
            'hi' => [
                'Day' => 'दिन', 'Night' => 'रात्रि', 'Rahu Kaal' => 'राहु काल', 'Gulika' => 'गुलिका', 'Yamaganda' => 'यमघण्ट',
                'Abhijit' => 'अभिजित', 'Nishita' => 'निशिथ', 'Vijaya' => 'विजय', 'Godhuli' => 'गोधूलि',
                'Pratah Sandhya' => 'प्रातः सन्ध्या', 'Madhyahna Sandhya' => 'मध्याह्न सन्ध्या', 'Sayahna Sandhya' => 'सायह्न सन्ध्या',
                'Brahma Muhurta' => 'ब्रह्म मुहूर्त', 'Dagdha Tithi' => 'दग्ध तिथि', 'Dagdha Yoga' => 'दग्ध योग',
                'Rikta Tithi' => 'रिक्ता तिथि', 'Varjyam' => 'वर्ज्यम', 'Abhijit Muhurta' => 'अभिजित मुहूर्त',
                'Varjyam (Visha Ghati)' => 'वर्ज्यम (विष घाटी)',
                'Sun Sign' => 'सूर्य राशि', 'Moon Sign' => 'चन्द्र राशि',
                'Muhurta is auspicious. Proceed with confidence.' => 'मुहूर्त शुभ है। विश्वास के साथ आगे बढ़ें।',
                'Muhurta is inauspicious. Finding alternative time recommended.' => 'मुहूर्त अशुभ है। वैकल्पिक समय खोजने की अनुशंसा की जाती है।',
                'Muhurta has significant doshas. Remedies may help but alternative preferred.' => 'मुहूर्त में महत्वपूर्ण दोष हैं। उपाय मदद कर सकते हैं लेकिन वैकल्पिक समय बेहतर है।',
                'Muhurta is acceptable but has minor doshas. Consider remedies.' => 'मुहूर्त स्वीकार्य है लेकिन इसमें छोटे दोष हैं। उपायों पर विचार करें।',
                'Abhijit Muhurta - High Dosha Cancellation Power' => 'अभिजित मुहूर्त - उच्च दोष निवारण शक्ति',
                'Abhijit power cancelled (Wednesday)' => 'अभिजित शक्ति रद्द (बुधवार)',
                'Not in Abhijit Muhurta' => 'अभिजित मुहूर्त में नहीं',
                'Krishna Paksha (waning)' => 'कृष्ण पक्ष',
                'Shukla Paksha (waxing)' => 'शुक्ल पक्ष',
            ],
            'gu' => [
                'Day' => 'દિવસ', 'Night' => 'રાત્રિ', 'Rahu Kaal' => 'રાહુ કાળ', 'Gulika' => 'ગુલિકા', 'Yamaganda' => 'યમઘંટ',
                'Abhijit' => 'અભિજિત', 'Nishita' => 'નિશિથ', 'Vijaya' => 'વિજય', 'Godhuli' => 'ગોધૂલિ',
                'Pratah Sandhya' => 'પ્રાતઃ સંધ્યા', 'Madhyahna Sandhya' => 'મધ્યાહ્ન સંધ્યા', 'Sayahna Sandhya' => 'સાયહ્ન સંધ્યા',
                'Brahma Muhurta' => 'બ્રહ્મ મુહૂર્ત', 'Dagdha Tithi' => 'દગ્ધ તિથિ', 'Dagdha Yoga' => 'દગ્ધ યોગ',
                'Rikta Tithi' => 'રિક્તા તિથિ', 'Varjyam' => 'વર્જ્યમ', 'Abhijit મુહૂર્ત' => 'અભિજિત મુહૂર્ત',
                'Varjyam (Visha Ghati)' => 'વર્જ્યમ (વિષ ઘાટી)',
                'Sun Sign' => 'સૂર્ય રાશિ', 'Moon Sign' => 'ચંદ્ર રાશિ',
                'Muhurta is auspicious. Proceed with confidence.' => 'મુહૂર્ત શુભ છે. આત્મવિશ્વાસ સાથે આગળ વધો.',
                'Muhurta is inauspicious. Finding alternative time recommended.' => 'મુહૂર્ત અશુભ છે. વૈકલ્પિક સમય શોધવાની ભલામણ કરવામાં આવે છે.',
                'Muhurta has significant doshas. Remedies may help but alternative preferred.' => 'મુહૂર્તમાં નોંધપાત્ર દોષો છે. ઉપાયો મદદ કરી શકે છે પરંતુ વૈકલ્પિક સમય પસંદ કરવામાં આવે છે.',
                'Muhurta is acceptable but has minor doshas. Consider remedies.' => 'મુહૂર્ત સ્વીકાર્ય છે પરંતુ તેમાં ગૌણ દોષો છે. ઉપાયો ધ્યાનમાં લો.',
                'Abhijit Muhurta - High Dosha Cancellation Power' => 'અભિજિત મુહૂર્ત - ઉચ્ચ દોષ નિવારણ શક્તિ',
                'Abhijit power cancelled (Wednesday)' => 'અભિજિત શક્તિ રદ (બુધવાર)',
                'Not in Abhijit Muhurta' => 'અભિજિત મુહૂર્તમાં નથી',
                'Krishna Paksha (waning)' => 'કૃષ્ણ પક્ષ',
                'Shukla Paksha (waxing)' => 'શુક્લ પક્ષ',
            ],
        ],
    ];

    public static function translate(string $type, int|string $key, ?string $locale = null): string
    {
        if ($key === '') return '';
        $locale ??= AstroCore::getConfig('panchang.defaults.locale', 'en');
        if (!isset(self::$translations[$type][$locale])) $locale = 'en';
        if ($type === 'String') return self::$translations['String'][$locale][$key] ?? self::$translations['Common'][$locale][$key] ?? (string) $key;
        // For FestivalDesc and Deity: return key as fallback (key IS the description/deity name)
        if ($type === 'FestivalDesc' || $type === 'Deity') return (string) $key;
        return self::$translations[$type][$locale][$key] ?? (string) $key;
    }
}
